### PR TITLE
Reintroduce stream refs

### PR DESCRIPTION
**Pull request by Horusiath**
This PR reintroduces changes for `FunctionRef` and `StreamRefs`, that were accidentally reverted. 
Also introduces `Flow.Watch` and `Flow.Ask` (see #3517).

/cc @Aaronontheweb

### CODE REVIEW

**Comment by Horusiath** [comment]
No idea why, but I cannot attach updated api approvals - git just doesn't pick them up.

**Comment by Aaronontheweb** [comment]
@Horusiath I started having the same problem recently too - wonder if it's something we added to .GITIGNORE that is doing it. I had this issue long before we did https://github.com/akkadotnet/akka.net/pull/3535 though

**Comment by pshrosbree** [comment]
You could edit your gitignore and see if you still have the problem...

**Comment by Horusiath** [comment]
It was my fault - when test failure was happening, I got approved/received files and edited them directly - therefore I was editing copy represented in bin instead of the original file being copied.

**Comment by Aaronontheweb** [comment]
`FlowAskSpec.Flow_with_ask_must_signal_ask_failure` - legit failure

**Pull request merged**
