### PR TITLE
Add support to `ByteString` for copying to/from `Memory` and `Span`

### PR DESCRIPTION
**Pull request by Arkatufus**
## Changes
Add `CopyTo` and `CopyFrom` `Memory` and `Span` support to `ByteString`

### CODE REVIEW

**Comment by to11mtm** [comment]
Should we consider going away from `ArraySegment` for internal storage and use `Memory` instead? On one hand it would be a bit of a yak shave, on the other hand it should greatly simplify the internal logic (since with `Memory` we can slice and not have to consider offset/length in other methods)

**Comment by Arkatufus** [comment]
I don't think we will get any improvement switching over to Memory<T>, even microsoft ReadOnlySequence<T> still uses ArraySegment<T> underneath.

**Comment by Aaronontheweb** [comment]
> I don't think we will get any improvement switching over to Memory, even microsoft ReadOnlySequence still uses ArraySegment underneath.

being able to work with new native APIs in .NET 6 without copying is a big improvement: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receiveasync?view=net-6.0#system-net-sockets-socket-receiveasync(system-memory((system-byte))-system-net-sockets-socketflags-system-threading-cancellationtoken)

**Comment by Arkatufus** [comment]
Hmmm... true, as long as we ditch dotnetty

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
This is small PR and doesn't do much to change the internals of `ByteString` - we should address the internals of this later, once we are in a better position to support System.Memory throughout the serialization and transport system.

**Pull request merged**
