### PR TITLE
Implemented DeadLetterSupression

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Implemented DeadLetterSupression
http://doc.akka.io/docs/akka/2.4.3/scala/event-bus.html#Dead_Letters

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
And we should add this interface to these classes
```csharp
Akka.Actor.PoisonPill
Akka.Actor.Terminated
Akka.IO.SelectionHandler+ChannelReadable
Akka.IO.SelectionHandler+ChannelWritable
Akka.IO.Tcp+CloseCommand
Akka.IO.Tcp+ConnectionClosed
Akka.Persistence.ReplayedMessage
Akka.Persistence.RecoverySuccess
Akka.Persistence.ReplayMessagesFailure
Akka.Pattern.BackoffSupervisor+StartChild
Akka.Pattern.BackoffSupervisor+ResetRestartCount
Akka.Dispatch.SysMsg.Terminate
Akka.Dispatch.SysMsg.DeathWatchNotification
Akka.Remote.Transport.DisassociateUnderlying
Akka.Remote.Transport.Disassociated
Akka.Cluster.Heartbeat
Akka.Cluster.HeartbeatRsp
Akka.Cluster.Tools.Client.ClusterReceptionist+GetContacts
Akka.Cluster.Tools.Client.ClusterReceptionist+Heartbeat
Akka.Cluster.Tools.Client.ClusterReceptionist+HeartbeatRsp
Akka.Cluster.Tools.Client.ClusterReceptionist+Ping
Akka.Cluster.Tools.PublishSubscribe.SubscribeAck 
Akka.Cluster.Tools.PublishSubscribe.Internal.Status
Akka.Cluster.Tools.PublishSubscribe.Internal.Delta
Akka.Cluster.Sharding.PersistentShardCoordinator+Register
Akka.Cluster.Sharding.PersistentShardCoordinator+GetShardHome
Akka.Cluster.Sharding.PersistentShardCoordinator+RegisterProxy
```

and here
```csharp
Akka.Persistence.Sql.Common.Journal.PersistenceIdAdded
Akka.Persistence.Sql.Common.Journal.EventAppended
Akka.Persistence.Sql.Common.Journal.CurrentPersistenceIds
Akka.Persistence.Sql.Common.Journal.TaggedEventAppended
Akka.Persistence.Sql.Common.Journal.ReplayedTaggedMessage
Akka.Streams.Implementation.IO.InputStreamPublisher+Continue
Akka.Streams.Implementation.IO.FilePublisher+Continue
Akka.Streams.Implementation.MultiStreamOutputProcessor+SubstreamRequestMore
Akka.Streams.Implementation.MultiStreamOutputProcessor+SubstreamCancel
Akka.Streams.Implementation.MultiStreamOutputProcessor+SubstreamSubscribe
Akka.Streams.Implementation.MultiStreamOutputProcessor+SubstreamSubscriptionTimeout
Akka.Streams.Implementation.FanIn+OnError
Akka.Streams.Implementation.FanIn+OnComplete
Akka.Streams.Implementation.FanIn+OnNext
Akka.Streams.Implementation.FanIn+OnSubscribe
Akka.Streams.Implementation.FanOut+SubstreamRequestMore
Akka.Streams.Implementation.FanOut+SubstreamCancel
Akka.Streams.Implementation.FanOut+SubstreamSubscribePending
```
```
akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Conductor.scala 
akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala 
akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala
akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala
akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala 
akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala 
akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
```

**Comment by Danthar** [comment]
@alexvaluyskiy can you rebase on dev please? And please squash your commits per the contributors guidelines. Thx for effort!

**Comment by alexvaluyskiy** [comment]
@Danthar done

**Comment by Danthar** [comment]
The failing unit test is a race condition. i verified that it works locally.

**Comment by Danthar** [comment]
Ok, we have a a consistently failing MNTK spec.

Akka.Remote.Tests.MultiNode.RemoteNodeRestartDeathWatchMultiNode1.Must_receive_terminated_when_remote_actor_system_is_restarted

This needs to be investigated and fixed before this PR can be merged.

**Comment by Aaronontheweb** [comment]
Needs to be rebased :(

**Comment by Danthar** [comment]
Since alot of fixes has been made to the MNTK. Could you please rebase on the latest dev? Some of the issues reported in this thread might 'magically' fix themselves now ;)

**Comment by alexvaluyskiy** [comment]
@cconstantin your commit https://github.com/akkadotnet/akka.net/pull/1947 broke persistence tests in this commit

**Comment by Danthar** [comment]
Restarted test builds. Tests still failing.

**Comment by Aaronontheweb** [comment]
Throws a `NullReferenceException` inside the `PatternSpec.GracefulStop` specs

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb It throws NullReferenceException, because the new DeadLetter should not be created, if Sender is null. But gracefulStop send NoSender

**Comment by veblush** [comment]
@alexvaluyskiy @Aaronontheweb Oh I found what caused this problem.

Akka seems to keep sender not-null in packing a message into the `Envelop`. [AbstractDispatcher.scala](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L27)

```
object Envelope { 
  def apply(message: Any, sender: ActorRef, system: ActorSystem): Envelope = { 
    if (message == null) throw new InvalidMessageException("Message is null") 
      new Envelope(message, if (sender ne Actor.noSender) sender else system.deadLetters) 
  } 
} 
```

But Akka.NET doesn't do like this. It just packs a message into `Envelop` without changes and
it keeps Envelope.Sender null if sender is null.

```csharp
var m = new Envelope {
  Sender = sender,
  Message = message,
};

```

This looks like a fundamental difference and should be considered.

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb what do you think about last commit?

**Comment by alexvaluyskiy** [comment]
@Horusiath this test "FSharp.Tests.ApiTests.actor that accepts unit will receive unit message" sends an empty message. But never versions of Akka Jvm forbid it, as @veblush mentioned before. How could we change this test?

**Comment by Horusiath** [comment]
If nullish values are going to be explicitly forbidden, then that test is no longer needed. However this also means, that it's a breaking change and should  be mentioned as that in release notes.

**Comment by Danthar** [comment]
Looks good!. Links back to: https://github.com/akkadotnet/akka.net/issues/2160

**Pull request merged**
