### PR TITLE
Hocon toString() with correct fallback  behavior

### PR DESCRIPTION
**Pull request by feitzi**
As described in #3886 the `Config.ToString(true)` doesn't include all fallback values. 
The reason for the missing value is, that the toString() methods of the underlying hocon classes do skip all fallback values. 

```csharp
if (kvp.Value.AdoptedFromFallback) continue;
```

With this PR I adapted this behavior with an internal toString() that also expects an `includeFallback` boolean. The public toString() uses  this internal overload with 'includeFallback = false`.

Furthermore,  the `toString()` of `config`, changes the internal representation. That isn't expected (at least for me). Therefore I changed this to an immutable merge and execute the merging on this temporarily new object.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@IgorFedchenko did you already implement this in the stand-alone HOCON project?

**Comment by IgorFedchenko** [comment]
> @IgorFedchenko did you already implement this in the stand-alone HOCON project?

@Aaronontheweb Yup, this is already implemented there.

**Comment by Aaronontheweb** [comment]
Implemented in https://github.com/akkadotnet/HOCON/pull/181

**Comment by Aaronontheweb** [comment]
This would actually be really useful in debugging some of the issues I'm running into with https://github.com/akkadotnet/akka.net/pull/4128

**Pull request merged**
