### PR TITLE
do-not-merge

### PR DESCRIPTION
**Pull request by KadekM**
... trying to find problem

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
think it could be the `Resizer` that's causing the problem?

**Comment by KadekM** [comment]
Yes - i have done some poking around it. SomeActor receives 'hit' resize is initiated, at first is resized by one (all's good), but then another and another resizing starts to happen...

**Comment by KadekM** [comment]
(another resizimgs happen before 'hits' are sent... I will try play with for some more later in the day...

**Comment by Aaronontheweb** [comment]
We've had issues with the Resizer before - it's somewhat imprecise. I wouldn't be surprised if that was the culprit.

**Comment by rogeralsing** [comment]
Should this also be closed as the Resizer problem was found and fixed?

**Comment by Aaronontheweb** [comment]
@rogeralsing senor @KadekM should re-integrate that change into this PR and uncomment out the failing test and see if that resolves the issue.

**Comment by KadekM** [comment]
@Aaronontheweb: the test is on dev brach - it was never commented out. Issue was patched before PR which was commenting it out was merged (#1302), thus those test pass (whole *RoundRobinSpec) and this issue should by resolved.

**Comment by KadekM** [comment]
Do not close yet please... there still seems to be something wrong (#1274) spec just failed.

**Comment by Aaronontheweb** [comment]
No worries - we'll keep it open

**Pull request closed without merging**
