### PR TITLE
Merge of #762

### PR DESCRIPTION
**Pull request by Aaronontheweb**
See #762 for original PR notes. This merges @HCanber's changes in with all of the other changesets going into V1.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Beautiful, green check mark. And with that I hereby declare

# AKKA.NET V1 CODE COMPLETE

Great job everyone cc @akkadotnet/contributors

**Comment by skotzko** [comment]
captain picard clap

**Comment by Aaronontheweb** [comment]
image

**Comment by Aaronontheweb** [comment]
doggie-dance

**Comment by mmisztal1980** [comment]
http://i.giphy.com/11FHKbYOYB6GtO.gif

**Comment by mmisztal1980** [comment]
image

**Pull request merged**
