### PR TITLE
Fixed a number of compiler warnings

### PR DESCRIPTION
**Pull request by sean-gilliam**
The compiler warnings are getting out of control with at least 102 in
HEAD. Most of these can be ignored since they look to be Obsolete tags
throwing the warnings. This PR reduces the number of warnings to 60.

### CODE REVIEW

**Comment by sean-gilliam** [comment]
Hmm. Looking at the TeamCity output, the error looks to be a xUnit error and not related to my PR.

**Comment by Aaronontheweb** [comment]
@sean-gilliam would you mind rebasing on dev? I have no idea if it will help, but I'm willing to try anything. XUnit still keeps crashing AT THE END of the test run for some reason :(

**Comment by sean-gilliam** [comment]
@Aaronontheweb sure thing

**Comment by sean-gilliam** [comment]
@Aaronontheweb should be gtg now

**Comment by sean-gilliam** [comment]
Hopefully cleaning up these warnings hasn't inadvertently exposed timing issues related to the either build script or the testing. I know you guys recently fixed that stuff. Or maybe it's just FAKE and xUnit hate me. ;`)

**Pull request merged**
