### PR TITLE
WIP Netstandard2.0upgrade

### PR DESCRIPTION
**Pull request by Danthar**
Work in Progress to update everything to netstandard 2.0 and netcore2.0.
First stage was updating TargetFrameworks in all the project files. Which is partly done.

- [X] Akka Core projects update
- [x] Contrib projects update
   - [X] Akka.Cluster.x
   - [X] Akka.DistributedData
   - [x] The rest
- [ ] Benchmark projects should also target and run netcore suite
- [ ] Check and verify project dependencies
   - [x] Update XUnit dependencies (needs XUnit core) 
   - [x] Update to newtonsoft.json 110.2
   - [x] Update to System.Collections.Immutable 1.5.0
- [x] Possibly update CI infrastructure (scripts and such)
- [X] Delete netcorepolyfills, aka, get rid of SerializableAttribute shims
- [ ] ApiApproval project needs updating
- [ ] Example projects needs to directly reference akka projects instead of assemblies, and be .netcore compatible instead of targetting net452. Possibly leave some projects to be net452 on purpose as a canary
   - [ ] Fsharp examples needs to be fixed
- [x] Update akka.Fsharp references to Fsharp.core 4.5.2

This work will be the enabler for some other improvements we have in mind. Feedback is welcome

Note; Lots of the example projects are still in old style csproj. And could use updating. I might do that in here if it gets in the way. But it might be better to make it a seperate issue. Could be an good for first contributors thingy.

### CODE REVIEW

**Comment by Danthar** [comment]
Update to xunit 2.3.1 is needed. Already being merged into dev. Will need to be ported into the 1.4 branch as well. https://github.com/akkadotnet/akka.net/pull/3504

**Comment by Danthar** [comment]
The PingPong and Spawnbenchmark projects have some issues. That needs looking at.

**Comment by Danthar** [comment]
No sure why im not seeing CI pips popping up. But i'd expect tests to run to completion after my last commit. It does so locally at least.

**Comment by Danthar** [comment]
Had to update to netstandard2.0 compat version of FluentAssertions. Massive breaking changes.
read it, and weep.
https://github.com/fluentassertions/fluentassertions/releases/tag/5.0.0

**Comment by Danthar** [comment]
Also: Some notes about stuff we are probably going to run into. https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html#upgrading-tips

**Comment by Aaronontheweb** [comment]
Compile failures

**Comment by heatonmatthew** [comment]
Incidentally I started on the same thing yesterday. Should have checked whether something was already in progress. For now I'll keep working in my fork at https://github.com/heatonmatthew/akka.net/tree/update-netstandard2.0 but I'm keen to consolidate our efforts.

Forgive my ignorance but how best can I work with you in a single fork.

**Comment by Aaronontheweb** [comment]
@heatonmatthew have this completed here: https://github.com/akkadotnet/akka.net/pull/3668 along with our build system overhaul, but I'm waiting on one final piece that I'm working on right now before I merge it all in.

**Pull request closed without merging**
