### PR TITLE
Work in Progress: Prefix some interfaces with "I"

### PR DESCRIPTION
**Pull request by SeanKilleen**
Attempting to pick up where @HCanber left off. I'll remove the WIP when I feel it is ready for review.

This is the first time I'm really building Akka on my machine and at the outset, 36-37 tests usually fail when run via NCrunch (mostly around needing multi-node tests environments and such). So, my benchmark for commits will be that:

* The project builds
* The changes pass a sanity spot-check
* No more than 37 tests fail

Below is my target list of interfaces, per @HCanber's comment on #652 and what he hadn't hit yet:

- [x] Akka.Actor.LoggingFSM, Akka (Public)
- [x]  Akka.Actor.NoSerializationVerificationNeeded, Akka (Public)
- [x]  Akka.Actor.PossiblyHarmful, Akka (Public)
- [x]  Akka.Actor.WithBoundedStash, Akka (Public)
- [x]  Akka.Actor.WithUnboundedStash, Akka (Public)
- [x]  Akka.Dispatch.BlockingMessageQueueSemantics, Akka (Public)
- [x]  Akka.Dispatch.BoundedDequeBasedMessageQueueSemantics, Akka (Public)
- [x]  Akka.Dispatch.BoundedMessageQueueSemantics, Akka (Public)
- [x]  ~~Akka.Dispatch.DequeBasedMailbox, Akka (Public)~~ (was already completed)
- [x]  Akka.Dispatch.DequeBasedMessageQueueSemantics, Akka (Public)
- [x]  Akka.Dispatch.MessageQueues.MessageQueue, Akka (Public)
- [x]  Akka.Dispatch.MultipleConsumerSemantics, Akka (Public)
- [x]  Akka.Dispatch.RequiresMessageQueue, Akka (Public)
- [ ]  Akka.Dispatch.Semantics, Akka (Public)
- [ ]  Akka.Dispatch.SysMsg.SystemMessage, Akka (Public)
- [x]  Akka.Dispatch.UnboundedDequeBasedMessageQueueSemantics, Akka (Public)
- [x]  Akka.Dispatch.UnboundedMessageQueueSemantics, Akka (Public)
- [ ]  Akka.Event.LoggingAdapter, Akka (Public)
- [ ]  Akka.FluentConfigInternals, Akka (Public)
- [ ]  Akka.Remote.InboundMessageDispatcher, Akka.Remote
- [ ]  Akka.Remote.RemoteRef, Akka.Remote
- [ ]  Akka.Routing.ConsistentHashable, Akka (Public)

Let me know if there's a more preferred way to structure this.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@SeanKilleen would you mind rebasing this PR on dev? The interface changes are one of those changesets that create conflicts pretty easily :p

**Comment by SeanKilleen** [comment]
That's definitely my intention --was going to do so after I'd progressed through a few more of them.




I'm honesty newer to that process. Is my thinking okay or is it causing conflicts in the meantime? Don't want to hamper anyone else. Should I rebase as I go?




Thanks for any guidance. Additionally if it would be easier for me to back out and leave this to others, feel free to close the PR -- I won't be offended. :)



—
Sean

E-"mauled" from my mobile device; please excuse typos and brevity.

**Comment by Aaronontheweb** [comment]
Sometimes I just do these merges myself, but lately I've been short on time :\

**Comment by SeanKilleen** [comment]
@Aaronontheweb totally understandable -- I'm excited for the session at dotNetFringe next weekend! 

I'm fine with however you'd like to do it, I'm not not used to contributing so if you have any guidance for how you'd like me to proceed with this chunk of commits, I'm happy to hear it.

Would you prefer that I make all of the small commits for all the checkboxes, then rebase, then remove WIP and we can look at merging? Or is there another strategy you'd like me to take, such as for example making each of these a separate simpler pull request? 

Happy to do my best to help out -- just want to make sure I'm doing more help than harm to the productivity of the group.

**Comment by SeanKilleen** [comment]
Sorry, I realize I may have misunderstood -- you meant for me to merge dev into this branch currently, I think. Correct? (if so that's totally fine, no problem)

**Comment by Aaronontheweb** [comment]
Basically what I meant is bring in the latest changes sitting on the `dev` branch into the branch on this PR, so that way the "Merge pull request" button turns green ;p

**Comment by SeanKilleen** [comment]
@Aaronontheweb quick question -- some of these tests that are failing appear to be tests that have nothing to do with my edits (in this case, `DefaultResizer_must_grow_as_needed_under_pressure()`.

In this case, should I ignore the failure, or would you prefer me to re-run the tests somehow?

**Comment by Aaronontheweb** [comment]
@SeanKilleen Stashing is broken - this is a real test  failure:

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=465&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by Aaronontheweb** [comment]
The Resizer / ConsistentHashRouter tests are known to be racy, as are some of the inbox specs. Please go through all failures and carefully review them.

**Comment by SeanKilleen** [comment]
:+1: will do.

**Comment by SeanKilleen** [comment]
@Aaronontheweb I figured out the stashing issue for the most part I believe -- looks to be that I hadn't updated Pigeon.conf with the new values. Going to commit a few more changes so that I can then update all the pigeon.conf values at once and get the stash test green.

**Comment by Aaronontheweb** [comment]
@SeanKilleen excellent - good work!

**Comment by SeanKilleen** [comment]
Checking off `Semantics

**Comment by SeanKilleen** [comment]
@Aaronontheweb now that this has been merged, I assume I have to create another PR to finish it off, correct?

**Pull request merged**
