### PR TITLE
Implement custom VisualStudio test runner for multi-node tests discovery and execution

### PR DESCRIPTION
**Pull request by IgorFedchenko**
This PR is work on #3615

The goal is to be able to include something like thins into multi-node specs project:
```
<ItemGroup>
      <PackageReference Include="Akka.MultiNodeTestRunner.VisualStudio" Version="1.0.0" />
  </ItemGroup>
```

And then running `dotnet test` should discover all MNTR tests and use MNTR to execute those tests.

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
Will move on with small steps. 

#### First step
Since we have our multi-node specs using `[MultiNodeFact]` attributes derived from xunit `[Fact]` attribute, looks like we can reuse some part of [xunit.runner.visualstudio](https://github.com/xunit/visualstudio.xunit) package source. Ideally would be to reference this package and inherit from those types , but I will start from copying their source and making it work as a `Akka.MultiNodeTestRunner.VisualStudio` package.

Actually, right now I already have this done - put this new package source in separate solution (because in Akka.NET solution it was building with some weird nuget warnings, so I decided to use separate solution - at the end, we are going to move it to separate repo anyway). I am publishing package to local folder nuget feed, and using `Akka.Remoting.Tests.MultiNode` project as a sample tests project. 
Right now my package does not discover those tests, but I will fix this. I guess this is related to package name that is hardcoded somewhere in runner sources, as assembly name.

#### Second step
After I will have my own working `Akka.MultiNodeTestRunner.VisualStudio` package, I will try to modify tests discovery to skip usual `[Fact]` tests and only find `[MultiNodeFact]`.

#### Third step
Here is where the actual fun starts: I will need to rewrite test executor to use our MNTR code (possibly modified in some degree) to start `Akka.NodeTestRunner`'s. 

Currently xunit [runs all tests in same process](https://github.com/xunit/xunit/issues/1044#issuecomment-265347025), to enable debugging feature. So most likely **we still will not be able to debug code on nodes** during tests. @Aaronontheweb - do we really need this process isolation on MNTR? Or we can run nodes in separate app domains to give managed code isolation, but be able to debug node code execution?

Anyway, looking at [this doc](https://xunit.net/docs/running-tests-in-parallel) looks like tests execution may be delegated to some other packages like `xunit.execution.dll` - so maybe will need to make forks of those as well.

In addition to existing test runner sources (thank you, opensource!) this resources give some light on how this test runners are structured:
https://docs.microsoft.com/en-us/archive/blogs/bhuvaneshwari/authoring-a-new-visual-studio-unit-test-adapter
http://matthewmanela.com/blog/anatomy-of-the-chutzpah-test-adapter-for-vs-2012-rc/
https://stackoverflow.com/a/38206731/3094849

**Comment by Aaronontheweb** [comment]
> Or we can run nodes in separate app domains to give managed code isolation, but be able to debug node code execution?

We have tried doing this in the past without much success, but you can always try again. I'm open

**Comment by IgorFedchenko** [comment]
> We have tried doing this in the past without much success, but you can always try again. I'm open

Ok, got it. The main reason why I am suggesting this is because xunit should be already doing this in their runner, so I can try to reuse it

**Comment by Aaronontheweb** [comment]
The issues we had in the past amounted to just issues with race conditions being worse and so forth. If we're migrating many of the MNTR methods to be asynchronous (and, in fact, if we implemented the `Main` method in the `NodeRunner.exe` to be `async Task main`) that might help alleviate some of those issues caused by having many threads all blocking / waiting on each other in each individual node.

**Comment by IgorFedchenko** [comment]
Hmm, I see. We shell try then.
Maybe I should also work on closing [this issue](https://github.com/akkadotnet/akka.net/issues/4146) as well.

**Comment by IgorFedchenko** [comment]
Closing this PR because MNTR moved to separate repository. Further work on this PR is here: https://github.com/akkadotnet/Akka.MultiNodeTestRunner/pull/8

**Pull request closed without merging**
