### PR TITLE
Update API Approver reporting

### PR DESCRIPTION
**Pull request by Arkatufus**
The reporting of `Akka.API.Tests` really needs an overhaul.
1. It relies on a very flaky `DiffEngine` to try and guess the best diff viewer installed in the system based on the file extension.
2. It assumes that the person running the test can access both the approved.txt and received.txt file to view the diff
3. `DiffEngine` often fails, resulting in an exception being thrown.
4. There is no diff viewer in the CI pipeline, making debugging impossible.

The better route is to actually embed the diff into the unit test report itself, so that it appears in the failing unit test report.
Diff message format:
```
<<<<<<<<< [ Approved file name ]
[ Line number ] + This line is newly added
[ Line number ] - This line is removed
[ Line number ] ? This line is modified
=========
[ Line number ] + This line is newly added
[ Line number ] - This line is removed
[ Line number ] ? This line is modified
>>>>>>>>> [ Received file name ]
```

### CODE REVIEW

**Comment by Arkatufus** [comment]
Example failed output:
```
Akka.API.Tests.ApiNotApprovedException
Failed API approval. Diff:
<<<<<<<<< CoreAPISpec.ApproveCore.approved.txt
=========
[5060] +     public class static ArrayExtensions
[5061] +     {
[5062] +         public static bool IsNullOrEmpty(this System.Array obj) { }
[5063] +         public static bool NonEmpty(this System.Array obj) { }
[5064] +         public static void Shuffle<T>(this T[] array) { }
[5065] +         public static System.Collections.Generic.Dictionary<T, int> ZipWithIndex<T>(this System.Collections.Generic.IEnumerable<T> collection) { }
[5066] +     }
>>>>>>>>> CoreAPISpec.ApproveCore.received.txt
  Exception doesn't have a stacktrace
```

**Review by IgorFedchenko — COMMENTED** [review]
Does this change anything that is documented here? https://getakka.net/community/public-api-changes.html

If it does not (documentation is up to date, just adds additional output ) - you can treat this PR as approved :)

**Comment by Arkatufus** [comment]
Nothing is changed, it just adds error reporting when the test catches a public API change, instead of a null referece exception

**Review by IgorFedchenko — APPROVED** [review]
LGTM

**Pull request merged**
