### PR TITLE
Make ddata replicator actor configurable to have backoff supervisor

### PR DESCRIPTION
**Pull request by andyfurnival**
Make ddata replicator actor configurable to have backoff supervisor. Defaults to not (original implementation) 

The test maybe a little overkill, I just wanted to prove that the original implementation how users would have it today, behaved the same way, including the way it fails

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Need to approve the changes to the public API https://getakka.net/community/public-api-changes.html

```
cd src/core/Akka.API.Tests
dotnet test -c Release --framework netcoreapp3.1`
```

**Comment by andyfurnival** [comment]
I think @Arkatufus has done a similar change on #5145. I saw your comment to make it configurable, and assumed that was for me. If that other PR is good, i can decline this one

**Comment by Arkatufus** [comment]
@andyfurnival Sure, I can merge your changes to mine.

**Comment by Aaronontheweb** [comment]
@Arkatufus go ahead and do that

**Pull request closed without merging**
