### PR TITLE
Fixes for NoSender serialization bugs

### PR DESCRIPTION
**Pull request by ssoshchepkov**
Fixes for `NoSender` actor serialization bugs described in #1036.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
thanks, @ssoshchepkov - looks like we've overlooked this one.

**Comment by rogeralsing** [comment]
Im not sure this fix is correct.
The scala version of the code uses the old "/nosender" path.
I think there could be more to this than we see here

**Comment by Aaronontheweb** [comment]
@rogeralsing ok, I reverted it. I'll let you take a closer look and see what's really going on.

**Comment by rogeralsing** [comment]
Turns out that its `NoBody` that uses that notation in scala.
`NoSender` in scala is just a wrapper for `null`

@ssoshchepkov if you want, could you adapt the PR to treat NoSender as null instead?
It's better if we stay as close as possible to the Scala code.

**Comment by Aaronontheweb** [comment]
@rogeralsing won't that conflict with your PR that turns `null` into `NoSender`? :p

**Comment by rogeralsing** [comment]
That code could just go away if we do this.
There is no reason to have weird comparisons all over the codebase if nosender really means null imo.

Or?

**Comment by ssoshchepkov** [comment]
@rogeralsing I've made changes to treat `NoSender` as `null`. Could you reopen this PR? Or should I create another?

**Comment by rogeralsing** [comment]
I think you have to send a fresh one. I dont think a PR can be re-opened once merged (as this was merged and then a revert patch applied)

**Pull request merged**
