### PR TITLE
[WIP] Implemented missed router specs

### PR DESCRIPTION
**Pull request by alexvaluyskiy**

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
These test could fail
     Router_in_general_must_default_to_all_for_one_always_escalate_strategy 
     Router_in_general_must_evict_terminated_routees

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy that commit is from the bleeding edge branch of Akka. Is this is the same in latest stable?

**Comment by Aaronontheweb** [comment]
Changes to `RouterConfig` look fine, as do the specs.

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb, yes, these tests from the latests version. But they are very unstable, due to oudated Router's code (and ActorCell code)

**Comment by Aaronontheweb** [comment]
Working on #2024 now - I'll address this as part of that.

**Comment by alexvaluyskiy** [comment]
@Horusiath why you merged it, it was WIP?

**Comment by Horusiath** [comment]
Sorry, it had to some bug in my head.

**Comment by alexvaluyskiy** [comment]
We should wait before @Aaronontheweb fix some issues in ActorCell, after that we should make routers up to date with JVM version. And after that we could merge this PR

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy could you submit a new PR for this?

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb I'm planning to update all local routers code to the latest JVM version. I will do it after all cluster specs. Anyway I should do it after changes in ActorCell, because that code causes  racy conditions

**Comment by Aaronontheweb** [comment]
ok, sounds good

**Pull request merged**
