### PR TITLE
Makes Akka context props available to Serilog templates

### PR DESCRIPTION
**Pull request by akoshelev**
Fixes issue #1423

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@maxim-s looks like we have a race condition with Akka.Persistence FSMs: 

http://petabridge-ci.cloudapp.net/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2672#_focus=13023&guest=1

Could you create an issue for this?

@akoshelev I'll re-run the build as your error is unrelated to this.

**Comment by maxim-s** [comment]
Thank you @Aaronontheweb , I've created issue #1426

**Comment by Aaronontheweb** [comment]
@rogeralsing @stefansedich I don't understand Serilog well enough to understand what this does - would one of you mind reviewing?

**Comment by stefansedich** [comment]
Thanks @akoshelev this was a nice find, I can't believe I missed this when I was in that area recently.

**Pull request merged**
