### PR TITLE
Removed nesting levels in certain places through block-scoped `using` statement and inversion of `if` blocks

### PR DESCRIPTION
**Pull request by Lehonti**
## Changes

No behavior is  changed. Code is just leveraging more modern constructs to improve readability

### Benchmarks

There shouldn't be any performance changes

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Thanks! I'm going to need to take a look at the test suite - these look like racy tests.

**Comment by Aaronontheweb** [comment]
Did you use an auto-formatter to make these changes?

**Comment by Lehonti** [comment]
> Did you use an auto-formatter to make these changes?

I used Visual Studio to do most of the busy work, but I formatted some things manually, too.

decided to keep a formatting that was similar to the original, which means that several `using` statements span several lines. If it were my own code I would do it differently, though.

**Comment by Aaronontheweb** [comment]
Yeah I don't think I'm going to merge this - touches way too many files with changes that I can't really review. If you want to help with formatting, please do it in smaller bite-sized PRs.

**Pull request closed without merging**
