### PR TITLE
Moved AkkaIO transport to Akka.Remote

### PR DESCRIPTION
**Pull request by rogeralsing**
As discussed in a previous core dev meeting, we are moving the AkkaIO transport to Akka.Remote

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Make sure you rebase to the latest off of dev - need to have the changes from #1446 included in your PR in order for the multi-node testrunner to pass.

**Comment by Aaronontheweb** [comment]
Need to rebase off of dev again - merge conflict

**Comment by rogeralsing** [comment]
Rebased

**Comment by rogeralsing** [comment]
Build server have not picked up the latest rebase

**Comment by Aaronontheweb** [comment]
Ah, it's because of the age of the previous commit - could you try this @rogeralsing ?

http://stackoverflow.com/a/31540373/377476

**Comment by rogeralsing** [comment]
Changed the commit date. hopefully this will trigger build now..

**Pull request merged**
