### PR TITLE
A virtual time TestScheduler

### PR DESCRIPTION
**Pull request by sadprofessor**
Needed for testing actors that use the scheduler. Included unit tests demonstrate usage.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Akka.NET TestKit may now go back in time. Safety Not Guaranteed. Must bring your own weapons.

In all seriousness, is this setup as the default scheduler in the TestKit going forward?

**Comment by sadprofessor** [comment]
I didn't feel 100% comfortable making it the default scheduler, so there's a new TestScheduler.conf you can use for tests that require deterministic scheduling. Of course it could be made the default if you think it should. I tried it briefly but it broke a bunch of remoting tests for non-obvious reasons.

**Comment by Aaronontheweb** [comment]
Good to know. Would you mind sending a page to https://github.com/akkadotnet/getakka.net explaining how to enable it and how it works (i.e. how does time advance?)

**Comment by sadprofessor** [comment]
Yeah np

**Pull request merged**
