### PR TITLE
897 NUnit TestKit

### LINKED ISSUE #897: Nunit TestKit
A lot of people (including my current client) use NUnit. While XUnit can be a better option, adding it to existing projects often faces resistance. It looks like it'll be easy to implement NUnit support in the TestKit.

### PR DESCRIPTION
**Pull request by ashic**
This is an NUnit implementation of the TestKit. 

Resolves #897 .

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
welp, looks like we don't have a good excuse to keep shitting all over XUnit anymore :p 

Thanks for your submission! We'll bundle this as part of the v1.0.1 release next week along with the XUnit2 testkit in #888 

cc @annymsMthd and @HCanber - does this look kosher to you?

**Comment by annymsMthd** [comment]
Looks good to me. Nice to see some NUnit up in here:)

**Comment by ashic** [comment]
Seems like an unrelated test failure. Intermittent test?

**Comment by Aaronontheweb** [comment]
@ashic yes, it's one of the outstanding racy unit tests that we still haven't quite fixed from #853

**Comment by annymsMthd** [comment]
#888 has a fix for that one

**Comment by Aaronontheweb** [comment]
@annymsMthd 
whiskey-approval

**Pull request merged**
