### PR TITLE
Fix proposal for issue #3129

### PR DESCRIPTION
**Pull request by sbacquet**
Issue #3129 : remotely deployed actors were registered in DistributedPubSubMediator's register with key = "/remote/...", hence did not receive messages from mediator sent with Send("/user/...") or SendToAll("/user/...").
Now the key is the same for all actors = the path beginning with /user/.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@sbacquet not entirely sure I understand the outcome of the fix here. Could you please add a unit test to demonstrate?

**Comment by sbacquet** [comment]
@Aaronontheweb the case is pretty simple and fully described in issue #3129.
As this issue involves remote deployment, I'm not sure I'd be able to write a unit test.
Will investigate...

**Comment by sbacquet** [comment]
I've just pushed a unit test to highlight the issue.
Revert the modifications in Topics.cs and the test _DistributedPubSubMediator_must_publish_remote_ will fail.
In order to be able to remotely deploy actors, I've had to refactor a little bit.

**Comment by sbacquet** [comment]
I can't figure out why the tests are racy (as usual, "it works fine on my computer").
I guess the issue is around : 
               var testActor = DistributedPubSubMediatorSpec.Current.TestActor;
but I don't know how to make it safe.
Any idea ?

It was an attempt to make a MultiNodeSpec compatible with remotely-deployed actors.
But obviously it's not the right way to do it...

**Comment by Aaronontheweb** [comment]
closed via #4207

**Pull request closed without merging**
