### PR TITLE
Update RELEASE_NOTES.md for 1.4.50 release

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
There's some other issues that need a mention here: https://github.com/akkadotnet/akka.net/issues?q=is%3Aclosed+milestone%3A1.4.50

**Comment by Arkatufus** [comment]
@Aaronontheweb We did not backport #6378, should we backport that?

**Comment by Arkatufus** [comment]
@Aaronontheweb #6366 was added in 1.4.49 but was not added in the release note

**Comment by Aaronontheweb** [comment]
> @Aaronontheweb We did not backport #6378, should we backport that?

eh, guess not

**Pull request merged**
