### PR TITLE
Check for possible broken documentation by failing on DocFX warning

### PR DESCRIPTION
**Pull request by Arkatufus**
## Changes
Add --warningsAsErrors flag to DocFX argument

close https://github.com/akkadotnet/akka.net/issues/5528

### Warnings Log
1-26-2022: 754 Warning(s)
2-4-2022: 702 Warning(s)
2-7-2022: 590 Warning(s)
2-8-2022: 411 Warning(s)
2-9-2022: 312 Warning(s)
**2-11-2022: 41 Warning(s)**
2-15-2022: 25 Warning(s)

## NOTE
This PR __WILL__ fail until we fix all of the DocFX warnings in our documentation.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Arkatufus still need to add a step to the pr-validation AzDo file to enforce this

**Comment by eaba** [comment]
Will this be helpful https://github.com/Ellerbach/docfx-companion-tools/tree/main/src/DocLinkChecker?

**Comment by Aaronontheweb** [comment]
@eaba DocFx already does this though - usually via build warnings. All we did was turn those into errors.

**Comment by Aaronontheweb** [comment]
@Arkatufus could you add the total number of warnings that need fixing to this PR and periodically update it as we reduce those?

**Comment by Aaronontheweb** [comment]
One thing we're probably doing to generate a lot of these warnings is not using `inheritdoc` properly when derived members refer to their bases.

**Comment by Aaronontheweb** [comment]
Looks like incremental builds was one of the things really raising our error count. Disabling that eliminated a ton of them.

**Pull request merged**
