### PR TITLE
Common.Logging logging support

### PR DESCRIPTION
**Pull request by derwasp**
I know that it is not the most important thing in the world, but I am using Common Logging in my project and I wanted to share this adapter.
I hope I didn't miss anything.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
cc @Horusiath @forki weird, looks like Paket ran into an issue during restore:

```
[16:32:51][Step 1/1] Paket failed with:
[16:32:51][Step 1/1] 	Could not download System.Threading.Tasks 4.0.10 from https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10.
[16:32:51][Step 1/1]     The process cannot access the file 'C:\Windows\system32\config\systemprofile\AppData\Local\NuGet\Cache\System.Threading.Tasks.4.0.10.nupkg' because it is being used by another process.
[16:32:51][Step 1/1] Process exited with code 1
[16:32:51][Step 1/1] Step FAKE Build (Command Line) failed
```

I'll kick off a new run of the build...

**Comment by forki** [comment]
That's a weird error. Are there other processes running?

**Comment by Aaronontheweb** [comment]
Not as far as I know - all of the build agents run on clean VMs (at least initially - they'll hang around if there's multiple builds queued up) and only run one job at a time.

**Comment by forki** [comment]
mhm. I will try to investigate that part of the code. Maybe you can run
"paket restore -v" then we will get the stacktrace

2015-11-11 17:24 GMT+01:00 Aaron Stannard <notifications@github.com>:

**Comment by forki** [comment]
I added a bit more tracing around that thing 20a6d95

**Comment by derwasp** [comment]
@Aaronontheweb is there something wrong with my code or is it only CI issue? It was building locally for me.

**Comment by Aaronontheweb** [comment]
CI is having some problems right now :( - build server issue apparently

**Comment by rogeralsing** [comment]
Is this one safe to pull in or are there any secret Paket related issues in here that I cant spot?
cc @Aaronontheweb

**Comment by derwasp** [comment]
@rogeralsing I already changed everything to work with nuget, since you removed Paket. I did the last rebase 3 days ago because of some conflicts.

**Comment by rogeralsing** [comment]
Thanks!

**Comment by forki** [comment]
You removed paket?

**Comment by derwasp** [comment]
@rogeralsing you are welcome

**Pull request merged**
