### PR TITLE
A persistent view replays events during the recovery despite the fact…

### PR DESCRIPTION
**Pull request by artem-karnaukh**
A persistent view replays events during the recovery despite the fact, that Recovery property is overriden and returns Recovery.None

### CODE REVIEW

**Comment by cconstantin** [comment]
@artem-karnaukh thanks for submitting fix. Would you mind including a test to illustrate the issue?

**Comment by Aaronontheweb** [comment]
@artem-karnaukh looks good to me - please go ahead and squash these commits and we'll merge them in.

**Comment by cconstantin** [comment]
@artem-karnaukh @Aaronontheweb: I put this on hold. Can you please update the test to demonstrate that events are replayed when `Recovery.None`? It does not do that in the current form. Sorry for insisting on this, but it appears to me that the existing code works correctly.

**Comment by Danthar** [comment]
Whats the status on this @cconstantin ? Does this PR addresses a valid problem?

**Comment by cconstantin** [comment]
@Danthar there was no reply after my request for a proper test. I don't believe this is a valid issue.

**Comment by Danthar** [comment]
Stale, and regarding the above comments. Im closing this.

**Pull request closed without merging**
