### PR TITLE
Adding C# hello world example #559

### PR DESCRIPTION
**Pull request by avoxm**
Hello world example project from Akka.NET wiki.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
I think it's a good idea to include a Hello World sample - your thoughts @rogeralsing ?

**Comment by rogeralsing** [comment]
The other examples have aimed to show specific features. Hello world would show none.

But I guess that it could be useful just to get going. 
So +1 from me

**Comment by avoxm** [comment]
@rogeralsing I guess you are right in regards of presenting features. Frankly, my intention was not presenting features, but to have the most basic sample just to make debugging through sources easier for new developers who want to join.

**Comment by Aaronontheweb** [comment]
Having a reference sample for the most basic stuff is useful - gives newbies a place to start looking.

I'll deal with the merge conflict a little later today and pull this in.

**Pull request merged**
