### PR TITLE
Patch for Issues 832 & 833

### PR DESCRIPTION
**Pull request by jcwrequests**
Based @rogeralsing  suggestion I removed the using a string to produce the actor and am instead using the type. This should resolve the issues with 832 & 833. @nvivo @danthar could you please check this version to see if it resolves your issues.  Thanks

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@jcwrequests looks good to me. If @nvivo or @danthar have anything to add they can chime in here. Will pull this in on Monday.

**Comment by nvivo** [comment]
Looks good by reading,  but I couldn't test it yet. Would be nice to have a new "rc" on nuget before releasing the next version,  so we can better check this and the other issues.

One note is that I think there are some comments or text files in a folder somewhere in the tree that explains how to create a resolver that might need an update after this.

**Comment by Aaronontheweb** [comment]
@nvivo we had a preview release of this up on NuGet about a week before the official release http://www.nuget.org/packages/Akka/1.0.0-dev1504032244

Each PR, when successful, also generates NuGet packages you can download as artifacts off of TeamCity.

But you're right - for longer term releases we should probably put weekly pre-releases out there rather than depend on people compiling from source.

**Comment by Aaronontheweb** [comment]
And thanks for doing your review too @nvivo - much appreciated!

**Comment by jcwrequests** [comment]
@nvivo @aaronontheweb you are probably right about the docs I will double check. BTW @nvivo sorry about the earlier confusion about your suggestion. I was in the middle of doing work around the house and was trying to review everything from my phone.

**Pull request merged**
