### PR TITLE
Add a filter for only a single mntr spec to be run under multi-plat

### PR DESCRIPTION
**Pull request by heynickc**
Putting this PR in to set up TeamCity to run MultiNode specs across runners kicked off as both .NET Core and .NET 4.5.2, limiting it to a single spec: `Akka.Remote.Tests.MultiNode.RemoteDeliverySpec`

This spec fails, indicating that we haven't achieved compatibility between target platforms as far as the 2 mntr runners are showing.  Submitting the PR simply to be able to set up the infrastructure in TeamCity so it's ready to run in the future.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Getting NREs here

```
[21:20:08]	[MultiNodeTestsMultiPlatform] Running build failed.
[21:20:08]	[MultiNodeTestsMultiPlatform] Error:
[21:20:08]	[MultiNodeTestsMultiPlatform] System.NullReferenceException: Object reference not set to an instance of an object.
[21:20:08]	[MultiNodeTestsMultiPlatform]    at FSI_0005.Build.sampleMntrSpecAssemblyFilter@225-1.Invoke(String x)
[21:20:08]	[MultiNodeTestsMultiPlatform]    at Microsoft.FSharp.Collections.IEnumerator.next@227[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
[21:20:08]	[MultiNodeTestsMultiPlatform]    at Microsoft.FSharp.Collections.IEnumerator.filter@222.System-Collections-IEnumerator-MoveNext()
[21:20:08]	[MultiNodeTestsMultiPlatform]    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
[21:20:08]	[MultiNodeTestsMultiPlatform]    at FSI_0005.Build.clo@207-18.Invoke(Unit _arg4)
[21:20:08]	[MultiNodeTestsMultiPlatform]    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
[21:20:08]	[MultiNodeTestsMultiPlatform] Starting FinalTarget: KillCreatedProcesses
[21:20:08]	[MultiNodeTestsMultiPlatform] Killing processes started by FAKE:
[21:20:08]	[MultiNodeTestsMultiPlatform] 2092
[21:20:08]	[MultiNodeTestsMultiPlatform] 3580
[21:20:08]	[MultiNodeTestsMultiPlatform] 3732
[21:20:08]	[MultiNodeTestsMultiPlatform] Killing any remaining dotnet and xunit.console.exe processes:
```

**Comment by Arkatufus** [comment]
I think this is more relevant:
```
[21:20:07][MultiNodeTestsMultiPlatform] Using MultiNodeTestRunner: D:\work\dcf07aab4d29c521\src\core\Akka.MultiNodeTestRunner\bin\Release\netcoreapp1.1\Akka.MultiNodeTestRunner.dll
[21:20:08][MultiNodeTestsMultiPlatform] Could not find built assembly for Akka.Cluster.Sharding.Tests.MultiNode.  Make sure project is built in Release config.
```

**Comment by heynickc** [comment]
Yea probably a build script thing, I'll fix it

**Comment by heynickc** [comment]
The null reference exception was due to Akka.Cluster.Sharding.Tests.MultiNode not targeting `netcoreapp1.1` yet, but incremental tests was looking for all MultiNode specs regardless.  Added a filter that excludes any project that hasn't been targeted for .NET Core yet.

**Comment by heynickc** [comment]
closing as we are holding off on this due to issues with serialization across platform targets

**Pull request closed without merging**
