### PR TITLE
WIP: Convert to Paket

### PR DESCRIPTION
**Pull request by forki**
Implements https://github.com/akkadotnet/akka.net/issues/609:

- [x] - run automatic conversion
- [x] - fix local FAKE build
- [x] - run paket simplify
- [x] - fix CI builds
- [x] - fix NuGet package creation

Remarks:

* `packages` folder is now in root
* xunit is used in two versions. Paket doesn't support that yet, but I put the older one in lib foder

### CODE REVIEW

**Comment by forki** [comment]
one test fails with "Process is terminated due to StackOverflowException." is this known?

**Comment by forki** [comment]
ah it's marked as skip, but somehow xunit2 executes it

**Comment by forki** [comment]
by using Paket 2.0 I was able to remove the xunit lib from the lib folder.
It's now part of the "legacy" group (see https://github.com/akkadotnet/akka.net/pull/1243/files#diff-b27553841b4413a24ed1b9aff865105bR38)

**Comment by forki** [comment]
looks like http://petabridge-ci.cloudapp.net/ is hanging

**Comment by rogeralsing** [comment]
` Failed to start build: Failed to clean files from: D:\BuildAgent\work\49b164d63843fb4`

Access rights problem on build server? cc @Aaronontheweb

**Comment by forki** [comment]
No there was a timeout and probably something is still running in the back.
Classical teamcity issue.

**Comment by Aaronontheweb** [comment]
I re-ran the build. This is an issue with your PR.

**Comment by Aaronontheweb** [comment]
That's weird though - didn't see it show up on the build log.

Running another now: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2377&guest=1

**Comment by forki** [comment]
Closed in favor of #1362

**Pull request closed without merging**
