### PR TITLE
add support for non abbreviated timespan strings

### PR DESCRIPTION
**Pull request by mrrd**
This pull request adds support for non abbreviated timespan values in hocon

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Lots of test failures....

**Comment by Danthar** [comment]
@mrrd it looks like you broke the parsing of normal values ?

A quick survey reveales that values like: 0.05 s  are causing problems now.

Check the remote conf for more samples: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/Configuration/Remote.conf
and the remoteSettings object for a few examples on which are expected to be TimeSpans. https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/RemoteSettings.cs

I think if you fix those scenario's it should probably resolve most, if not all, failing unit tests.

**Comment by mrrd** [comment]
@Danthar thanks I can see exactly what I have missed a + in the regex

**Comment by Danthar** [comment]
@mrrd can you please squash your commits

**Pull request merged**
