### PR TITLE
Replaced generic exceptions with more specific ones

### PR DESCRIPTION
**Pull request by sean-gilliam**
Reference #1192

This PR replaces the generic exceptions with more specific ones. This
should help make debugging easier for apps that work with Akka.NET.

### CODE REVIEW

**Comment by rogeralsing** [comment]
Looks great!
The failed tests looks a bit funky though, do we have code that expects the old exception types anywhere?

**Comment by sean-gilliam** [comment]
Thanks :) 

Hmm. At first glance, it looks to be timeout related. Maybe my changes on src/core/Akka.TestKit/TestKitBase.cs from Exception to TimeoutException could be causing this?

I'll dig it to it.

**Comment by sean-gilliam** [comment]
Well I just ran those tests again on my end and I get green check marks. Maybe something going on with the build server?

**Comment by rogeralsing** [comment]
@Aaronontheweb can we do something about the buildserver rebuilds, add a bot that we ourselves can activate or something?
Its been frustrating for a long time now that nobody else can activate this

**Comment by Aaronontheweb** [comment]
@rogeralsing yeah, that's something I want to be able to do with Hubot but we don't have it working yet. cc @skotzko 

In the meantime, I can give you guys accounts for restarting builds. Would that work?

**Pull request merged**
