### PR TITLE
Updating FSharp.Quoteations.Evaluator for Akka.FSharp api

### PR DESCRIPTION
**Pull request by tjaskula**
I'm trying to make the changes updating FSharp.Quotations.Evaluator and FSPickler. I've also included the last version of FSharp.Core

### CODE REVIEW

**Comment by tjaskula** [comment]
@Aaronontheweb I'm disapointed. This has fixed linux build but it seems some UT are failing which seems not be related to the commit. Is there a way to rerun failed checks to be sure ?

**Comment by Danthar** [comment]
rerunning failing tests

**Comment by tjaskula** [comment]
Cool, all is well :)

**Comment by Horusiath** [comment]
If you're okay with .net standard 2.0 dependency, I'm okay with it as well. 

In case of Akkling I've decided to simply remove parts of the API related to `Expr` - it was not as invasive as I initially thought, thanks to Hyperion, we were able to serialize things like delegates, so i.e. cluster routing still worked there.

**Comment by vasily-kirichenko** [comment]
Why? Akkling is much mature and quotations have been recently removed from there. Just use it.

**Comment by Danthar** [comment]
woops wrong button

**Comment by Danthar** [comment]
This can be merged once CI is done

**Comment by ivog** [comment]
@Danthar Great!! Thanks!

**Comment by ivog** [comment]
@Danthar I guess, the linux tests need to be rerun again.

**Pull request merged**
