### PR TITLE
adding Akka.DI.SimpleInjector with tests

### PR DESCRIPTION
**Pull request by nukedbit**
adding Akka.DI.SimpleInjector with tests SimpleInjector dependency resolver.
I have implemented it basing on other DI implementations, i have also included the Shared assembly info.

One point of attention i had to change the two base Bind<T> methods on DiResolverSpec so it could call Register<T> on SimpleInjector wich has a clause T:class

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Make sure you rebase to the latest off of dev - need to have the changes from #1446 included in your PR in order for the multi-node testrunner to pass.

**Comment by nukedbit** [comment]
Merged with the lasted of dev and squashed commits but seem still to fail, i'm missing something?
Thanks
S.

**Comment by tmusico** [comment]
@nukedbit if you change your implementation of the two Bind<T> methods in the ResolverSpec file ... then you do not need to change the base Bind methods to include the  where T:class clause

        protected override void Bind<T>(object diContainer, Func<T> generator)
        {
            var container = diContainer as Container;
            container.Register(typeof(T), () => generator(), Lifestyle.Scoped);
        }

        protected override void Bind<T>(object diContainer)
        {
            var container = diContainer as Container;
            container.Register(typeof (T), typeof(T), Lifestyle.Scoped);
        }

**Comment by Aaronontheweb** [comment]
you'll need to rebase again :\ - sorry about that

**Comment by rogeralsing** [comment]
Can this be closed in favor for #1647?
cc @akkadotnet/contributors

**Comment by nukedbit** [comment]
@rogeralsing hi sorry for the late answer but i was in sick leave, yes you can close it, i don't mind ;)
Thanks for the support you have given me, and also thanks for the great job you are doing on the project, going soon on production on a small project with akkanet

**Pull request closed without merging**
