### PR TITLE
Fix serialization verification for DeadLetters

### PR DESCRIPTION
**Pull request by cconstantin**
DeadLetter with a Message property marked with INoSerializationVerificationNeeded should be excluded from serialization verification

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
You need to rebase - this build is affected by the NuGet 3.4.3 bug

**Comment by cconstantin** [comment]
@Aaronontheweb oops, rebased.

**Comment by Aaronontheweb** [comment]
mind rebasing one more time, for MNTR?

**Comment by Aaronontheweb** [comment]
Merged

**Pull request merged**
