### PR TITLE
Create a new linked CancellationToken for each database operation(#3471)

### PR DESCRIPTION
**Pull request by jarlrasm**
This fixes a memory leak with SqlCommands being referenced indefinitely in the SqlJournal's long living CancellationToken.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@jarlrasm did you see a memory leak crop up during profiling or something?

**Comment by jarlrasm** [comment]
@Aaronontheweb yes. I noticed hundreds of thousands of uncollected sql-related objects when I was profiling our app with some load. Tracked it down to the cancellationToken.

**Comment by maxcherednik** [comment]
@jarlrasm Could you please explain the reason behind? Where is the issue itself? The reason I am asking is that I don't remember CancellationToken behaves this way.

**Comment by jarlrasm** [comment]
@maxcherednik DbCommand registers a callback on the CancellationToken which is never removed, thus preventing garbagecollection.

**Comment by maxcherednik** [comment]
@jarlrasm Yeah, this change is going to fix the issue. But the root cause here is that we misuse cancelationTokenSource

**Comment by jarlrasm** [comment]
@maxcherednik I agree that it is strange. But since I don't know the background for why the design is as it is, I didn't want to change it in a fundamental way.

**Comment by maxcherednik** [comment]
@jarlrasm  btw there are 2 issues here:
1. there is a bug in the DbCommand - they dont dispose the registration: https://github.com/Microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Data/System/Data/Common/DBCommand.cs#L213
2. CancellationTokenSource is misused here. For example, post stop method cancels the CTS and then what? Who will make sure that everything was complete? 
Cancellation should always be called from the places where the initial call was made and should be done within the context of the method.
```
Task DoSomething(int param, CancellationToken ct);
```

Maybe we can the core team if this class is public.

The fix of yours will probably remove the leak, but it will also introduce some allocations, potentially heavy. There could be more subtle issues, which are not visible right now.

**Comment by jarlrasm** [comment]
1. Looks like the upstream bug is fixed in dotnet-core:
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbCommand.cs#L144
2. I agree here, but I think someone who understand the intention behind the design should look into it, rather than me just guessing.

I don't think the allocations introduced by my fix are at all heavy, but I agree with the sentiment that the root problems should be fixed rather than patching on something that is flawed.

**Comment by Aaronontheweb** [comment]
@maxcherednik Max, do you feel like you have a strong enough handle on the Akka.Persistence stuff to take a look at this? I'm neck deep in fixing some issues with a different OSS project today (NBench) but I might be able to take a look at it this weekend. Otherwise, @Horusiath might be able to take a look and see what's up.

**Comment by maxcherednik** [comment]
@Aaronontheweb will try to have a look in a couple of days.

**Comment by Aaronontheweb** [comment]
@maxcherednik thanks bud, I owe you one.

**Comment by maxcherednik** [comment]
For the reference: https://github.com/dotnet/corefx/issues/16439

**Comment by Aaronontheweb** [comment]
Looks good to me. Read up on it some more and couldn't see any harm in it.

**Pull request merged**
