### PR TITLE
SynchronizationContext for #907

### PR DESCRIPTION
**Pull request by kekekeks**
This should restore current actor cell before calling continuation

### CODE REVIEW

**Comment by kekekeks** [comment]
#907

**Comment by rogeralsing** [comment]
Do we have to account for the xUnit synchronizationcontext or is that applied ontop of this one once the async test starts?

**Comment by kekekeks** [comment]
Xunit just [wraps](https://github.com/xunit/xunit/blob/43fa87d47a593aab97ff9f84dc5d2c2ac54b1a33/src/xunit.execution/Sdk/AsyncTestSyncContext.cs) anything it finds [before calling the method](https://github.com/xunit/xunit/blob/3f8b35c989af05e7b80beae37938b00036c670ce/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L187), but after [calling constructor](https://github.com/xunit/xunit/blob/3f8b35c989af05e7b80beae37938b00036c670ce/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L157).

**Comment by Aaronontheweb** [comment]
Could we add a test to verify the existence and resolution of the bug in addition to the fix?

**Comment by kekekeks** [comment]
Obsoleted by #913

**Comment by kekekeks** [comment]
CallContext is a slowpoke, so it seems that we are going to use this

**Comment by rogeralsing** [comment]
As #913 is too costly in terms of processing overhead, we still need this fix.
The test seems to fail, are we losing context even with this applied?

**Pull request merged**
