### PR TITLE
Add API for UntypedActorWithStash types

### PR DESCRIPTION
**Pull request by ismaelhamed**
Added utility abstract classes for `UntypedActor`s that support stashing: 

- `UntypedActorWithStash`
- `UntypedActorWithUnboundedStash` 
- `UntypedActorWithUnrestrictedStash`

Depends on #6325 

## Checklist

* [X] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [X] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).
* [X] Changes in public API reviewed, if any.
* [X] I have added website documentation for this feature.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@ismaelhamed #6325 has been merged. I can start work on backporting it probably on Friday unless you want to do it (via `git cherry-pick`)

**Comment by ismaelhamed** [comment]
> @ismaelhamed #6325 has been merged. I can start work on backporting it probably on Friday unless you want to do it (via `git cherry-pick`)

I think I can find the time to do it myself. I will be back porting #6323, #6325 and #6327 if you're fine with it.

**Comment by Aaronontheweb** [comment]
> > @ismaelhamed #6325 has been merged. I can start work on backporting it probably on Friday unless you want to do it (via `git cherry-pick`)
> 
> I think I can find the time to do it myself. I will be backporting #6323, #6325 and #6327 if you're fine with it.

Yes, that would delight me

**Review by Aaronontheweb — COMMENTED** [review]
Is the general goal behind this API change to move away from the actor creation pipeline, so the stash is provided automatically as part of the base class infrastructure itself rather than injected in from the outside?

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by ismaelhamed** [comment]
> Is the general goal behind this API change to move away from the actor creation pipeline, so the stash is provided automatically as part of the base class infrastructure itself rather than injected in from the outside?

@Aaronontheweb  If you think about it, using stashing is currently a little weird since users actually must implement an interface (including declaring the `Stash` property that, BTW, they are not instantiating themselves). That's because in scala traits can have behavior, which can't be done with interfaces in JAVA and CSharp (well, we have default interfaces now but you get the point).

So it is natural that these utility classes exist in the JAVA API, allowing the user to just derive from a class (like they would with normal actors) and just get everything needed for stashing already set up. They can still implement the interfaces themselves if they choose to, but this is a bit of an improvement on the usability side.

**Comment by Aaronontheweb** [comment]
> They can still implement the interfaces themselves if they choose to, but this is a bit of an improvement on the usability side.

Time will tell I guess, but I see your point.

**Pull request merged**
