### PR TITLE
TestScheduler should use ConcurrentQueue for work items

### LINKED ISSUE #2352: TestScheduler isn't thread safe
You can get modified collections when it's enumerating over queued work items. Need to use a ConcurrentQueue.

### PR DESCRIPTION
**Pull request by thomastomanek**
Fixes #2352

### CODE REVIEW

**Comment by Danthar** [comment]
LGTM

**Comment by Danthar** [comment]
It seems this change is causing issues with this test:  FlowSelectAsyncUnorderedSpec.A_Flow_with_SelectAsyncUnordered_must_not_run_more_futures_than_configured

**Comment by thomastomanek** [comment]
It's running fine locally here. Also I can't even see that that spec is using the TestScheduler.

**Comment by Aaronontheweb** [comment]
merged - sorry about the delay. Build system needed to be upgraded to Win2016 RTM

**Pull request merged**
