### PR TITLE
ClusterSingletonManager remove ClusterEvent.MemberExited events

### PR DESCRIPTION
**Pull request by zbynek001**
this removes some unhandled events warnings

### CODE REVIEW

**Comment by Danthar** [comment]
Im not sure if the bug is that we are subscribing to the `MemberExited` event or if the bug is, that we are not handling this event. /cc @Aaronontheweb  ?

**Comment by zbynek001** [comment]
at least scala subscribes only to `MemberRemoved`, and not to `MemberExited`. And there is nothing handling `MemberExited` in ClusterSingletonManager

**Comment by alexvaluyskiy** [comment]
@zbynek001 looks good

**Comment by Aaronontheweb** [comment]
@Danthar `MemberRemoved` gets fired when the node is officially gone from the cluster.

**Pull request merged**
