### PR TITLE
Perf optimize `ActorSelection`

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Saw some of the same inefficient / allocate-y patterns from `VectorClock` and elsewhere show up in this class and wanted to clean it up.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Performance baseline

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.928 (2004/?/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
  DefaultJob : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT


```
|                        Method | Iterations |       Mean |     Error |    StdDev |     Median |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |-----------:|----------:|----------:|-----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 102.539 ms | 2.0437 ms | 5.4197 ms | 100.920 ms | 6200.0000 |     - |     - |  25.55 MB |
|          CreateActorSelection |      10000 |   5.569 ms | 0.0825 ms | 0.0772 ms |   5.543 ms | 1203.1250 |     - |     - |   4.81 MB |

**Comment by Aaronontheweb** [comment]
Reduced memory allocation on create:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.928 (2004/?/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
  DefaultJob : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT


```
|                        Method | Iterations |      Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 99.315 ms | 1.9810 ms | 2.9037 ms | 6333.3333 |     - |     - |  25.55 MB |
|          CreateActorSelection |      10000 |  5.668 ms | 0.0629 ms | 0.0557 ms |  953.1250 |     - |     - |   3.81 MB |

**Comment by Aaronontheweb** [comment]
Lazily create an `EmptyActorReference` only when it's needed now, rather than every time when the function is recursed.

Big performance improvement on `Tell` / `Ask` operations - ~99ms -> ~84.ms, 25.55mb allocated -> 20.51mb allocated.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.928 (2004/?/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
  DefaultJob : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT


```
|                        Method | Iterations |      Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 83.980 ms | 1.3279 ms | 2.1443 ms | 5000.0000 |     - |     - |  20.51 MB |
|          CreateActorSelection |      10000 |  5.539 ms | 0.0605 ms | 0.0566 ms |  953.1250 |     - |     - |   3.81 MB |

**Comment by Aaronontheweb** [comment]
Made `Iterator<T>`, a helper class we use in some areas, into a `struct`.

Reduced memory consumption by a small amount:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.928 (2004/?/20H1)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
  DefaultJob : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT


```
|                        Method | Iterations |      Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 82.042 ms | 0.9767 ms | 0.8658 ms | 5000.0000 |     - |     - |   20.2 MB |
|          CreateActorSelection |      10000 |  5.296 ms | 0.0708 ms | 0.0627 ms |  953.1250 |     - |     - |   3.81 MB |

**Comment by Aaronontheweb** [comment]
I'll think that should do it - 20% throughput improvement, 25% memory consumption improvement.

**Review by Arkatufus — APPROVED** [review]
LGTM

**Pull request merged**
