### PR TITLE
[NET471] Added API Approval [#6707]

### PR DESCRIPTION
**Pull request by eaba**
## Checklist

close https://github.com/akkadotnet/akka.net/pull/6707

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Fixed .NET Framework API approvals for https://github.com/akkadotnet/akka.net/pull/6707 in this PR

**Comment by F0b0s** [comment]
I fixed API Approval in my PR @Aaronontheweb

**Comment by F0b0s** [comment]
I'm trying to complete my PR

**Comment by Aaronontheweb** [comment]
Fixed in #6707

**Pull request closed without merging**
