### PR TITLE
Removes code that overrides OFF log level with WARNING.

### PR DESCRIPTION
**Pull request by tstojecki**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
```
NBench.NBenchException: Error occurred during $Akka.Remote.Tests.Performance.ForkJoinDispatcherRemoteMessagingThroughputSpec+OneWay SETUP. ---> System.ArgumentException: Unknown LogLevel: "off". Valid values are: "DEBUG", "INFO", "WARNING", "ERROR"
Parameter name: off
   at Akka.Event.Logging.LogLevelFor(String logLevel) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Event\Logging.cs:line 159
   at Akka.Remote.Remoting..ctor(ExtendedActorSystem system, RemoteActorRefProvider provider) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote\Remoting.cs:line 116
   at Akka.Remote.RemoteActorRefProvider.get_RemoteInternals() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote\RemoteActorRefProvider.cs:line 50
   at Akka.Remote.RemoteActorRefProvider.Init(ActorSystemImpl system) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote\RemoteActorRefProvider.cs:line 111
   at Akka.Actor.Internal.ActorSystemImpl.Start() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\Internal\ActorSystemImpl.cs:line 102
   at Akka.Remote.Tests.Performance.Transports.RemoteMessagingThroughputSpecBase.Setup(BenchmarkContext context) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.Tests.Performance\Transports\RemoteMessagingThroughputSpecBase.cs:line 74
   at NBench.Sdk.ReflectionBenchmarkInvoker.InvokePerfSetup(BenchmarkContext context)
   at NBench.Sdk.Benchmark.PreRun()
   --- End of inner exception stack trace ---
```

Looks like this change caused some configuration exceptions - might need to make some modifications to support an "off" setting? cc @rogeralsing ?

**Comment by tstojecki** [comment]
I am working on it, will submit another PR. 
Sorry, I don't have CI set up locally, newbie here...

**Comment by Aaronontheweb** [comment]
@tstojecki could you squash these two commits? Steps are detailed in `contributing.md` in this repo

**Comment by tstojecki** [comment]
Done.

**Comment by Aaronontheweb** [comment]
ty sir

**Pull request merged**
