### PR TITLE
Akka IO port

### PR DESCRIPTION
**Pull request by willieferguson**
All commits in the akka-io branch squashed.

There are still some XML comments missing, I will create PR for this on dev branch.

### CODE REVIEW

**Comment by rogeralsing** [comment]
Why hasnt the test runner picked this up?

**Comment by Aaronontheweb** [comment]
@rogeralsing @willieferguson might be the timestamp on the commits - sometimes when you rebase a PR the timestamp on the earliest commit gets set. There's a git command you can use to rewrite the timestamp to a newer time. http://stackoverflow.com/questions/454734/how-can-one-change-the-timestamp-of-an-old-commit-in-git

**Comment by willieferguson** [comment]
When you rebase with squash it takes the timestamp of the 'pick' commit. Fixed with "git commit --amend --reset-author"

The build now has issue with NuGet restore, which I suspect is unrelated to the PR.

**Comment by Aaronontheweb** [comment]
@willieferguson always check the **Build Log** tab:

[07:54:45][Step 1/1] Error parsing the nested project section in solution file. A project with the GUID "{BAC85686-AFC4-413E-98DC-5ED8F468BC63}" is listed as being nested under project "{264C22A4-CAFC-41F6-B82C-4DDC5C196767}", but does not exist in the solution.
[07:54:45][Step 1/1] Task failed with Package restore of ./src/Akka.sln failed
[07:54:45][Step 1/1] Retry.
[07:54:45][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe "restore" "D:\BuildAgent\work\49b164d63843fb4\src\Akka.sln" "-OutputDirectory" "D:\BuildAgent\work\49b164d63843fb4\src\packages"
[07:54:45][Step 1/1] All packages listed in packages.config are already installed.
[07:54:45][Step 1/1] Error parsing the nested project section in solution file. A project with the GUID "{BAC85686-AFC4-413E-98DC-5ED8F468BC63}" is listed as being nested under project "{264C22A4-CAFC-41F6-B82C-4DDC5C196767}", but does not exist in the solution.
[07:54:45][Step 1/1] Task failed with Package restore of ./src/Akka.sln failed
[07:54:45][Step 1/1] Retry.
[07:54:45][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe "restore" "D:\BuildAgent\work\49b164d63843fb4\src\Akka.sln" "-OutputDirectory" "D:\BuildAgent\work\49b164d63843fb4\src\packages"
[07:54:45][Step 1/1] All packages listed in packages.config are already installed.
[07:54:46][Step 1/1] Error parsing the nested project section in solution file. A project with the GUID "{BAC85686-AFC4-413E-98DC-5ED8F468BC63}" is listed as being nested under project "{264C22A4-CAFC-41F6-B82C-4DDC5C196767}", but does not exist in the solution.
[07:54:46][Step 1/1] Task failed with Package restore of ./src/Akka.sln failed
[07:54:46][Step 1/1] Retry.
[07:54:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe "restore" "D:\BuildAgent\work\49b164d63843fb4\src\Akka.sln" "-OutputDirectory" "D:\BuildAgent\work\49b164d63843fb4\src\packages"
[07:54:46][Step 1/1] All packages listed in packages.config are already installed.
[07:54:46][Step 1/1] Error parsing the nested project section in solution file. A project with the GUID "{BAC85686-AFC4-413E-98DC-5ED8F468BC63}" is listed as being nested under project "{264C22A4-CAFC-41F6-B82C-4DDC5C196767}", but does not exist in the solution.
[07:54:46][Step 1/1] Task failed with Package restore of ./src/Akka.sln failed
[07:54:46][Step 1/1] Retry.
[07:54:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe "restore" "D:\BuildAgent\work\49b164d63843fb4\src\Akka.sln" "-OutputDirectory" "D:\BuildAgent\work\49b164d63843fb4\src\packages"
[07:54:46][Step 1/1] All packages listed in packages.config are already installed.
[07:54:46][Step 1/1] Error parsing the nested project section in solution file. A project with the GUID "{BAC85686-AFC4-413E-98DC-5ED8F468BC63}" is listed as being nested under project "{264C22A4-CAFC-41F6-B82C-4DDC5C196767}", but does not exist in the solution.
[07:54:46][Step 1/1] Running build failed.
[07:54:46][Step 1/1] Error:
[07:54:46][Step 1/1] System.Exception: Package restore of ./src/Akka.sln failed
[07:54:46][Step 1/1] ##teamcity[buildStatus status='FAILURE' text='System.Exception: Package restore of ./src/Akka.sln failed   at Fake.RestorePackageHelper.RestoreMSSolutionPackages@189-1.Invoke(String message) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 189   at Fake.RestorePackageHelper.runNuGet(String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 90   at Fake.RestorePackageHelper.runNuGetTrial@94.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 94   at Fake.TaskRunnerHelper.runWithRetries|[a|](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32   at Fake.TaskRunnerHelper.runWithRetries|[a|](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32   at Fake.TaskRunnerHelper.runWithRetries|[a|](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32   at Fake.TaskRunnerHelper.runWithRetries|[a|](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32   at Fake.RestorePackageHelper.runNuGetTrial(Int32 retries, String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 95   at Fake.RestorePackageHelper.RestoreMSSolutionPackages(FSharpFunc`2 setParams, String solutionFile) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 189   at FSI_0001.Build.clo@63-2.Invoke(Unit _arg1) in D:\BuildAgent\work\49b164d63843fb4\build.fsx:line 65   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411']
[07:54:46][Step 1/1]    at Fake.RestorePackageHelper.RestoreMSSolutionPackages@189-1.Invoke(String message) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 189
[07:54:46][Step 1/1]    at Fake.RestorePackageHelper.runNuGet(String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 90
[07:54:46][Step 1/1]    at Fake.RestorePackageHelper.runNuGetTrial@94.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 94
[07:54:46][Step 1/1]    at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
[07:54:46][Step 1/1]    at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
[07:54:46][Step 1/1]    at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
[07:54:46][Step 1/1]    at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
[07:54:46][Step 1/1]    at Fake.RestorePackageHelper.runNuGetTrial(Int32 retries, String toolPath, TimeSpan timeOut, String args

Looks like it's that issue with Visual Studio's .SLN file again. I'm sorry this has been such a pain in the ass Willie >_<

**Comment by willieferguson** [comment]
@Aaronontheweb - my apologies. 

Git squash does not behave like I expected. The solution file was fixed in 2a226e3ac77afafe15126c7579a1ef107c905c9b. Will look into it and create new PR if necessary.

**Pull request merged**
