### PR TITLE
upgraded to JSON.NET 12.0.2

### PR DESCRIPTION
**Pull request by Aaronontheweb**

### CODE REVIEW

**Comment by Danthar** [comment]
Resolved merge conflict. @Aaronontheweb this needs to be merged right ? Not sure if this PR has been open for this long because you lost sight of it, or because it was intentional.

**Comment by Aaronontheweb** [comment]
@Danthar I left it out mostly because I didn't want to bite all of that off as part of `beta1` - but yes, we should upgrade it now.

**Comment by Danthar** [comment]
So yeah this PR probably is whats causing these errors:

https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=20730&view=ms.vss-test-web.build-test-results-tab&runId=1058248&resultId=100620&paneView=debug

**Comment by Aaronontheweb** [comment]
I'll look at that today

**Pull request merged**
