### PR TITLE
Hardcode RepositoryUrl

### PR DESCRIPTION
**Pull request by eaba**
Hard coded RepositoryUrl(https://github.com/akkadotnet/akka.net) to prevent Build from adding the repositoryurl of forked repository

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Got the tests to pass locally on my machine with these settings - let's see what the build server says.

**Comment by Aaronontheweb** [comment]
looks like the issue is that the build server never generates the `﻿[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/akkadotnet/akka.net")]` metadata in the assembly files - that's probably because this issue was introduced, IIRC, by the .NET 5 SDK

Resolve https://github.com/akkadotnet/akka.net/pull/4671 first and then we'll re-check this. Wish we could get a better message out of the ApiApprover to validate this.

**Comment by eaba** [comment]
> 
> 
> looks like the issue is that the build server never generates the `﻿[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/akkadotnet/akka.net")]` metadata in the assembly files - that's probably because this issue was introduced, IIRC, by the .NET 5 SDK
> 
> Resolve #4671 first and then we'll re-check this. Wish we could get a better message out of the ApiApprover to validate this.

It was a pain.....

**Comment by eaba** [comment]
Superceded by https://github.com/akkadotnet/akka.net/pull/4683

**Pull request closed without merging**
