### PR TITLE
Streams update to 2.4.11

### PR DESCRIPTION
**Pull request by Silv3rcircl3**
<details>
  <summary>

2.4.3 done</summary>

- [x] https://github.com/akka/akka/pull/19812
- [x] https://github.com/akka/akka/pull/19835
- [x] https://github.com/akka/akka/pull/19880
- [x] https://github.com/akka/akka/pull/19875
- [x] https://github.com/akka/akka/pull/19886
- [x] https://github.com/akka/akka/pull/19864
- [x] https://github.com/akka/akka/pull/19982
- [x] https://github.com/akka/akka/pull/19845
- [x] https://github.com/akka/akka/pull/20026
- [x] https://github.com/akka/akka/pull/19701
- [x] https://github.com/akka/akka/pull/20035
- [x] https://github.com/akka/akka/pull/20041
- [x] https://github.com/akka/akka/pull/20016
- [x] https://github.com/akka/akka/pull/19889
- [x] https://github.com/akka/akka/pull/20072
- [x] https://github.com/akka/akka/pull/20075
- [x] https://github.com/akka/akka/pull/19908
- [x] https://github.com/akka/akka/pull/20076
- [x] https://github.com/akka/akka/pull/19990
- [x] https://github.com/akka/akka/pull/20070 
- [x] https://github.com/akka/akka/pull/20155
- [x] https://github.com/akka/akka/pull/19895
- [x] https://github.com/akka/akka/pull/19878
- [x] https://github.com/akka/akka/pull/20189
- [x] https://github.com/akka/akka/pull/19860
- [x] https://github.com/akka/akka/pull/20195
- [x] https://github.com/akka/akka/pull/19910
- [x] https://github.com/akka/akka/pull/20240
- [x] https://github.com/akka/akka/pull/19881
- [x] https://github.com/akka/akka/pull/20040
- [x] https://github.com/akka/akka/pull/20067
- [x] https://github.com/akka/akka/pull/20043

</details>

<details>
  <summary>

2.4.4 done</summary>

- [x] https://github.com/akka/akka/pull/20202
- [x] https://github.com/akka/akka/pull/20225
- [x] https://github.com/akka/akka/pull/20235
- [x] https://github.com/akka/akka/pull/20243
- [x] https://github.com/akka/akka/pull/20252
- [x] https://github.com/akka/akka/pull/20281
- [x] https://github.com/akka/akka/pull/20285
- [x] https://github.com/akka/akka/pull/20267
- [x] https://github.com/akka/akka/pull/20191
  </details>

<details>
  <summary>

2.4.5 done</summary>

- [x] https://github.com/akka/akka/pull/20269
- [x] https://github.com/akka/akka/pull/20297
- [x] https://github.com/akka/akka/pull/20325
- [x] https://github.com/akka/akka/pull/20334
- [x] https://github.com/akka/akka/pull/20351
- [x] https://github.com/akka/akka/pull/20335
- [x] https://github.com/akka/akka/pull/20356
- [x] https://github.com/akka/akka/pull/20137
- [x] https://github.com/akka/akka/pull/19795
- [x] https://github.com/akka/akka/pull/20293
- [x] https://github.com/akka/akka/pull/20373
- [x] https://github.com/akka/akka/pull/20125
- [x] https://github.com/akka/akka/pull/20412
- [x] https://github.com/akka/akka/pull/20375
- [x] https://github.com/akka/akka/pull/20141
- [x] https://github.com/akka/akka/pull/20295
- [x] https://github.com/akka/akka/pull/20454
- [x] https://github.com/akka/akka/pull/20451
- [x] https://github.com/akka/akka/pull/20370
- [x] https://github.com/akka/akka/pull/20459
- [x] https://github.com/akka/akka/pull/20468
- [x] https://github.com/akka/akka/pull/20430
- [x] https://github.com/akka/akka/pull/20330
- [x] https://github.com/akka/akka/pull/20401 
- [x] https://github.com/akka/akka/pull/20348
- [x] https://github.com/akka/akka/pull/20242
- [x] https://github.com/akka/akka/pull/20307
- [x] https://github.com/akka/akka/pull/20376
- [x] https://github.com/akka/akka/pull/20383
  </details>

<details>
  <summary>

2.4.6 & 2.4.7 done</summary>

- [x] https://github.com/akka/akka/pull/20555
- [x] https://github.com/akka/akka/pull/20344
- [x] https://github.com/akka/akka/pull/20367
- [x] https://github.com/akka/akka/pull/20704
- [x] https://github.com/akka/akka/pull/20605
- [x] https://github.com/akka/akka/pull/20620
- [x] https://github.com/akka/akka/pull/20611
- [x] https://github.com/akka/akka/pull/20660
- [x] https://github.com/akka/akka/pull/20680
- [x] https://github.com/akka/akka/pull/20621
- [x] https://github.com/akka/akka/pull/20670
- [x] https://github.com/akka/akka/pull/20476
- [x] https://github.com/akka/akka/pull/20692
- [x] https://github.com/akka/akka/pull/20671
- [x] https://github.com/akka/akka/pull/20629
- [x] https://github.com/akka/akka/pull/20494
  </details>

<details>
  <summary>

2.4.8 done</summary>

- [x] https://github.com/akka/akka/pull/20733
- [x] https://github.com/akka/akka/pull/20762
- [x] https://github.com/akka/akka/pull/20769
- [x] https://github.com/akka/akka/pull/20837
- [x] https://github.com/akka/akka/pull/20877
- [x] https://github.com/akka/akka/pull/20757
- [x] https://github.com/akka/akka/pull/20579
- [x] https://github.com/akka/akka/pull/20742
- [x] https://github.com/akka/akka/pull/20914
- [x] https://github.com/akka/akka/pull/20922
- [x] https://github.com/akka/akka/pull/20919
- [x] https://github.com/akka/akka/pull/20445
- [x] https://github.com/akka/akka/pull/20788
- [x] https://github.com/akka/akka/pull/20693
  </details>

<details>
  <summary>

2.4.9 done</summary>

- [x] https://github.com/akka/akka/pull/20928
- [x] https://github.com/akka/akka/pull/20948
- [x] https://github.com/akka/akka/pull/21003
- [x] https://github.com/akka/akka/pull/21038
- [x] https://github.com/akka/akka/pull/21066
- [x] https://github.com/akka/akka/pull/21002
- [x] https://github.com/akka/akka/pull/20778
- [x] https://github.com/akka/akka/pull/21125
- [x] https://github.com/akka/akka/pull/21069
- [x] https://github.com/akka/akka/pull/21140
- [x] https://github.com/akka/akka/pull/21158
- [x] https://github.com/akka/akka/pull/21169
- [x] https://github.com/akka/akka/pull/21157
- [x] https://github.com/akka/akka/pull/21178
- [x] https://github.com/akka/akka/pull/20386
- [x] https://github.com/akka/akka/pull/21148
- [x] https://github.com/akka/akka/pull/21093
- [x] https://github.com/akka/akka/pull/21095
- [x] https://github.com/akka/akka/pull/21054
- [x] https://github.com/akka/akka/pull/21021
- [x] https://github.com/akka/akka/pull/20838
  </details>

<details>
  <summary>

2.4.10 done</summary>

- [x] https://github.com/akka/akka/pull/21322
- [x] https://github.com/akka/akka/pull/21025
- [x] https://github.com/akka/akka/pull/21312
- [x] https://github.com/akka/akka/pull/21317
- [x] https://github.com/akka/akka/pull/21309
- [x] https://github.com/akka/akka/pull/20888
- [x] https://github.com/akka/akka/pull/21083
- [x] https://github.com/akka/akka/pull/21183
- [x] https://github.com/akka/akka/pull/21258
- [x] https://github.com/akka/akka/pull/21208
- [x] https://github.com/akka/akka/pull/21246
- [x] https://github.com/akka/akka/pull/21252
- [x] https://github.com/akka/akka/pull/21139
- [x] https://github.com/akka/akka/pull/21260
- [x] https://github.com/akka/akka/pull/21329
  </details>

<details>
  <summary>

2.4.11 done</summary>

- [x] https://github.com/akka/akka/pull/21436
- [x] https://github.com/akka/akka/issues/21548
- [x] https://github.com/akka/akka/pull/21451
- [x] https://github.com/akka/akka/pull/21447
- [x] https://github.com/akka/akka/pull/21443
  </details>

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 could you incorporate the translation Thread.Interrupt to CancellationToken from netcore branch?
https://github.com/alexvaluyskiy/akka.net/commit/3c6861aea893dd57902f534378ad0326857ac896

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy sure, I will do it once I ported all PR's

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 it is impossible to implement all that PRs in one PR. You could deliver all these changes via separated pull requests, like
- Streams update from 2.4.2 to 2.4.3
- Streams update from 2.4.3 to 2.4.4 
...

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy jup, I got the same feeling. I keep this PR open for tracking the progress and for 2.4.9

**Comment by alexvaluyskiy** [comment]
<details>
  <summary>2.4.10</summary>
- [ ] https://github.com/akka/akka/pull/21322
- [ ] https://github.com/akka/akka/pull/21025
- [ ] https://github.com/akka/akka/pull/21312
- [ ] https://github.com/akka/akka/pull/21317
- [ ] https://github.com/akka/akka/pull/21309
- [ ] https://github.com/akka/akka/pull/20888
- [ ] https://github.com/akka/akka/pull/21183
- [ ] https://github.com/akka/akka/pull/21258
- [ ] https://github.com/akka/akka/pull/21208
- [ ] https://github.com/akka/akka/pull/21208
- [ ] https://github.com/akka/akka/pull/21246
- [ ] https://github.com/akka/akka/pull/21252
- [ ] https://github.com/akka/akka/pull/21139
- [ ] https://github.com/akka/akka/pull/21260
- [ ] https://github.com/akka/akka/pull/21329
</details>

**Comment by alexvaluyskiy** [comment]
<details>
  <summary>2.4.11</summary>
- [ ] https://github.com/akka/akka/pull/21436
- [ ] https://github.com/akka/akka/issues/21548
- [ ] https://github.com/akka/akka/pull/21451
- [ ] https://github.com/akka/akka/pull/21447
- [ ] https://github.com/akka/akka/pull/21443
</details>

**Comment by Silv3rcircl3** [comment]
Finally... 
@akkadotnet/core ready for review

**Pull request merged**
