### PR TITLE
Removed redundant type parameters from PersistentFSMBase.State

### PR DESCRIPTION
**Pull request by kantora**
As I've described in https://github.com/akkadotnet/akka.net/issues/1952. With backward compatibility support.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@kantora could rebase this PR on dev please? Hung the build server for 8 hours today. MNTR fixes from last week should take care of that.

**Comment by Aaronontheweb** [comment]
edit: looks like that was TeamCity's fault - something errored out inside the agent's connection to server.

**Comment by kantora** [comment]
@Aaronontheweb So, do I need to do something?

**Comment by Aaronontheweb** [comment]
Yeah, this needs to be rebased on dev - the MNTR won't pass until you get the latest fixes in.

**Comment by kantora** [comment]
Done

**Pull request merged**
