### PR TITLE
Removing FluentConfig,

### PR DESCRIPTION
**Pull request by rogeralsing**
This PR removes the fluent config support as this never got any traction.
The chat example have been modified to use standard inline hocon configuration.

I do not think we should keep any backward compatability on this one, I can publish the removed bits as a contrib in my own repository incase anyone still needs this.

### CODE REVIEW

**Comment by rogeralsing** [comment]
Closes #739 #165

**Comment by rogeralsing** [comment]
I have cloned the fluent config support to a separate repository incase anyone wants to keep using or forking it.
https://github.com/rogeralsing/Akka.FluentConfig

**Comment by stefansedich** [comment]
Feel like getting this up to date with a merge @rogeralsing ? so it can be merged and closed?

**Comment by rogeralsing** [comment]
Ill update it

**Comment by chrisalexander** [comment]
I think this is still referenced in the documentation? http://getakka.net/docs/deployment-scenarios/Console

**Pull request merged**
