### PR TITLE
[WIP] Cluster spec

### PR DESCRIPTION
**Pull request by eaba**
Fixes async testkit cluster

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Merging this in so we can terminate the feature branch @Arkatufus - you good with that?

**Comment by Arkatufus** [comment]
I'll try to cherry-pick this to dev

**Comment by Arkatufus** [comment]
@eaba Is this ready for review? 
@Aaronontheweb would probably best to wait until it is not a WIP anymore

**Comment by Arkatufus** [comment]
Superceeded by #5984

**Pull request closed without merging**
