### PR TITLE
add ClientDowningNodeThatIsUnreachableSpec #1992

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by maxim-s** [comment]
Could you add copyrights

**Comment by alexpantyukhin** [comment]
@maxim-s  done.

**Comment by Silv3rcircl3** [comment]
@alexpantyukhin ah sorry we have overseen that on the other PR's too, could you please add the copyright there as well ?

**Comment by maxim-s** [comment]
@Silv3rcircl3 previous PR has been merged alredy, I think @alexpantyukhin can create separate PR with missed copyrights and we can create issue for it

**Comment by Silv3rcircl3** [comment]
@maxim-s I know ;-) fine for me, or he changes the others files in this PR too, as you like @alexpantyukhin

**Comment by maxim-s** [comment]
Thank you @alexpantyukhin good job!

**Comment by alexpantyukhin** [comment]
@maxim-s  you are welcome!

**Pull request merged**
