### PR TITLE
Fix actor dependency injector link

### PR DESCRIPTION
**Pull request by jdsartori**
Original link target was ambiguous.

I did some research and figured the author meant this: AkkaNetContrib/Akka.DI.SimpleInjector

### CODE REVIEW

**Comment by sean-gilliam** [comment]
It seems you have changes from your open PR #3705 included in this PR. See commit 51c84c91c3d6bd80c517ad7db6c267f5d3b4fb4a.
Looking at that previous PR it looks like a branching issue.

**Comment by jdsartori** [comment]
Hi, Sean:

Thank you! I'm still working on setting up my dev environment and I'll try
to get that sorted out ASAP.

Until then, I'll see if I have better luck working via the "Improve this
document" link, since I'm only doing documentation stuff at the moment.

I appreciate your help. I'm a big fan of akka.NET and I look forward to
eventually contributing code.

-JDSartori

**Comment by sean-gilliam** [comment]
@jdsartori Thank you for sending in this PR. Your help in cleaning up the docs is greatly appreciated. 

This change, however, is incorrect. It looks like someone forgot to port over the documentation from the old site regarding Actor Producer Extensions.
If you'd like to port over this documentation, then it is located here. https://github.com/akkadotnet/getakka.net/blob/master/src/docs/DI%20Core.md

**Comment by jdsartori** [comment]
Sorry about that.

**Pull request closed without merging**
