### PR TITLE
Updated DI.Core Readme to match correction in Patch for issue 832 & 833

### PR DESCRIPTION
**Pull request by jcwrequests**
@Aaronontheweb @rogeralsing  I updated the DI readme to reflect the changes to the Patch for issues 832 & 833. A special thanks to @nvivo. You have been really awesome with your feedback and it's really appreciated Muito obrigado.

### CODE REVIEW

**Comment by nvivo** [comment]
This is officially getting weird. =) I know I made a big deal out of nothing. I'm fine, don't worry.

**Comment by jcwrequests** [comment]
@nvivo Point taken. Movin on. :>

**Comment by Aaronontheweb** [comment]
Man this is weird - second time in two days I've seen XUnit crash on the build server. Hasn't happened up until this weekend :p

**Comment by rogeralsing** [comment]
Umm why is my async await stuff part of this PR?
this PR should only contain the updated Readme

**Comment by Aaronontheweb** [comment]
@jcwrequests could you redo this PR on top of `/dev/` latest?

**Comment by jcwrequests** [comment]
@Aaronontheweb I will redo it and have it sent first thing in the morning. Notice something that needed to be adjusted anyway. Thanks.

**Comment by Aaronontheweb** [comment]
thanks @jcwrequests! I appreciate it :)

**Pull request closed without merging**
