### PR TITLE
Serialization reload on settings change

### PR DESCRIPTION
**Pull request by zbynek001**
Serializers configurations from extension default config are not correctly loaded.
At the time extension tries to inject it's default config with InjectTopLevelFallback, serializer configuration was already loaded and it's not reloaded afterwards. Currently only workaround I know about is providing all fallback configurations when creating ActorSystem itself. This pr tries to improve this.

### CODE REVIEW

**Comment by zbynek001** [comment]
Not sure if there is a better way how to handle this scenario.
And maybe it soon won't be needed with the change to persistence serialization

**Comment by Aaronontheweb** [comment]
@zbynek001 which serializers do you have this problem for? User-defined ones?

**Comment by zbynek001** [comment]
I've run into this with singleton & sharding. During startup, they are trying to inject default configs via `InjectTopLevelFallback` which works for most stuff, but not for "akka.actor.serializers" configuration. Those never get updated because they were already loaded

**Comment by Danthar** [comment]
Looks good to me. We do the same thing for the Dispatchers subsystem as well. The change in itself is good.

**Comment by zbynek001** [comment]
Should be fixed by #2952

**Comment by zbynek001** [comment]
reason was that two nodes (those with sharding) were using ClusterShardingMessageSerializer, and the Control node was using hyperion so it was not able to deserialize some messages

**Pull request merged**
