### PR TITLE
Issue #1226 implemented

### PR DESCRIPTION
**Pull request by Exef**
Both Put() and CleanUp() methods in class SimpleDnsCache.Cache are now immutable.

It's my first pull request, so if you find any issues let me know and I'll fix them. Any ideas what unit test should I add?

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Exef need to rebase your branch on `dev` so we can merge it though! `CONTRIBUTING.MD` contains a guide that'll explain how to do this.

I haven't reviewed the code yet though - but I'll take a look.

**Comment by Exef** [comment]
@Aaronontheweb Sure, my bad I'll fix it today. I've read everything that was linked from README.MD, but there was no link to CONTRIBUTING.MD. I'll open docs issue to fix this.

**Comment by rogeralsing** [comment]
There is still some mutability going on in the Cleanup method:

```csharp
             public Cache Cleanup()
             {
                 var now = _clock();
                 while (_queue.Any() && !_queue.First().IsValid(now))
                 {
                     var minEntry = _queue.First();
                     var name = minEntry.Name;
                     _queue.Remove(minEntry);  //<-------------------------------------------- here
                     if (_cache.ContainsKey(name) && !_cache[name].IsValid(now))
                         _cache.Remove(name); //<-------------------------------------------- here
                 }
                 return new Cache(_queue, _cache, _clock);
             }
```

**Comment by Exef** [comment]
Yeah, I've missed it. Also putting an element to new Cache also put to old cleaned-up cache.

**Comment by Exef** [comment]
Ok, done. What else should I do?

**Comment by rogeralsing** [comment]
:+1: Thanks

**Pull request merged**
