### PR TITLE
[Async TestKit] Convert Akka.Streams.Tests to async - TcpSpec

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
```
Expected a <Akka.Streams.StreamTcpException> to be thrown, but found <Xunit.Sdk.XunitException>: "
"Xunit.Sdk.XunitException with message "Expected task to complete within 3s."
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
     at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
     at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
     at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
     at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
     at FluentAssertions.Specialized.GenericAsyncFunctionAssertions`1.<CompleteWithinAsync>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Akka.TestKit.Extensions.TaskExtensions.<ShouldCompleteWithin>d__3`1.MoveNext() in D:\a\1\s\src\core\Akka.TestKit\Extensions\TaskExtensions.cs:line 110
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at FluentAssertions.Specialized.AsyncFunctionAssertions.<InvokeWithInterceptionAsync>d__15.MoveNext()
```

**Comment by Arkatufus** [comment]
Well, at least that partially proves that the async `CompletesWithin` guard works... still have to hunt down the hung test assembly

**Comment by Arkatufus** [comment]
build.fsx is broken, fixed in #5925

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Pull request merged**
