### PR TITLE
Class for expressing coding assumptions #570

### PR DESCRIPTION
**Pull request by avoxm**
Adding utility class for expressing coding assumptions. This class will
be extended to support more conditions as needed.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@avoxm I think you might need to merge in the latest changes from `dev` before this can automatically merge, given that @Horusiath's latest PR added some new projects to the .SLN file

**Comment by avoxm** [comment]
Hmmm.... running sync shows that everything is up to date.

**Comment by avoxm** [comment]
yes you were right @Aaronontheweb, thanks. Now it looks much better

**Comment by Aaronontheweb** [comment]
@avoxm ty sir!

**Pull request merged**
