### PR TITLE
#1606 - It should be possible to check if a PersistentView is in a recovery mode

### PR DESCRIPTION
**Pull request by aph5nt**
Done. 
Ready for review.
Unit tests are passing.

### CODE REVIEW

**Comment by Horusiath** [comment]
Shouldn't comments in line [90](https://github.com/akkadotnet/akka.net/pull/1618/files#diff-46912761603a8b7b55771b6cdd3f8911R90) and [228](https://github.com/akkadotnet/akka.net/pull/1618/files#diff-46912761603a8b7b55771b6cdd3f8911R228) be switched?

**Comment by Aaronontheweb** [comment]
@aph5nt any thoughts on @Horusiath's comment?

**Comment by Aaronontheweb** [comment]
ping @aph5nt

**Comment by Aaronontheweb** [comment]
@Horusiath what should we do with this?

**Pull request merged**
