### PR TITLE
Throw on generic Ask if response was Status.Failure

### PR DESCRIPTION
**Pull request by Horusiath**
Right now, when we're using a generic variant of `Ask<>` method, we are solving it by simply casting between Task results (from `object` to our expected `TResult` type). 

The problem here is that, by default Akka.NET solves failure cases to be returned to sender using `Status.Failure` message. In this case, if we'll try to cast `Failure` to generic type `TResult`, we'll end with `InvalidCastException`, swallowing the actual error (carried as a payload of `Failure` message) that happened underneath.

What this PR does, is simplifying casting method (I'm using `async` instead of manual cross task casting), and it checks for `Status.Failure` message - if it was returned and the `TResult` itself is not `Failure`, then we are simply rethrowing that error (while still preserving the stack trace). Additionally I've added 2 tests to verify that behavior. For non-generic variant of `Ask` method everything works as previously - since we cannot guarantee, that user didn't expected `Failure` message to be returned.

This should help an error readability a lot.

### CODE REVIEW

**Comment by maxcherednik** [comment]
@Horusiath @Aaronontheweb I was wondering if we are working on the same thing. I was hoping to remove this CastTask at all - since this is another thing which is hiding real exceptions. Async/Await makes our code 'sync' for the readers.

**Comment by Horusiath** [comment]
@maxcherednik sorry, but I might be out of track. Do you have some PR for that already?

**Comment by maxcherednik** [comment]
@Horusiath nearly. Apart from fixing, was about to add some documentation. It's this guy: #3220

**Comment by Horusiath** [comment]
Closing this one. Eventually it will become part of max PR.

**Pull request closed without merging**
