### PR TITLE
[WIP] Multi data center support

### PR DESCRIPTION
**Pull request by Horusiath**
This is port of Multi-DC support from https://doc.akka.io/docs/akka/2.5/cluster-dc.html

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Issue https://github.com/akkadotnet/akka.net/issues/3261

**Comment by Horusiath** [comment]
Can we rerun test for this PR somehow?

**Comment by Aaronontheweb** [comment]
Issue might be the age of the PR - added before Azure DevOps was added. If updating it with the latest doesn't trigger it, might need to close this PR and just create a new one. Not 100% sure.

**Comment by ismaelhamed** [comment]
@Horusiath @Aaronontheweb **Multi-DC Persistence** is a commercial addon, so are we going to have a custom implementation then?

**Comment by Aaronontheweb** [comment]
I wasn't aware of that. 

Putting on my Petabridge hat: at the moment, I'm not sure - we haven't been trying to follow Lightbend's roadmap when it comes to proprietary technology because the way Akka is consumed in .NET looks quite different than it does on the JVM. Our technology is consumed more by enterprises (energy, finance, healthcare, transportation) and whereas Lightbend also has to support large-scale ecommerce, social media, advertising, etc clients who really do need similarly large-scale features like multi-DC persistence. We'd love to have that type of problem too as adoption of Akka.NET continues to expand rapidly ;)

In terms of what Petabridge will support, that comes down entirely to economics - features that are expensive to support and are only needed by a small number of very high-utilization users should absolutely be proprietary, as those users should foot the bill for the engineering and QA time that goes into maintaining those. 

On principle I don't want to co-mingle what Petabridge and the Akka.NET project, but - necessarily, one of the reasons why people adopt Akka.NET in the first place is precisely because _we do support it_ and we are often the ones who foot the maintenance costs for the project. 

Ultimately we have to strike a balance between what's sustainable for both the company + project and the users' best interests. That's a balancing act that we're still working on figuring out - so far Phobos is the only proprietary component but that will probably change in the future. 

As far as implementation goes, we'll need to get the serialization system fully standardized onto the Protobuf format, per https://github.com/akkadotnet/akka.net/issues/3811, so we can introduce features like this in a forward-compatible manner downstream. Obviously this will need to be merged in too before we can start on that.

**Comment by ismaelhamed** [comment]
It makes total sense. I was just wondering, given you guys have put a lot of effort into this PR, what would be the use cases for **Multi-DC** support without **Multi-DC Persistence**? And this is just my ignorance talking now.

**Comment by Horusiath** [comment]
@ismaelhamed @Aaronontheweb  Multi-DC Persistence uses different technique as it allows to have mutliple incarnations of the same logical entity in different data centers. It uses state representation as CRDTs for conflict-avoidance (similar to our DistributedData module).

Mutli-DC persistence is not necessary tho - IMHO the most important part is to have ensure that cluster sharding (ddata-based one) and split-brain resolvers are multi-dc aware. You don't need multi-dc persistence features in many scenarios.

Another thing, that I'm working over in very slow pace is port of [Eventuate](https://github.com/horusiath/eventuate.net) - it's a persistence library (written by original Akka.Persistence author) that introduces features like replicated event journals and gives comparable features, that multi-dc persistence provides - in fact it was inspiration for multi-dc persistence on the first place.

**Pull request closed without merging**
