### PR TITLE
#3679 Add ability to disable IPv6 for DNS resolution and outgoing socket connection

### PR DESCRIPTION
**Pull request by snekbaev**

### CODE REVIEW

**Comment by snekbaev** [comment]
@Aaronontheweb when you have a moment, could you please help me out with the failing tests :)

**Comment by Aaronontheweb** [comment]
@snekbaev will do

**Comment by snekbaev** [comment]
@Aaronontheweb probably needs one more rerun :)

**Comment by snekbaev** [comment]
@Aaronontheweb @Horusiath  I'd assume regular contributors can't trigger the tests re-run without a commit...? :)

**Comment by snekbaev** [comment]
hah, it's all green, finally! Awesome! :)

**Comment by Aaronontheweb** [comment]
nice work @snekbaev

**Pull request merged**
