### PR TITLE
End-to-end Mono compilation [WIP]

### PR DESCRIPTION
**Pull request by Aaronontheweb**

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
You have to change these paths too
https://github.com/akkadotnet/akka.net/blob/dev/build.fsx#L226

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy yeah,  there's a bunch of stuff in the FAKE file that needs to be updated

**Comment by Aaronontheweb** [comment]
In `build.sh`:

```
mono $SCRIPT_PATH/.nuget/nuget.exe install xunit.runners -OutputDirectory $SCRIPT_PATH/packages/FAKE -ExcludeVersion -Version 2.0.0
```

Needs to be updated to `xunit.runner.console`, which is what we have in `build.cmd`

**Comment by alexvaluyskiy** [comment]
```
mono $SCRIPT_PATH/src/.nuget/NuGet.exe install NUnit.Console -OutputDirectory $SCRIPT_PATH/src/packages/FAKE -ExcludeVersion -Version 3.2.1
mono $SCRIPT_PATH/src/.nuget/NuGet.exe install xunit.runner.console -OutputDirectory $SCRIPT_PATH/src/packages/FAKE -ExcludeVersion -Version 2.0.0
```

**Comment by alexvaluyskiy** [comment]
And I think Sqlite nuget package doesn't support Mono. So we should exclude it
And... we should change the paths of test results, because it puts all files in the root folder, instead of "TestResults" folder

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy I added a method inside FAKE (on NBench) for being able to skip platform-specific unit tests and benchmarks: 

https://github.com/petabridge/NBench/blob/dev/build.fsx#L37

and

https://github.com/petabridge/NBench/blob/dev/build.fsx#L114

I'll use that same approach here.

**Comment by Aaronontheweb** [comment]
As for the pathing stuff, in some of those cases we just need to be using the `Path` class and some of the built-in FileHelpers in FAKE - they do a decent job of handling that in a platform-independent way. I'll go through and start testing more of that. First things first though - gotta squash some Helios bugs on Mono.

**Comment by Aaronontheweb** [comment]
Waiting on #2294 before moving onto the next phases of this. Resolves a resource leak issue that blows up the Mono test runner.

**Comment by Danthar** [comment]
Since #2294 has been merged. Any news on this ?

**Comment by Aaronontheweb** [comment]
@Danthar we can close this

**Pull request closed without merging**
