### PR TITLE
ActorTaskScheduler QueueTask for LongRunning #1410

### PR DESCRIPTION
**Pull request by Zetanova**
Its not a bug, its a missaligment to the normal behavior of .net. If something is creating a task with the TaskCreationOptions.LongRunning Flag it assumes that it can hold the thread for a long running process. If this process is a never ending message loop, it will lock one thread and cell/actor in akka.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Why is it saying "no files changed" ?

**Comment by Zetanova** [comment]
yes, was reverts before, included only one fact now, and its now missing

**Comment by Aaronontheweb** [comment]
make sure you follow the process in `Contributing.md` for squashing commits too ;)

**Comment by Aaronontheweb** [comment]
@Zetanova this spec fails consistently: 
 ActorAsyncAwaitSpec.Actors_should_be_able_to_start_longrunning_task

**Comment by Zetanova** [comment]
Danthar  ask for a spec, see https://github.com/akkadotnet/akka.net/issues/1410

**Comment by Aaronontheweb** [comment]
Aha, I get it now - this was to prove the issue.

**Comment by Aaronontheweb** [comment]
you need to separate these PRs into individual branches

**Comment by Zetanova** [comment]
I have no clue how

**Comment by Aaronontheweb** [comment]
http://technosophos.com/2009/12/04/git-cherry-picking-move-small-code-patches-across-branches.html

**Comment by Aaronontheweb** [comment]
In general,never send a PR from your dev branch. Always send one from a clean feature branch - `contributing.md` in this repo outlines a good process for doing this. Don't tightly couple patches for multiple logical contexts together in one PR.

**Pull request closed without merging**
