### PR TITLE
Add remote random spec

### PR DESCRIPTION
**Pull request by KadekM**
#1257

### CODE REVIEW

**Comment by KadekM** [comment]
Build - was it me or are there some unstable/racey tests ?

**Comment by Aaronontheweb** [comment]
Re-running the tests now to verify

**Comment by KadekM** [comment]
I will try to look at it during weekend, I'm pretty sure the tests were passing on my machine. How can I find more info about the failure ?

**Comment by Aaronontheweb** [comment]
Check out the build log - which you can access by clicking the red X next to the failure:

image

**Comment by KadekM** [comment]
@Aaronontheweb  I checked it on build server before via details on the "All checks have failed" :+1:  I actually have problem with what to make out of the error :)

**Comment by Aaronontheweb** [comment]
Looks like node 4 failed an equals assertion on the spec included in this PR

**Comment by KadekM** [comment]
@Aaronontheweb are you sure ? I am looking at the log:
```
08:19:39][Step 1/1] [RUNNER][8:19 AM]: Results for Akka.Remote.Tests.MultiNode.RemoteRandomMultiNode.RemoteRandomSpecs
[08:19:39][Step 1/1] [RUNNER][8:19 AM]: Start time: 9/4/2015 8:17:11 AM
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 1: PASS [00:00:24.2123915 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 2: PASS [00:00:24.2113919 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 3: PASS [00:00:24.2113919 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 4: PASS [00:00:24.1925072 elapsed]
```

it seems to be issue of remote round robin
```
[08:19:39][Step 1/1] [RUNNER][8:19 AM]: Results for Akka.Remote.Tests.MultiNode.RemoteRoundRobinMultiNode.RemoteRoundRobinSpecs
[08:19:39][Step 1/1] [RUNNER][8:19 AM]: Start time: 9/4/2015 8:17:39 AM
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 1: PASS [00:00:24.1325198 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 2: PASS [00:00:24.1325198 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 3: PASS [00:00:24.1269821 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]:  --> Node 4: FAIL [00:00:24.0851784 elapsed]
[08:19:39][Step 1/1] [RUNNER][8:19 AM]: End time: 9/4/2015 8:18:06 AM
```

which would be also mine as per #1272

**Comment by Aaronontheweb** [comment]
@KadekM now that we've fixed that resizer issue, could you try updating this PR with the latest from `dev` and see what happens?

**Comment by KadekM** [comment]
That's not good...it seems RemoteRoundRobin is still failing.

**Comment by KadekM** [comment]
@Aaronontheweb can you please try to re-run this ?

**Comment by KadekM** [comment]
@Aaronontheweb @rogeralsing rebased

**Comment by rogeralsing** [comment]
:+1:

**Pull request merged**
