### PR TITLE
Update to NetCoreSdk 2.0.0

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
- .NET Core SDK from 1.0.4 to 2.0.0
- FAKE from 4.61.2 to 4.63.0
- Nuget from 4.1.0 to 4.3.0
- Google.Protobuf.Tools from 3.2.0 to 3.4.0
- Microsoft.NET.Test.Sdk from 15.0.0 to 15.3.0
- Removed Optimized=false for .NetStandard1.6 https://github.com/akkadotnet/akka.net/issues/3088

### CODE REVIEW

**Comment by Danthar** [comment]
This is not an official bump to netstandard 2.0 right ?

**Comment by joshgarnett** [comment]
Be careful with the Google.Protobuf upgrades, they made some significant changes from 3.0 -> 3.3 around code generation of enums, which made for a pretty painful upgrade.  Hopefully they 3.2 -> 3.4 is less of a headache for c#.

**Comment by joshgarnett** [comment]
From 3.0 -> 3.2 (?) the C# code generation changed enums from upper snake case to upper camel case.  ex:  FOO_BAR to FooBar.  It create a big headache of a refactor for me on my project.  I don't know of any similar changes for 3.2 -> 3.4.  I mainly just wanted to call it out as something to watch out for.

**Comment by Aaronontheweb** [comment]
@joshgarnett @alexvaluyskiy why include any Protobuf upgrades right now? Just drop them?

**Comment by Aaronontheweb** [comment]
Although, I guess it should be ok since all of that stuff is internal and this doesn't affect wire compatibility, right?

**Pull request merged**
