### PR TITLE
Upgraded to System.Collections.Immutable 1.3.1

### PR DESCRIPTION
**Pull request by Aaronontheweb**
This in order to validate a System.Collections.Immutable upgrade per #2286 - the part of Akka.NET most affected, performance-wise, by a change to this dependency is the `IChildrenContainer`, used to house child actor references inside a parent.

I've added a simple benchmark in order to measure the impact, given that the later versions of System.Collections.Immutable are designed to be much more memory efficient when it comes to copying than the current one we use (1.1.36)

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Benchmarked this locally and was disappointed with the results. No performance change at all really.

**Comment by Horusiath** [comment]
@Aaronontheweb keep in mind, that we already tried to move to actor child container to System.Collections.Immutable in the past, but we've moved back from this idea since v1.1.36 performance was a lot worse than our custom immutable collections implementations.

**Comment by Aaronontheweb** [comment]
Looks like the issue with this PR is that the benchmarks for `Akka.Tests.Performance` have been getting timed out by FAKE. Let me see how long that assembly is supposed to run for...

**Comment by Aaronontheweb** [comment]
@Horusiath we never switched back; the `IChildContainer` does still use `System.Collections.Immutable`, even though we took a performance hit. This is because the hand-rolled AVL trees we used before had all sorts of implementation errors that occurred somewhat racily.

**Comment by Aaronontheweb** [comment]
Going to need to get creative and rebase the both commits separately once #2512 is merged so I can get the build server's official results from before and after the `System.Collections.Immutable` upgrade.

**Comment by Aaronontheweb** [comment]
Using the latest System.Collections.Immutable (1.3.1)
-----

# Akka.Tests.Performance.Actor.Internal.ChildrenContainerSpec+FullChildrenContainer_add_children_speed_test
__Add as many children as possible to an a child container with lots of children already__
_2/15/2017 4:29:59 PM_
### System Info
```ini
NBench=NBench, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
WorkerThreads=32767, IOThreads=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   42,913,528.00 |   42,905,141.54 |   42,892,920.00 |        7,803.41 |
TotalCollections [Gen0] |     collections |           38.00 |           38.00 |           38.00 |            0.00 |
TotalCollections [Gen1] |     collections |            7.00 |            7.00 |            7.00 |            0.00 |
TotalCollections [Gen2] |     collections |            1.00 |            1.00 |            1.00 |            0.00 |
[Counter] ChildContainerMutations |      operations |      177,860.00 |      177,860.00 |      177,860.00 |            0.00 |

### Per-second Totals
          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   52,441,422.59 |   50,147,692.44 |   45,437,920.65 |    1,997,804.12 |
TotalCollections [Gen0] |     collections |           46.44 |           44.41 |           40.25 |            1.77 |
TotalCollections [Gen1] |     collections |            8.55 |            8.18 |            7.42 |            0.33 |
TotalCollections [Gen2] |     collections |            1.22 |            1.17 |            1.06 |            0.05 |
[Counter] ChildContainerMutations |      operations |      217,351.43 |      207,882.93 |      188,413.11 |        8,268.61 |

### Raw Data
#### TotalBytesAllocated
           Run # |           bytes |       bytes / s |      ns / bytes |
---------------- |---------------- |---------------- |---------------- |
               1 |   42,913,136.00 |   52,441,422.59 |           19.07 |
               2 |   42,900,176.00 |   52,175,973.63 |           19.17 |
               3 |   42,893,112.00 |   51,160,695.79 |           19.55 |
               4 |   42,913,528.00 |   51,041,438.05 |           19.59 |
               5 |   42,913,312.00 |   51,735,066.98 |           19.33 |
               6 |   42,913,432.00 |   51,137,003.68 |           19.56 |
               7 |   42,900,760.00 |   51,369,413.66 |           19.47 |
               8 |   42,905,864.00 |   49,977,593.53 |           20.01 |
               9 |   42,907,376.00 |   48,907,137.32 |           20.45 |
              10 |   42,900,576.00 |   47,931,301.62 |           20.86 |
              11 |   42,913,176.00 |   48,404,578.64 |           20.66 |
              12 |   42,892,920.00 |   45,437,920.65 |           22.01 |
              13 |   42,899,472.00 |   50,200,455.58 |           19.92 |

#### TotalCollections [Gen0]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |           38.00 |           46.44 |   21,534,371.05 |
               2 |           38.00 |           46.22 |   21,637,392.11 |
               3 |           38.00 |           45.32 |   22,063,150.00 |
               4 |           38.00 |           45.20 |   22,125,226.32 |
               5 |           38.00 |           45.81 |   21,828,476.32 |
               6 |           38.00 |           45.28 |   22,083,828.95 |
               7 |           38.00 |           45.50 |   21,977,423.68 |
               8 |           38.00 |           44.26 |   22,592,157.89 |
               9 |           38.00 |           43.31 |   23,087,457.89 |
              10 |           38.00 |           42.46 |   23,553,763.16 |
              11 |           38.00 |           42.86 |   23,330,315.79 |
              12 |           38.00 |           40.25 |   24,841,828.95 |
              13 |           38.00 |           44.47 |   22,488,510.53 |

#### TotalCollections [Gen1]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |            7.00 |            8.55 |  116,900,871.43 |
               2 |            7.00 |            8.51 |  117,460,128.57 |
               3 |            7.00 |            8.35 |  119,771,385.71 |
               4 |            7.00 |            8.33 |  120,108,371.43 |
               5 |            7.00 |            8.44 |  118,497,442.86 |
               6 |            7.00 |            8.34 |  119,883,642.86 |
               7 |            7.00 |            8.38 |  119,306,014.29 |
               8 |            7.00 |            8.15 |  122,643,142.86 |
               9 |            7.00 |            7.98 |  125,331,914.29 |
              10 |            7.00 |            7.82 |  127,863,285.71 |
              11 |            7.00 |            7.90 |  126,650,285.71 |
              12 |            7.00 |            7.42 |  134,855,642.86 |
              13 |            7.00 |            8.19 |  122,080,485.71 |

#### TotalCollections [Gen2]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |            1.00 |            1.22 |  818,306,100.00 |
               2 |            1.00 |            1.22 |  822,220,900.00 |
               3 |            1.00 |            1.19 |  838,399,700.00 |
               4 |            1.00 |            1.19 |  840,758,600.00 |
               5 |            1.00 |            1.21 |  829,482,100.00 |
               6 |            1.00 |            1.19 |  839,185,500.00 |
               7 |            1.00 |            1.20 |  835,142,100.00 |
               8 |            1.00 |            1.16 |  858,502,000.00 |
               9 |            1.00 |            1.14 |  877,323,400.00 |
              10 |            1.00 |            1.12 |  895,043,000.00 |
              11 |            1.00 |            1.13 |  886,552,000.00 |
              12 |            1.00 |            1.06 |  943,989,500.00 |
              13 |            1.00 |            1.17 |  854,563,400.00 |

#### [Counter] ChildContainerMutations
           Run # |      operations |  operations / s | ns / operations |
---------------- |---------------- |---------------- |---------------- |
               1 |      177,860.00 |      217,351.43 |        4,600.84 |
               2 |      177,860.00 |      216,316.56 |        4,622.85 |
               3 |      177,860.00 |      212,142.25 |        4,713.82 |
               4 |      177,860.00 |      211,547.05 |        4,727.08 |
               5 |      177,860.00 |      214,422.95 |        4,663.68 |
               6 |      177,860.00 |      211,943.60 |        4,718.24 |
               7 |      177,860.00 |      212,969.74 |        4,695.50 |
               8 |      177,860.00 |      207,174.82 |        4,826.84 |
               9 |      177,860.00 |      202,730.26 |        4,932.66 |
              10 |      177,860.00 |      198,716.71 |        5,032.29 |
              11 |      177,860.00 |      200,619.93 |        4,984.55 |
              12 |      177,860.00 |      188,413.11 |        5,307.49 |
              13 |      177,860.00 |      208,129.67 |        4,804.70 |

**Comment by Aaronontheweb** [comment]
Using the currently installed System.Collections.Immutable (1.1.36); Add children on a container that already has 50,000 children.
-----

# Akka.Tests.Performance.Actor.Internal.ChildrenContainerSpec+FullChildrenContainer_add_children_speed_test
__Add as many children as possible to an a child container with lots of children already__
_2/16/2017 1:54:46 AM_
### System Info
```ini
NBench=NBench, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
WorkerThreads=32767, IOThreads=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   41,908,064.00 |   41,849,073.23 |   41,824,768.00 |       20,323.29 |
TotalCollections [Gen0] |     collections |           37.00 |           37.00 |           37.00 |            0.00 |
TotalCollections [Gen1] |     collections |            6.00 |            6.00 |            6.00 |            0.00 |
TotalCollections [Gen2] |     collections |            1.00 |            1.00 |            1.00 |            0.00 |
[Counter] ChildContainerMutations |      operations |      173,391.00 |      173,391.00 |      173,391.00 |            0.00 |

### Per-second Totals
          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   58,411,069.29 |   55,178,139.46 |   48,711,430.30 |    2,773,650.98 |
TotalCollections [Gen0] |     collections |           51.64 |           48.78 |           43.07 |            2.45 |
TotalCollections [Gen1] |     collections |            8.37 |            7.91 |            6.98 |            0.40 |
TotalCollections [Gen2] |     collections |            1.40 |            1.32 |            1.16 |            0.07 |
[Counter] ChildContainerMutations |      operations |      242,002.92 |      228,616.28 |      201,836.90 |       11,484.93 |

### Raw Data
#### TotalBytesAllocated
           Run # |           bytes |       bytes / s |      ns / bytes |
---------------- |---------------- |---------------- |---------------- |
               1 |   41,825,072.00 |   55,362,762.14 |           18.06 |
               2 |   41,824,768.00 |   54,546,401.61 |           18.33 |
               3 |   41,850,544.00 |   56,427,035.33 |           17.72 |
               4 |   41,850,928.00 |   57,375,199.71 |           17.43 |
               5 |   41,850,544.00 |   56,713,341.30 |           17.63 |
               6 |   41,832,120.00 |   57,923,090.95 |           17.26 |
               7 |   41,850,544.00 |   58,411,069.29 |           17.12 |
               8 |   41,848,656.00 |   56,161,535.69 |           17.81 |
               9 |   41,908,064.00 |   56,195,078.20 |           17.80 |
              10 |   41,846,280.00 |   48,711,430.30 |           20.53 |
              11 |   41,849,344.00 |   53,152,728.92 |           18.81 |
              12 |   41,850,544.00 |   51,028,953.46 |           19.60 |
              13 |   41,850,544.00 |   55,307,186.13 |           18.08 |

#### TotalCollections [Gen0]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |           37.00 |           48.98 |   20,418,189.19 |
               2 |           37.00 |           48.25 |   20,723,624.32 |
               3 |           37.00 |           49.89 |   20,045,281.08 |
               4 |           37.00 |           50.72 |   19,714,200.00 |
               5 |           37.00 |           50.14 |   19,944,086.49 |
               6 |           37.00 |           51.23 |   19,518,948.65 |
               7 |           37.00 |           51.64 |   19,364,408.11 |
               8 |           37.00 |           49.65 |   20,139,135.14 |
               9 |           37.00 |           49.61 |   20,155,686.49 |
              10 |           37.00 |           43.07 |   23,217,970.27 |
              11 |           37.00 |           46.99 |   21,279,497.30 |
              12 |           37.00 |           45.11 |   22,165,764.86 |
              13 |           37.00 |           48.90 |   20,451,154.05 |

#### TotalCollections [Gen1]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |            6.00 |            7.94 |  125,912,166.67 |
               2 |            6.00 |            7.82 |  127,795,683.33 |
               3 |            6.00 |            8.09 |  123,612,566.67 |
               4 |            6.00 |            8.23 |  121,570,900.00 |
               5 |            6.00 |            8.13 |  122,988,533.33 |
               6 |            6.00 |            8.31 |  120,366,850.00 |
               7 |            6.00 |            8.37 |  119,413,850.00 |
               8 |            6.00 |            8.05 |  124,191,333.33 |
               9 |            6.00 |            8.05 |  124,293,400.00 |
              10 |            6.00 |            6.98 |  143,177,483.33 |
              11 |            6.00 |            7.62 |  131,223,566.67 |
              12 |            6.00 |            7.32 |  136,688,883.33 |
              13 |            6.00 |            7.93 |  126,115,450.00 |

#### TotalCollections [Gen2]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |            1.00 |            1.32 |  755,473,000.00 |
               2 |            1.00 |            1.30 |  766,774,100.00 |
               3 |            1.00 |            1.35 |  741,675,400.00 |
               4 |            1.00 |            1.37 |  729,425,400.00 |
               5 |            1.00 |            1.36 |  737,931,200.00 |
               6 |            1.00 |            1.38 |  722,201,100.00 |
               7 |            1.00 |            1.40 |  716,483,100.00 |
               8 |            1.00 |            1.34 |  745,148,000.00 |
               9 |            1.00 |            1.34 |  745,760,400.00 |
              10 |            1.00 |            1.16 |  859,064,900.00 |
              11 |            1.00 |            1.27 |  787,341,400.00 |
              12 |            1.00 |            1.22 |  820,133,300.00 |
              13 |            1.00 |            1.32 |  756,692,700.00 |

#### [Counter] ChildContainerMutations
           Run # |      operations |  operations / s | ns / operations |
---------------- |---------------- |---------------- |---------------- |
               1 |      173,391.00 |      229,513.17 |        4,357.05 |
               2 |      173,391.00 |      226,130.49 |        4,422.23 |
               3 |      173,391.00 |      233,782.87 |        4,277.47 |
               4 |      173,391.00 |      237,709.02 |        4,206.82 |
               5 |      173,391.00 |      234,969.06 |        4,255.88 |
               6 |      173,391.00 |      240,086.87 |        4,165.16 |
               7 |      173,391.00 |      242,002.92 |        4,132.18 |
               8 |      173,391.00 |      232,693.37 |        4,297.50 |
               9 |      173,391.00 |      232,502.29 |        4,301.03 |
              10 |      173,391.00 |      201,836.90 |        4,954.50 |
              11 |      173,391.00 |      220,223.40 |        4,540.84 |
              12 |      173,391.00 |      211,418.07 |        4,729.96 |
              13 |      173,391.00 |      229,143.22 |        4,364.08 |

**Comment by Aaronontheweb** [comment]
So according to this, the performance of 1.3.1 is technically worse (why can't anything be simple....) The two benchmarks were taken on different instances of the same type of VM, so I'm going to re-run the specs on top of the same piece of hardware and see how we do.

**Pull request merged**
