### PR TITLE
Removing all implementations of IActorLogging #515

### PR DESCRIPTION
**Pull request by avoxm**
Deprecating IActorLogging interface and removing its implementations.

### CODE REVIEW

**Comment by avoxm** [comment]
Build is failing because of "execution duration" specific test cases and is not related to the checked in changes.

**Comment by Aaronontheweb** [comment]
This looks good - I'll take a closer look at the source in the morning and give you some specific comments if they're necessary. Thanks for your contribution!

**Comment by Aaronontheweb** [comment]
All tests passed. Ran my clustered routing and deployment samples with no issues. Pulling this in.

Welcome to the Akka.NET team, @avoxm

**Comment by Aaronontheweb** [comment]
@avoxm whoops - looks like you added some commits since I started reviewing this PR. Could you put those onto a separate branch / PR ?

**Pull request merged**
