### PR TITLE
Remote PingPong benchmark

### PR DESCRIPTION
**Pull request by rogeralsing**
PingPong benchmark adapted to run two actor systems in the same process using Akka.Remote.
Shows throughput on loopback.

remotepingponglocalhost

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
This benchmark isn't as useful in Remote due to lack of parallelism on EndpointWriter (network message order preservation comes at a price) but I still think this is very useful to have in the short run

**Comment by rogeralsing** [comment]
A better use for this benchmark might be to alter it to ignore the dispatcher throughput and instead pass different sized messages.
That would give a hint on how message sizes and different serializers affect remote throughput.

**Comment by Aaronontheweb** [comment]
@rogeralsing I like that idea

**Comment by rogeralsing** [comment]
I'm closing this for now, I'll work on it to see if I can get more meaningful data out of it, but until then, closed

**Pull request closed without merging**
