### PR TITLE
Multinode Test Visualizer

### PR DESCRIPTION
**Pull request by GraemeBradbury**
VisualizerPersistenTestRunStore creates a html file with a timeline
visual showing the node events.

This file sits alongside the json file and has the same name
(different file extension)

#1196

### CODE REVIEW

**Comment by sean-gilliam** [comment]
Why include all the vis.js files in the PR? Maybe include it as CDN links in the html or reference it through a tool like bower for the dev to pull in on their own.

Just a suggestion. Otherwise looks great :+1:

**Comment by GraemeBradbury** [comment]
IMO it's a strength of the Akka.Net project that I can pull, type`build build` and it all just works. So putting a dependency on nodejs just to build the test report feels wrong to me.

Thinking about using a CDN raises a couple of questions
* What to do with our css? CDN as well?
* What about offline/intermittent connections? is it a problem?

**Comment by GraemeBradbury** [comment]
capture

Screenshot of visualizer in Chrome

**Comment by Aaronontheweb** [comment]
Figured out why TC didn't pick up this build. The timestamp of this commit is from 9 days ago, so TC won't pick it up.

Could do the following and update the timestamp to present time? http://stackoverflow.com/questions/454734/how-can-one-change-the-timestamp-of-an-old-commit-in-git

**Comment by GraemeBradbury** [comment]
@Aaronontheweb This runs consistently on local.
On build server it'll run the Cluster multinode tests but will consistently fail on the Remote multinode tests.

The build log doesn't contain any reason for failure beyond exit code 42. Which I've not been able to find in MSDN docs.

Have found mention of code 42 in reference to TeamCity not finding a file but the build logs show that both the runner and the dll are being created successfully in the locations expected.

A remote possibility could be that the exit code is 0x42 (BAD_DEV_TYPE - incorrect network resource type) which sorta makes sense considering the tests. It just seems unlikely considering Cluster builds and runs successfully.

**Comment by GraemeBradbury** [comment]
The test sinks seem to be working properly

````
[08:23:42][Step 1/1] Writing test state to: D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\bin\Release\Akka.Remote.Tests.MultiNode-635775565262939944.json
[08:23:42][Step 1/1] Writing test state to: D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\bin\Release\Akka.Remote.Tests.MultiNode-635775565262939944.html
```

Looks like its the RemoteRoundRobinSpec being consistently racy
```
[08:24:45][Step 1/1] [RUNNER][8:24 AM]: Results for Akka.Remote.Tests.MultiNode.RemoteRoundRobinMultiNode.RemoteRoundRobinSpecs
[08:24:45][Step 1/1] [RUNNER][8:24 AM]: Start time: 9/11/2015 8:22:06 AM
[08:24:45][Step 1/1] [RUNNER][8:24 AM]:  --> Node 1: PASS [00:00:27.6249069 elapsed]
[08:24:45][Step 1/1] [RUNNER][8:24 AM]:  --> Node 2: FAIL [00:01:02.6693675 elapsed]
[08:24:45][Step 1/1] [RUNNER][8:24 AM]:  --> Node 3: FAIL [00:00:42.6693895 elapsed]
[08:24:45][Step 1/1] [RUNNER][8:24 AM]:  --> Node 4: FAIL [00:00:27.5746810 elapsed]
```

**Comment by Aaronontheweb** [comment]
@GraemeBradbury I'm going to see about adding the multi-node test visualizer as an artifact of each build, so it can be viewed as part of the TC builds

**Comment by GraemeBradbury** [comment]
@Aaronontheweb Made some tweaks to make the visualizer work better from TC.
Basically took @sean-gilliam 's advice and used the CDN for VisJS with no other references. So each file is standalone.

**Comment by rogeralsing** [comment]
Do we need to have the full namespace written out on the events? 
`Akka.Cluster.Tests.MultiNode.LeaderLeavingSpecConfg.` wouldnt it be possible to somehow reduce the number of times we see the same prefix?
Add legends to charts or add headers or whatever.

Love it all but the event names are a mouthfull

**Pull request merged**
