### PR TITLE
Fixing Issue 3286

### PR DESCRIPTION
**Pull request by NickPolyder**
This is a fix for #3286 
Hello, i tried to found any reference to `MaybePublisher` and fix it. 
The API Tests pass but i would like to know if there is any unit test that i must create or alter for that.

Thanks.

### CODE REVIEW

**Comment by marcpiechura** [comment]
@NickPolyder a few specs need to be updated 
http://petabridge-ci.cloudapp.net/viewLog.html?buildId=46939&buildTypeId=AkkaNet_AkkaNetWindowsUnitTests&guest=1

**Comment by NickPolyder** [comment]
@marcpiechura  Okay cool. I will resolve all of them and get back to you. (Sorry for starting the pull request but i didnt had any other way of running all the unit tests)

**Comment by marcpiechura** [comment]
@NickPolyder no worries, I never run all tests, only the ones I think are affected, that’s what CI is for 😉

**Comment by NickPolyder** [comment]
@marcpiechura  So i think its safe to say that all the test passes.

Although i see the win - perf -tests fail. Could you explain to me what this error mean ? 

Thanks

**Comment by Horusiath** [comment]
@NickPolyder don't worry - performance tests are sensitive to what actually happens on the CPU. For this reason, sometimes they return false negatives.

**Comment by marcpiechura** [comment]
Thx @NickPolyder foe fixing this one! 
Closes #3286

**Pull request merged**
