### PR TITLE
Down if MemberStatus.Joining

### PR DESCRIPTION
**Pull request by ayoung**
This pull is intended to fix issue #2346.

I noticed that if a cluster member is in `Joining` state when you call `cluster.Leave()`, the member will appear unreachable to other nodes indefinitely. This adds a check to see if the state is `Joining`, then call `Downing()` instead.

The only caveat to this is that if you have a callback waiting on `cluster.RegisterOnMemberRemoved(someAction)` then this won't be called. Is there some other event that should be hooked into for this?

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Wondering how we can test this to ensure that it works....

**Comment by Danthar** [comment]
Status on this one? The change itself looks good. @Aaronontheweb

**Comment by Aaronontheweb** [comment]
I think this one still needs a spec to verify that its behavior is inline with the cluster specifications

**Comment by Aaronontheweb** [comment]
resolved via https://github.com/akkadotnet/akka.net/pull/3551

**Pull request closed without merging**
