### PR TITLE
Fixed logic on how to get current events by tag in batches

### PR DESCRIPTION
**Pull request by ptjhuang**
#3697 

Looking at the Scala LevelDb implementation, it looks like they have a special "$$$tag" persistence-id that stores the highest sequence number.

Most SQL database are fairly good at getting highest value of an indexed column, so it's done as a separate query.

### CODE REVIEW

**Comment by angrybug** [comment]
Tests failed in areas I didn't change?

**Comment by Aaronontheweb** [comment]
@ptjhuang yeah that's our fault - racy unit tests that we haven't debugged yet. I'll take a look at it and do a proper review on this PR. Sorry for the delay - been traveling in Europe for work :p

**Comment by ericphan** [comment]
@Aaronontheweb I'm running into this issue as well, do you have an ETA on when this will be merged in?

**Comment by Aaronontheweb** [comment]
@ericphan I'll look at it today

**Comment by Aaronontheweb** [comment]
@ericphan @ptjhuang going to release this as part of Akka.NET v1.3.12 this week.

**Pull request merged**
