### PR TITLE
Adding DependencyInjection SimpleInjector and Tests

### PR DESCRIPTION
**Pull request by tmusico**

### CODE REVIEW

**Comment by rogeralsing** [comment]
Looks good.
Can you squash the commits into one?

cc @akkadotnet/contributors should we pull this into the main repo?
There is a risk of the main repo containing too many 3rd party addons that might be hard to maintain in the long run.

**Comment by tmusico** [comment]
@rogeralsing I squashed commits, it failed continuous-integration/windows-multinode-tests .. how can i fix this?

**Comment by Aaronontheweb** [comment]
@tmusico I restarted them for you

**Comment by CarlosTorrecillas** [comment]
Are there any plans of merging this eventually?

Cheers!

**Comment by Aaronontheweb** [comment]
@CarlosTorrecillas our plan is to move all of these DI frameworks out of the core project and the @akkadotnet/core team will not actively support them. We'll provide infrastructure for CI and the like, but you won't see any of us committing code unless we're actively using the plugin in our own projects. So, if you want to see something like this be released, help make sure there are people interested in maintaining it.

**Comment by CarlosTorrecillas** [comment]
@Aaronontheweb is there any plan though in creating a "DI repo" that can be maintained by the community or will it not be even created under akkadotnet? I'm happy to help in migrating into the new project if there is one.

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/Akka.DI.SimpleInjector - @Horusiath is creating them now

**Comment by CarlosTorrecillas** [comment]
Hi @Aaronontheweb  i submitted a PR a couple of days ago to https://github.com/akkadotnet/Akka.DI.SimpleInjector so it's ready for you guys to review it and hopefully merge it in.

**Comment by Danthar** [comment]
@CarlosTorrecillas How would you feel about taking ownership of the SimpleInjector plugin ?

**Comment by CarlosTorrecillas** [comment]
I would be fine with it @Danthar

**Comment by Danthar** [comment]
Ok the PR in the https://github.com/akkadotnet/Akka.DI.SimpleInjector repos is merged. So im going to close this one.

@akkadotnet/core how do you feel about giving the https://github.com/akkadotnet/Akka.DI.SimpleInjector maintainership to @CarlosTorrecillas

**Comment by Horusiath** [comment]
I'm all for that. It's always better for the library to have concrete person supporting it, than some abstract organization ;)

**Comment by Aaronontheweb** [comment]
go for it @Danthar

**Comment by MichaelLogutov** [comment]
In current implementation I was unable to use SimpleInjector Verify method to test that DI container has all dependencies correctly wired.

It's because for such self test to work we need to register all actors classes in container for Verify method was able to test that all their depdendencies are correctly registered. Verify method testing this by creating each instance of registered type to see if there is something wrong - and thats where Akka throws:

```
Do not create actors using 'new', always create them using an ActorContext/System
```

**Comment by Danthar** [comment]
@MichaelLogutov Akka has its own instance build pipeline for actors. SimpleInjector's verify resolves an actor type, outside of the scope of an ActorSystem. Thats why you are getting this error.

Unless you can tweak the SimpleInjectors diagnostics system to test actor resolves from inside the scope of an actorsystem, I suggest you use the 'SuppressDiagnosticWarning` function on an actor registration to suppress verification errors.

**Pull request closed without merging**
