### PR TITLE
#1248 added Akka.Remote MultiNodeSpec: RemoteDeploymentDeathWatchSpec

### PR DESCRIPTION
**Pull request by maxim-s**

### CODE REVIEW

**Comment by maxim-s** [comment]
Just one point, I didn't implement printTree method for ActorSystem

**Comment by Aaronontheweb** [comment]
Looks like it failed:

```
 Results for Akka.Remote.Tests.MultiNode.RemoteDeploymentDeathWatchMultiNode.AnActorSystemThatDeploysActorsOnAnotherNodeMustBeAbleToShutdownWhenRemoteNodeCrash
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: Start time: 11/11/2015 2:12:58 PM
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Node 1: FAIL [00:00:02.7358512 elapsed]
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Node 2: FAIL [00:00:02.8429711 elapsed]
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Node 3: FAIL [00:00:02.7551369 elapsed]
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: End time: 11/11/2015 2:13:04 PM
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: FINAL RESULT: FAIL after 00:00:05.8911064.
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: Failure messages by Node
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: <----------- BEGIN NODE 1 ----------->
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Akka.Remote.Tests.MultiNode.RemoteDeploymentDeathWatchMultiNode1.AnActorSystemThatDeploysActorsOnAnotherNodeMustBeAbleToShutdownWhenRemoteNodeCrash FAIL
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Message: Assert.True() Failure
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Type: Xunit.Sdk.TrueException
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: <----------- END NODE 1 ----------->
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: <----------- BEGIN NODE 2 ----------->
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Akka.Remote.Tests.MultiNode.RemoteDeploymentDeathWatchMultiNode2.AnActorSystemThatDeploysActorsOnAnotherNodeMustBeAbleToShutdownWhenRemoteNodeCrash FAIL
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Message: Assert.True() Failure
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Type: Xunit.Sdk.TrueException
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: <----------- END NODE 2 ----------->
[14:13:52][Step 1/1] [RUNNER][2:13 PM]: <----------- BEGIN NODE 3 ----------->
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Akka.Remote.Tests.MultiNode.RemoteDeploymentDeathWatchMultiNode3.AnActorSystemThatDeploysActorsOnAnotherNodeMustBeAbleToShutdownWhenRemoteNodeCrash FAIL
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Message: Assert.True() Failure
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
[14:13:52][Step 1/1] [RUNNER][2:13 PM]:  --> Type: Xunit.Sdk.TrueException
```

Are you able to get this running locally?

**Comment by maxim-s** [comment]
I'm checking it, because it works locally

**Comment by maxim-s** [comment]
@Aaronontheweb , problems were solved

**Comment by rogeralsing** [comment]
Perfect!

**Pull request merged**
