### PR TITLE
PatternMatch with result returning support. 

### PR DESCRIPTION
**Pull request by kantora**
Especially useful for FSM state function definition.

### CODE REVIEW

**Comment by kantora** [comment]
Rebased on latest dev

**Comment by ismaelhamed** [comment]
Any chance we can move this PR forward and have it merged?

**Comment by Danthar** [comment]
Needs api approval. But other then that. Should be ok.

**Comment by Danthar** [comment]
@kantora do you mind going through: http://getakka.net/docs/akka-developers/public-api-changes for this PR ?

**Comment by kantora** [comment]
@Danthar I don't mind, but I don't get at this moment what is expected to be done from me?
As far as I understood this API changes should be approved. Should I approve my own changes or this should be done by someone else?

**Comment by kantora** [comment]
Ouchh... finally got the main idea from second read.

**Comment by kantora** [comment]
Updated to the latest dev and added api approval.

**Comment by kantora** [comment]
But suppose this will become obsolete with C#7 built-in pattern matching.

**Pull request merged**
