### PR TITLE
Removed inconsistent constructor from RoundRobinPool per #967

### PR DESCRIPTION
**Pull request by guessmyname**
Corrected associated tests.

### CODE REVIEW

**Comment by Danthar** [comment]
This change modifies the API. Therefore needs approval: http://getakka.net/docs/akka-developers/public-api-changes

**Comment by Danthar** [comment]
@Aaronontheweb or @Horusiath Could one of you chime in on this. I would like to have some more consensus on merging this PR (provided the mono build completes). Since it has impact on the public API, albeit minor.

**Comment by alexvaluyskiy** [comment]
@guessmyname why this constructor is inconsistent?

**Comment by Danthar** [comment]
@alexvaluyskiy  This PR is about: https://github.com/akkadotnet/akka.net/issues/967

**Comment by Aaronontheweb** [comment]
I don't think this PR adds any value really, even if the constructor is inconsistent. Just mark it as deprecated.

**Comment by alexvaluyskiy** [comment]
Scala has much more powerful default parameters and named parameters features. That's why Scala has only one constructor, but we should have a couple of overloaded constructors

**Comment by Danthar** [comment]
Closing this as a "wont fix" @guessmyname thx for the effort. A valuable discussion was had. And this issue can now be removed from our list.

**Pull request closed without merging**
