### PR TITLE
Add PipeTo for non-generic Tasks for exception handling

### PR DESCRIPTION
**Pull request by adamhathcock**
This feels like something I want to do.  Let me know if this is a bad idea and I won't be doing in my own code.

### CODE REVIEW

**Comment by nvivo** [comment]
The idea of PipeTo is to pipe the result of the task to the recipient. If the task doesn't have a result, what are you piping? Only the failure?

**Comment by adamhathcock** [comment]
Correct.  I'd want the parent is try to handle the error and not just let it die in Task-land

**Comment by rogeralsing** [comment]
Looks good, this is in line with what JVM Akka does.
´´´scala
  final class PipeableFuture[T](val future: Future[T])(implicit executionContext: ExecutionContext) {
    def pipeTo(recipient: ActorRef)(implicit sender: ActorRef = Actor.noSender): Future[T] = {
      future onComplete {
        case Success(r) ⇒ recipient ! r
        case Failure(f) ⇒ recipient ! Status.Failure(f)
      }
      future
    }
```

**Comment by stefansedich** [comment]
I lile it! 

Do we need to have a test around it?

**Comment by nvivo** [comment]
Agreed. Makes sense to me.

**Pull request merged**
