### PR TITLE
added CachingConfig to MessageDispatcherConfigurator

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Brings things up to code with the JVM and eliminates most parsing from https://github.com/akkadotnet/akka.net/pull/2538

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb you referenced wrong PR. My PR is not related with parsing of HOCON

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy I think the NBench tests are still fine, judging from the logs it looks like all of our build servers are really busy. Seeing some issues show up on the NBench releases themselves today.

As for the PR, yours is the one that will see the biggest impact from this change.

**Comment by Aaronontheweb** [comment]
# Perf Results

## Before

 Akka.Tests.Performance.Actor.ActorMemoryFootprintSpec+ReceiveActor_memory_footprint
__Measures the amount of memory used by 10,000 ReceiveActors__
_3/8/2017 1:01:24 AM_

### Totals
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   20,944,568.00 |   19,328,385.23 |   16,696,520.00 |    1,395,676.39 |
[Counter] ActorCreateThroughput |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |

### Per-second Totals
          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |  122,003,259.70 |  101,178,460.22 |   84,299,589.47 |   10,076,411.87 |
[Counter] ActorCreateThroughput |      operations |       58,250.55 |       52,364.84 |       46,843.17 |        3,693.29 |

## After

Akka.Tests.Performance.Actor.ActorMemoryFootprintSpec+ReceiveActor_memory_footprint
__Measures the amount of memory used by 10,000 ReceiveActors__
_3/8/2017 2:20:28 AM_

### Totals
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |   17,162,832.00 |   16,780,139.69 |   16,019,768.00 |      327,654.95 |
[Counter] ActorCreateThroughput |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |

### Per-second Totals
          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalBytesAllocated |           bytes |  130,256,920.09 |  115,312,494.60 |   98,261,117.81 |    9,759,801.99 |
[Counter] ActorCreateThroughput |      operations |       76,357.50 |       68,658.51 |       60,228.12 |        4,825.84 |

**Comment by Aaronontheweb** [comment]
Throughput increased from 52,364.84 actors created per second to 68,658.51 per second, 31% increase.

**Pull request merged**
