### PR TITLE
#2271 Akka.Cluster.Tools.PublishSubscribe.Internal made public

### PR DESCRIPTION
**Pull request by kantora**
Fix for the https://github.com/akkadotnet/akka.net/issues/2271

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
Maybe Wire should fix it?

**Comment by kantora** [comment]
Did I break the tests or they was already broken?

**Comment by kantora** [comment]
@alexvaluyskiy this is supposed to be the temporary patch until Wire is fixed (or the correct solution designed). Just to bring functionality up. As it was discussed with @Danthar in the original issue.

P.S. I know, no one likes kludges.

**Comment by Danthar** [comment]
A few remarks: 
A: I dont think this PR broke the unit tests. I think its either a racy tests thingy, or something else.
B: Like i said in the issue topic, I vote to make a PR fixing this in the Akka codebase. And @kantora followed up on that, rightly so.

The reason why I think this should be fixed in akka is because on one hand I don't want to block fixing this issue on developments in Wire (its really a minor change from the akka codebase perspective). And on the other hand I dont believe this will be fixed in Wire.

I mean, it was an internal type. Internal types are generally not meant to be serialized. So really, its no surprise Wire barfed on this.

**Comment by alexvaluyskiy** [comment]
@Danthar we are changing our public API only for temporary quick-fix?

**Comment by alexvaluyskiy** [comment]
@kantora if you change public fields to readonly properties in these classes, will it fix the problem?

**Comment by kantora** [comment]
@alexvaluyskiy Just to be clear. Despite the subject, only two classes were made public (`Akka.Cluster.Tools.PublishSubscribe.Internal.Bucket` and `Akka.Cluster.Tools.PublishSubscribe.Internal.ValueHolder`) in order to be serializable.

> @kantora if you change public fields to readonly properties in these classes, will it fix the problem?

As I understood Wire can't serialize internal classes.
The exception:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: `Wire.SerializerFactories.ArraySerializerFactory.WriteValues<Akka.Cluster.Tools.PublishSubscribe.Internal.Bucket>(System.Collections.Generic.IReadOnlyList<Akka.Cluster.Tools.PublishSubscribe.Internal.Bucket>, System.IO.Stream, System.Type, Wire.ValueSerializers.ValueSerializer, Wire.SerializerSession)' is inaccessible due to its protection level
```
But readonly fields worked well (so readonly properties should work well to I suppose).

@alexvaluyskiy so correct solution will be moving `Bucket` and `ValueHolder` from `Internal` namespace, replacing all public fields with properties. Am I right?

**Comment by alexvaluyskiy** [comment]
> As I understood Wire can't serialize internal classes.
So, we should fix Wire

**Comment by rogeralsing** [comment]
I'll provide a fix inside Wire instead.
I found out what the issue is.
The current ArraySerializer in wire do some magic tricks when calling a generic method, this fails for internal types.
Internal types works everywhere else in Wire, thus it has not been spotted before.

I vote for closing this, and I'll have a fix out ASAP.

**Comment by Silv3rcircl3** [comment]
Closing, will be fixed in Wire.

**Pull request closed without merging**
