### PR TITLE
Add log4net logging adapter support

### PR DESCRIPTION
**Pull request by onatm**
Added support for log4net logging. :dart:

### CODE REVIEW

**Comment by rogeralsing** [comment]
Looks good.
cc @akkadotnet/developers should we include more contrib loggers in the core repo or should we opt for keeping this externally?

**Comment by annymsMthd** [comment]
I think log4net is a pretty widely used logger and we should probably add it to core.
@onatm can you rebase this PR?

**Comment by onatm** [comment]
@annymsMthd done :+1:

**Comment by onatm** [comment]
I thought a quick rebase was enough but after b293dae377f9f90979a7c5a6819e7891b88395d2 there are so many build errors. I'm trying to fix the problems.

**Pull request merged**
