### PR TITLE
DistributedPubSubMediator - an error in HandlePrune, Fix of fix in #2222 (removed multiple enumeration)

### PR DESCRIPTION
**Pull request by kantora**
Sorry, I've replaced one bug with another. This should help.

### CODE REVIEW

**Comment by kantora** [comment]
Hmmm... There is no more exception here, but it still works wrong... Now it silently drops active subscriptions.

**Comment by kantora** [comment]
The original pull request: https://github.com/akkadotnet/akka.net/pull/2222
The original issue: https://github.com/akkadotnet/akka.net/issues/2221

**Comment by alexvaluyskiy** [comment]
@kantora I can't merge this PR, because we don't have any test for "HandlePrune" neither in MNTK tests nor in unit tests. Could you create the one. If not, just share some examples of code, which can help me to reproduce this bug

**Comment by kantora** [comment]
@alexvaluyskiy As for me, it reproduces just each time cluster pub/sub is used, if you give it at least 2 or 3 minutes to run. And, to be honest, this pr just hides the problem (as it prevents the exception to appear) and don't fixes it. I've described the main issue in https://github.com/akkadotnet/akka.net/issues/2226.

As for this particular PR - the fix is obvious from code as the previous version modified dictionary while was iterating it and fixes the recently merged PR https://github.com/akkadotnet/akka.net/pull/2222.

**Comment by alexvaluyskiy** [comment]
@kantora I've tested your code, it really fixed the problem. But we shouldn't test our code manually. So we should create a test for it. I've created an issue for this case
https://github.com/akkadotnet/akka.net/issues/2232

**Pull request merged**
