### PR TITLE
Hard-code RepositoryUrl

### PR DESCRIPTION
**Pull request by eaba**

### CODE REVIEW

**Review by Aaronontheweb — APPROVED** [review]
LGTM @eaba

**Comment by Aaronontheweb** [comment]
The failing tests so far appear to be racy unit tests - nothing @eaba changed in this PR would cause those to fail.

**Comment by Aaronontheweb** [comment]
@eaba approval tests all failed

**Comment by eaba** [comment]
@Aaronontheweb all the approval tests passed locally before I pushed the commit

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
@eaba other API approvals are missing - please actively look at the test results on Github when they fail.

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Missing API approvals

**Pull request closed without merging**
