### PR TITLE
WIP add retry stage

### PR DESCRIPTION
**Pull request by marcpiechura**
Clone from https://github.com/AkkaNetContrib/Alpakka/pull/19

### CODE REVIEW

**Comment by marcpiechura** [comment]
@vasily-kirichenko could you copy/paste the test code so that your contribution is kept ?

**Comment by vasily-kirichenko** [comment]
@marcpiechura I tried hard to make a PR to your branch and failed - github does not show your repo as a base :(

**Comment by vasily-kirichenko** [comment]
So I've made a new PR https://github.com/akkadotnet/akka.net/pull/3235

**Comment by vasily-kirichenko** [comment]
Merge my branch or whatever you find more appropriate.

**Comment by marcpiechura** [comment]
All good, we take your PR :wink:

**Pull request closed without merging**
