### PR TITLE
Monotonic clock for #846

### PR DESCRIPTION
**Pull request by kekekeks**
#846

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
So I guess we'd need to integrate this inside `Deadline`, `IScheduler`, and so forth... I agree that this is the right way to provide consistent + high resolution clock behavior internally.

Any thoughts as to how difficult this will be to integrate into those other areas?

**Comment by HCanber** [comment]
Do not pull this is in yet, see discussion in #846

**Comment by Aaronontheweb** [comment]
@HCanber does this look like it's ready to pull in?

**Comment by Aaronontheweb** [comment]
The MonotonicClock values still need to be integrated with the actual `Scheduler`, but for now I'm going to pull it in.

**Comment by HCanber** [comment]
Sorry, missed this.
Can we somehow mark these as experimental? Although they fulfill what's needed, I don't like the api, and I'm not sure the user will understand when to use them.
Maybe mark them with `[Obsolete("Experimental. Might be removed and replaced with something else")]`.

**Pull request merged**
