### PR TITLE
remove redundant string interpolation

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by Arkatufus — APPROVED** [review]
LGTM

**Review by Aaronontheweb — DISMISSED** [review]
Looks like there's a real test failure in one of the suites

> Assert.Contains() Failure: Sub-string not found
String:    "Illegal actor name [üß]. Actor paths MUST"···
Not found: "include only ASCII"

**Comment by Aaronontheweb** [comment]
Name of the failing test: Akka.Tests.Actor.LocalActorRefProviderSpec.An_ActorRefFactory_must_throw_suitable_exceptions_for_malformed_actor_names(name: "üß", expectedExceptionMessageSubstring: "include only ASCII")

**Comment by Aaronontheweb** [comment]
This error is happening in `dev` too so it's not this PR - we will track this down

**Pull request merged**
