### PR TITLE
Removed Reentrancy behavior

### PR DESCRIPTION
**Pull request by rogeralsing**
Removing all traces of async reentrancy.

### CODE REVIEW

**Comment by rogeralsing** [comment]
The build error, is that something else or what causes that?
"it works on my machine"...

**Comment by annymsMthd** [comment]
Looks like a nuget issue

**Comment by nvivo** [comment]
I'm all for it, but doesn't this change the API? Where do we draw the line?

**Comment by rogeralsing** [comment]
Yes it does change the API, but hopefully reentrancy was not widely used, and there is just too much noise around it that steals focus from the project itself. 
So I'm all for breaking that part..

**Comment by nvivo** [comment]
Agree.

**Comment by HCanber** [comment]
Agree

**Comment by Aaronontheweb** [comment]
yeah science

Pulling this in.

**Pull request merged**
