### PR TITLE
Always check for non empty journal batch before sending to journal

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Fix https://github.com/akka/akka/issues/21116

### CODE REVIEW

**Comment by cconstantin** [comment]
@alexvaluyskiy if this is the only persistence related change in 2.4.9, would you mind also updating the `jvm-version.txt` file?

**Comment by alexvaluyskiy** [comment]
@cconstantin we could have a wiki page with versions, like this
https://gist.github.com/alexvaluyskiy/8b40d06c4c70ecf56b45551b57315559

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy let's just update the file in the repo. Could you update that please?

**Comment by Danthar** [comment]
Needs rebase (and update?)

**Comment by Silv3rcircl3** [comment]
needs a rebase again

**Comment by Aaronontheweb** [comment]
@Silv3rcircl3 used my magic administrator privilege to bring it in :p

**Pull request merged**
