### PR TITLE
Continue with the next nuget/symbol upload if one failed

### LINKED ISSUE #838: Rewrite NuGet build script so each individual package upload gets retryed on failure
Right now a NuGet release is "all or nothing" - if one NuGet package gets uploaded but the others fail, then the entire job fails permanently and I have to manually upload all packages.

We should rewrite the FAKE script to wrap each individual package upload in a retry and allow them to continue independent of eachother.

### PR DESCRIPTION
**Pull request by Silv3rcircl3**
The retry feature mentioned in #838 was already implemented. 

closes #838

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Ah, you are the man - I had no idea it was this simple.

**Comment by Aaronontheweb** [comment]
Turns out this wasn't as simple as this - the build script uploads successfully once and then keeps trying over and over again. Could you take another look at this @Silv3rcircl3 ?

```
[19:10:55][Step 1/1] Pushing nuget packages
[19:10:55][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 3
[19:10:56][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:03][Step 1/1] Your package was pushed.
[19:11:03][Step 1/1] Pushing Akka 1.0.5 to the symbol server (https://nuget.smbsrc.net/)...
[19:11:55][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 2
[19:11:56][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:57][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:11:57][Step 1/1] The remote server returned an error: (409) Conflict..
[19:11:57][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 1
[19:11:58][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:59][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:11:59][Step 1/1] The remote server returned an error: (409) Conflict..
[19:11:59][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 0
[19:11:59][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:12:00][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:12:00][Step 1/1] The remote server returned an error: (409) Conflict..
[19:12:00][Step 1/1] Error during NuGet symbol push. D:\BuildAgent\work\86e8e7aa463877c0\src\.nuget\NuGet.exe push "D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg" key omitted
[19:12:00][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.Cluster.1.0.5.14-beta.nupkg Attempts left: 3
[19:12:01][Step 1/1] Pushing Akka.Cluster 1.0.5.14-beta to the NuGet gallery (https://www.nuget.org)...
[19:12:06][Step 1/1] Your package was pushed.
[19:12:06][Step 1/1] Pushing Akka.Cluster 1.0.5.14-beta to the symbol server (https://nuget.smbsrc.net/)...
[19:13:00][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.Cluster.1.0.5.14-beta.nupkg Attempts left: 2
[19:13:01][Step 1/1] Pushing Akka.Cluster 1.0.5.14-beta to the NuGet gallery (https://www.nuget.org)...
[19:13:02][Step 1/1] Failed to process request. 'A package with id 'Akka.Cluster' and version '1.0.5.14-beta' already exists and cannot be modified.'. 
[19:13:02][Step 1/1] The remote server returned an error: (409) Conflict..
[19:13:02][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.Cluster.1.0.5.14-beta.nupkg Attempts left: 1
[19:13:02][Step 1/1] Pushing Akka.Cluster 1.0.5.14-beta to the NuGet gallery (https://www.nuget.org)...
[19:13:03][Step 1/1] Failed to process request. 'A package with id 'Akka.Cluster' and version '1.0.5.14-beta' already exists and cannot be modified.'. 
[19:13:03][Step 1/1] The remote server returned an error: (409) Conflict..
[19:13:03][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.Cluster.1.0.5.14-beta.nupkg Attempts left: 0
[19:13:04][Step 1/1] Pushing Akka.Cluster 1.0.5.14-beta to the NuGet gallery (https://www.nuget.org)...
[19:13:04][Step 1/1] Failed to process request. 'A package with id 'Akka.Cluster' and version '1.0.5.14-beta' already exists and cannot be modified.'. 
[19:13:04][Step 1/1] The remote server returned an error: (409) Conflict..
[19:13:04][Step 1/1] Error during NuGet symbol push. D:\BuildAgent\work\86e8e7aa463877c0\src\.nuget\NuGet.exe push "D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.Cluster.1.0.5.14-beta.nupkg" key omitted
[19:13:04][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.DI.AutoFac.1.0.5.nupkg Attempts left: 3
[19:13:05][Step 1/1] Pushing Akka.DI.AutoFac 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:13:10][Step 1/1] Your package was pushed.
[19:13:10][Step 1/1] Pushing Akka.DI.AutoFac 1.0.5 to the symbol server (https://nuget.smbsrc.net/)...
[19:14:04][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.DI.AutoFac.1.0.5.nupkg Attempts left: 2
[19:14:05][Step 1/1] Pushing Akka.DI.AutoFac 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:14:07][Step 1/1] Failed to process request. 'A package with id 'Akka.DI.AutoFac' and version '1.0.5' already exists and cannot be modified.'. 
[19:14:07][Step 1/1] The remote server returned an error: (409) Conflict..
[19:14:07][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.DI.AutoFac.1.0.5.nupkg Attempts left: 1
[19:14:07][Step 1/1] Pushing Akka.DI.AutoFac 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:14:08][Step 1/1] Failed to process request. 'A package with id 'Akka.DI.AutoFac' and version '1.0.5' already exists and cannot be modified.'. 
[19:14:08][Step 1/1] The remote server returned an error: (409) Conflict..
[19:14:08][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.DI.AutoFac.1.0.5.nupkg Attempts left: 0
[19:14:08][Step 1/1] Pushing Akka.DI.AutoFac 1.0.5 to the NuGet gallery (https://www.nuget.org)...
```

Like that for every package ;)

**Comment by Silv3rcircl3** [comment]
Yeah of course, but that's really strange since I didn't changed the retry logic. Maybe the nuget.exe isn't returning 0 ... We will se ;-)

**Comment by Silv3rcircl3** [comment]
One thing I would like to check before I try to resolve this, because it is working fine in the nightly build...

```
[Step 1/1] Pushing nuget packages
[00:01:45][Step 1/1] Pushing D:\BuildAgent\work\e5ed5ddbe4b3a95f\bin\nuget\Akka.1.0.6.120-beta.nupkg Attempts left: 3
[00:01:45][Step 1/1] Pushing Akka 1.0.6.120-beta to 'https://www.myget.org/F/akkadotnet/api/v2'...
[00:02:03][Step 1/1] Your package was pushed.
[00:02:03][Step 1/1] Pushing D:\BuildAgent\work\e5ed5ddbe4b3a95f\bin\nuget\Akka.Cluster.1.0.6.120-beta.nupkg Attempts left: 3
[00:02:04][Step 1/1] Pushing Akka.Cluster 1.0.6.120-beta to 'https://www.myget.org/F/akkadotnet/api/v2'...
[00:02:16][Step 1/1] Your package was pushed.
```

The issue you described in #838 matches exactly this behavior, the first Nuget package get's uploaded successfully but it still retries to upload the package three times and then throws the exception and you have to upload the other packages manually. So could you take a look in a previous release build and check if the behavior is the same (I couldn't find the release builds in Teamcity)?
```
[19:10:55][Step 1/1] Pushing nuget packages
[19:10:55][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 3
[19:10:56][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:03][Step 1/1] Your package was pushed.
[19:11:03][Step 1/1] Pushing Akka 1.0.5 to the symbol server (https://nuget.smbsrc.net/)...
[19:11:55][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 2
[19:11:56][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:57][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:11:57][Step 1/1] The remote server returned an error: (409) Conflict..
[19:11:57][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 1
[19:11:58][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:11:59][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:11:59][Step 1/1] The remote server returned an error: (409) Conflict..
[19:11:59][Step 1/1] Pushing D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg Attempts left: 0
[19:11:59][Step 1/1] Pushing Akka 1.0.5 to the NuGet gallery (https://www.nuget.org)...
[19:12:00][Step 1/1] Failed to process request. 'A package with id 'Akka' and version '1.0.5' already exists and cannot be modified.'. 
[19:12:00][Step 1/1] The remote server returned an error: (409) Conflict..
[19:12:00][Step 1/1] Error during NuGet symbol push. D:\BuildAgent\work\86e8e7aa463877c0\src\.nuget\NuGet.exe push "D:\BuildAgent\work\86e8e7aa463877c0\bin\nuget\Akka.1.0.5.nupkg" key omitted
``` 
**without the try catch block the whole upload would stop here**

**Pull request merged**
