### PR TITLE
DistributedPubSub: Use TypeQualifiedNameForManifest with Manifest required Serializers

### PR DESCRIPTION
**Pull request by jordansjones**
Instead of `.FullName`.

### CODE REVIEW

**Comment by Horusiath** [comment]
Any rationale for that? Problem with assembly qualified names is that they contains things like version or token number - which are not used elsewhere in serialization pipeline and can cause unexpected behavior when incremental upgrades are going to happen while pub/sub is working.

**Comment by alexvaluyskiy** [comment]
I think we should have an extension like this and use it everywhere, instead of AssemblyQualifiedName
```csharp
    public static class TypeExtensions
    {
        public static string TypeQualifiedNameForManifest(this Type type)
        {
            return type == null ? string.Empty : $"{type.FullName}, {type.Assembly.GetName().Name}";
        }
    }
```

**Comment by cconstantin** [comment]
@alexvaluyskiy iirc correctly I added such an extension when updating persistence a while back, but it may be in persistence.

**Comment by JordanJones** [comment]
@Horusiath the rational is that without the assembly name, `Type.GetType(...)` returns `null`. But I'm all for having an extension method.

I'll create one if there isn't one already in the core `Akka` project and update my PR either tonight or tomorrow sometime.

**Comment by jordansjones** [comment]
Turns out that I missed the `TypeQualifiedNameForManifest` method on the base serializer. I've opted to use that instead of the `AssemblyQualifiedName` value.

**Pull request merged**
