### PR TITLE
Add cross-platform spec test to MNTR

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Arkatufus** [comment]
Very simple cross platform spec test for multi node test runner.
All it does is alternate the node test runner binary used to run each node role in each spec between Net and Net Core binaries

**Comment by Arkatufus** [comment]
Note that cross platform test support is only available on Net Core build.

**Comment by Aaronontheweb** [comment]
@Arkatufus just so I understand correctly, all this PR provides right now are some switches for enabling X-plat multi-node tests. Not any actual x-plat multi-node tests themselves, correct?

**Comment by Aaronontheweb** [comment]
Derp, nevermind:

> Very simple cross platform spec test for multi node test runner.
All it does is alternate the node test runner binary used to run each node role in each spec between Net and Net Core binaries

**Pull request merged**
