### PR TITLE
Unit test Akka.FSharp.System.create with extensions

### PR DESCRIPTION
**Pull request by aaronpalmer**
Add a unit test to demonstrate a bug with Akka.FSharp.System.create when creating with a configuration that has akka.extensions specified.

### CODE REVIEW

**Comment by AaronEshbach** [comment]
I did a little research, and there is a conflicting serializer ID.  Both the Cluster Tools DistributedPubSubMessageSerializer and the FSharp ExprSerializer use the same identifier, 9.  I think changing the ID for one of these serializers would fix this unit test.

**Comment by Danthar** [comment]
Thx for your contribution

**Comment by Aaronontheweb** [comment]
@AaronEshbach did that issue with the colliding serializer IDs get resolved? Or should we file a new issue for that?

**Comment by AaronEshbach** [comment]
We tested Akka.FSharp with Akka.Cluster.Tools at version 1.3.8, and the issue appears to be resolved.

**Pull request merged**
