### PR TITLE
Akka IO

### PR DESCRIPTION
**Pull request by willieferguson**
Merge PR from akka-io to dev. 

I'm about halfway through the XML documentation and will create PR on dev once completed.

### CODE REVIEW

**Comment by willieferguson** [comment]
@akkadotnet/developers - Seen this build failure before? Seems to be related to cluster tests.

**Comment by Aaronontheweb** [comment]
Test failure related to Akka.IO TcpConnections http://petabridge-ci.cloudapp.net/viewLog.html?buildId=1509&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

Earlier there was a multinode test failure, which is related to Akka.Cluster.

**Comment by Aaronontheweb** [comment]
Looks like the tests are passing - yay!

Would it be possible to squash all of these commits onto the Akka.IO branch into a single commit per our [Contribution Guidelines](https://github.com/akkadotnet/akka.net/blob/dev/CONTRIBUTING.md)?

**Comment by willieferguson** [comment]
Created #1142 with squashed commits.

**Pull request closed without merging**
