### PR TITLE
#1676 nuget packages

### PR DESCRIPTION
**Pull request by MrTortoise**
This is just the nuget portion of this issue. Got a nod from Aaron regarding this pull request.

I am working on the rest as well. Bit busy next couple of days and its larger than i expected but itl come.

My first pull request from a feature branch in git like this so if i fubar please explain and ill sort it asap ;)
I think i followed the instructions though!

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@MrTortoise could you rebase?

**Comment by MrTortoise** [comment]
in theory yes.

What do you want me to rebase onto what?
What I have tried to do so far is:
add upstream and merge dev into my origin/dev
I was then expecting to be able to rebase my branch onto that merge ...

Is that correct?
(because when i do the rebase i end up 1 set behind and several ahead so
cannot pull or push)

**Comment by Aaronontheweb** [comment]
https://youtu.be/8UguQzmswC4?t=4m55s - shows how to do it

git rebase -i dev

Need to consolidate these two commits into 1.

**Comment by MrTortoise** [comment]
well i think that has gone wrong.

**Comment by Horusiath** [comment]
If it passes tests, looks good for me.

**Comment by MrTortoise** [comment]
I haven't rebased this successfully due to my ineptness with git.
I think i have got it into a state now where i cannot do so cleanly.

**Comment by Danthar** [comment]
MrTortoise if you follow the instructions in the youtube link @Aaronontheweb posted. It should work.
So git fetch upstream
make sure your in your branch
then git rebase -i upstream/dev and squash your commits.
Now it should have replayed your commits on top of the head of upstream/dev
then git push -f origin

**Comment by MrTortoise** [comment]
as i said above, i have got my fork into a state that i do not know how to recover from

https://github.com/MrTortoise/akka.net

if you want to take a look. I have watched aarons video many times and it doesn't cover the situation i am in.

**Comment by Danthar** [comment]
closing this, since the rebase from Aaron was merged.

**Pull request closed without merging**
