### PR TITLE
Implemented NodeLeavingAndExitingSpec

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Fixed https://github.com/akkadotnet/akka.net/issues/2011

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
Failed here https://github.com/akkadotnet/akka.net/issues/2065

**Comment by Aaronontheweb** [comment]
doh lol! Needs to be rebased again - I think it's all the `.csproj` file that's causing the problem @alexvaluyskiy

**Comment by Aaronontheweb** [comment]
Looks like an issue with this line in `ConvergenceSpec.cs`:

```csharp
RunOn(() =>
            {
                for (var i = 0; i < 5; i++)
                {
                    AwaitAssert(() => ClusterView.Members.Count.ShouldBe(4));
                    AwaitSeenSameState(GetAddress(_config.First), GetAddress(_config.Second), GetAddress(_config.Fourth));
                    MemberStatus(GetAddress(_config.First)).ShouldBe(Akka.Cluster.MemberStatus.Up);
                    MemberStatus(GetAddress(_config.Second)).ShouldBe(Akka.Cluster.MemberStatus.Up);
                    MemberStatus(GetAddress(_config.Fourth)).ShouldBe(Akka.Cluster.MemberStatus.Joining);
                    Assert.True(MemberStatus(GetAddress(_config.Fourth)) == null); // fails
                    // wait and then check again
                    Thread.Sleep(Dilated(TimeSpan.FromSeconds(1)));
                }
            }, _config.First, _config.Second, _config.Fourth);
```

**Comment by Aaronontheweb** [comment]
`Assert.True(MemberStatus(GetAddress(_config.Fourth)) == null);` specifically

**Comment by Aaronontheweb** [comment]
Hmm... just got this to fail locally for me on the dev branch.

**Comment by Aaronontheweb** [comment]
Ah, looks like the line should have been removed in #2067

**Comment by Aaronontheweb** [comment]
Fix: https://github.com/akkadotnet/akka.net/pull/2072

**Comment by alexvaluyskiy** [comment]
Yep, I forgot to do it in the MemberJoined PR

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy same issue as before - rebase (I'm so sorry this is like the 10th time you've had to do this) should bring the fix in:

Failure message for `ConvergenceSpec` again
```
[Node1][FAIL] Akka.Cluster.Tests.MultiNode.ConvergenceWithAccrualFailureDetectorMultiNode1.ConvergenceSpecTests
[Node1][FAIL-EXCEPTION] Type: Xunit.Sdk.TrueException
--> [Node1][FAIL-EXCEPTION] Message: Assert.True() Failure
Expected: True
Actual:   False
--> [Node1][FAIL-EXCEPTION] StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.<A_cluster_of_3_members_must_not_move_a_new_joining_node_to_up_while_there_is_no_convergence>b__6_1() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 179
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 501
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.A_cluster_of_3_members_must_not_move_a_new_joining_node_to_up_while_there_is_no_convergence() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 170
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.ConvergenceSpecTests() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 126
```

**Comment by alexvaluyskiy** [comment]
@Horusiath could restart CI, please?

**Comment by Silv3rcircl3** [comment]
JoinSeedNodeSpecs failed, the spec implemented in this PR passed.

**Pull request merged**
