### PR TITLE
About mono experience #694 

### PR DESCRIPTION
**Pull request by drr00t**
Hi, 

first thank you to start this work. 

Yesterday i made a few changes to build Akka.net solution in Gnome Ubuntu and execute benchmark PinPong.

**This is my development environment:**

 - OS: Gnome Ubuntu 14.04
 - Platform: x64
 - Mono runtime: 3.12 [install instructions here](http://www.mono-%20-%20project.com/docs/getting-started/install/linux/)

**Requirements:**

 - install mono-complete, because we of fsharp and VB dependencies

**What i would like to do**

 - I am using Monodevelop-5.7 of same mono 3.12 installation repository, Monodevelop fail miserably load of project files, maybe i have to use gnu auto tools from Monodevelop to generate MDP project files.
 - cleanup the warnings, we have a lot.
 - run tests, at moment i just build, but execution fail.
 - remove all specific Microsoft platform things.

**Results of my execution, i receive a lot of red numbers...**
----------
Worker threads:         800
OSVersion:              Unix 3.13.0.49
ProcessorCount:         8
ClockSpeed:             0 MHZ
Actor Count:            16
Messages sent/received: 30000000  (3e7)

ActorBase    first start time: 31.91 ms
ReceiveActor first start time: 82.48 ms

            ActorBase                          ReceiveActor
            
Throughput, 	Msgs/sec, 	      Start [ms],       Total [ms],     Msgs/sec,         Start [ms], Total [ms]

         1,  1007000,     215.98,   29982.07,   1292000,      16.56,   23233.40
         5,  3127000,       9.88,    9602.15,   3044000,      13.91,    9867.11
        10,  3967000,      17.19,    7579.67,   3792000,       9.81,    7921.52
        15,  3901000,       9.95,    7699.39,   4300000,      13.88,    6990.62
        20,  4743000,       9.77,    6334.85,   4880000,      21.29,    6168.45
        30,  5116000,       9.72,    5873.58,   4792000,       9.96,    6269.99
        40,  4891000,       7.38,    6141.38,   5087000,      17.17,    5914.76
        50,  5069000,      17.52,    5935.92,   5122000,      13.45,    5871.43
        60,  3606000,      18.82,    8338.38,   4858000,      22.96,    6198.61
        70,  4715000,      11.11,    6373.54,   4073000,      10.10,    7375.21
        80,  5138000,      11.02,    5849.62,   5518000,      21.32,    5467.78
        90,  4509000,       5.52,    6658.93,   4342000,      12.14,    6921.01
       100,  4583000,      12.20,    6558.16,   5047000,       8.89,    5952.80
       200,  2929000,      13.73,   10254.09,   2296000,      24.14,   13086.58
       300,  4267000,      15.07,    7045.76,   4897000,       6.95,    6132.90
       400,  2930000,       8.60,   10244.81,   2354000,      16.06,   12756.04
       500,  2337000,      15.64,   12849.84,   5093000,      10.04,    5900.93
       600,  4195000,      11.33,    7162.91,   2063000,      19.93,   14556.74
       700,  1963000,      36.20,   15315.59,   2701000,      37.67,   11144.27
       800,  2693000,      21.95,   11161.68,   2386000,      48.70,   12622.00
       900,  2180000,      17.57,   13773.82,   2914000,      13.35,   10306.14
Done..

```

### CODE REVIEW

**Comment by rogeralsing** [comment]
Is the output from a VM? 
Release build and no debugger attached?

Looks like we dont scale up well at all as it peaks at 5 mil messages/sec and then jump up and down all over the place.

**Comment by drr00t** [comment]
Hi @rogeralsing

No, is not a VM. follow my hardware configuration, i did forget before, sorry for that.

 - Memory: 8GB
 - Processor: Intel Core i7 CPU Q 720 at 1.6GHz x 8
 - Hard-drive: Kingston SSDNow V+ 200 120GB

To run example before, i follow this steps:
 - build solution with xbuild Akka.sln
 - build benchmark project xbuild /p:Configuration="Debug Mono"  

I did run again build solution and benchmark in release mode this way:

 - xbuild /p:Configuration="Release Mono"  

----------

adriano@merovingian:~/Projects/cs/akka.net/src/benchmark/PingPong$ bin/Release\ Mono/PingPong.exe 
Worker threads:         800
OSVersion:              Unix 3.13.0.49
ProcessorCount:         8
ClockSpeed:             0 MHZ
Actor Count:            16
Messages sent/received: 30000000  (3e7)

ActorBase    first start time: 23.36 ms
ReceiveActor first start time: 56.96 ms

```
            ActorBase                          ReceiveActor
Throughput, Msgs/sec, Start [ms], Total [ms],  Msgs/sec, Start [ms], Total [ms]
         1,  1238000,     291.50,   24517.07,   1217000,       9.64,   24641.86
         5,  3036000,      15.01,    9895.47,   3069000,       9.81,    9784.89
        10,  3453000,      10.84,    8697.97,   3711000,       9.87,    8092.90
        15,  4213000,       9.06,    7129.98,   4228000,      12.03,    7107.29
        20,  4402000,      14.49,    6830.35,   3930000,      10.20,    7644.05
        30,  4585000,      20.53,    6562.62,   4012000,       9.32,    7486.45
        40,  4576000,      13.98,    6569.99,   3529000,      15.48,    8515.53
        50,  2623000,      14.58,   11451.16,   4571000,      18.28,    6581.26
        60,  2241000,      17.15,   13400.91,   5213000,      12.29,    5766.67
        70,  3886000,      13.36,    7732.88,   2651000,      54.79,   11368.09
        80,  3577000,      15.93,    8401.16,   2583000,      22.80,   11635.25
        90,  2822000,      17.70,   10646.06,   2997000,      59.30,   10068.37
       100,  2277000,      31.95,   13204.19,   2427000,      12.71,   12369.13
       200,  2985000,      28.52,   10076.62,   2317000,      26.09,   12971.26
       300,  3049000,      37.79,    9876.63,   3068000,      21.18,    9799.28
       400,  2924000,      11.26,   10269.47,   2486000,      17.33,   12081.68
       500,  2836000,      18.55,   10596.32,   3235000,      12.46,    9284.51
       600,  2325000,      11.30,   12912.17,   2914000,      10.85,   10303.42
       700,  2725000,      69.86,   11076.31,   2803000,      63.93,   10765.58
       800,  2193000,      27.44,   13702.17,   2355000,      17.35,   12751.73
       900,  2574000,      14.86,   11666.52,   2899000,      18.59,   10364.51
Done..

```
----------

I can't speculate anything yet, i going to try make things work on Linux before i start look more deeply.

**Comment by stefansedich** [comment]
I might spin up a fresh vm today and have a look into this too.

Cheers

**Comment by rogeralsing** [comment]
There are pretty much two possible causes for this:

1. The `ConcurrentQueue` used in the Mailbox could cause contention
1. The Mono `ThreadPool` might be less effective than the .NET counterpart (heavily optimized in .NET 4.5)

My guess is that the latter is the cause.
We have a copy of the Mono ConcurrentQueue in our codebase, and if we compile and run Akka.NET with Mono settings on Windows, there is no perf loss.
So unless the lockfree stuff behaves differently on mono than on .NET, that should not be the cause.

The ThreadPool is more likely the cause, as there will be a huge amount of contention on the global work queue. Java Akka had the same problem and thus they introduced the ForkJoinDispatcher.

If that is the reason, I have no idea how we could solve this except than providing our own dedicated threadpool, which is exactly what we have done lately, but our impl is far from optimal and still relies on a global work queue that will cause the same type of contention.

**Comment by drr00t** [comment]
Hi,

Maybe this is the problem [Mono ThreadPool deadlock!] (http://www.mono-project.com/archived/articlethreadpool_deadlocks/), the recomendation is change threads per CPU via mono environment variable MONO_THREADS_PER_CPU. I can't try now, but i can test this at night.

```
export MONO_THREADS_PER_CPU=2000
```

**Comment by rogeralsing** [comment]
I'm able to replicate this behavior on my ubuntu VM.
Numbers looks more stable for me though.
And TBH, I dont know what I can expect from a VM running debug code.

```
Throughput, Msgs/sec, Start [ms], Total [ms],  Msgs/sec, Start [ms], Total [ms]
         1,  1600000,      36.04,   18784.96,   1672000,      13.10,   17952.70
         5,  3055000,      11.75,    9828.87,   3096000,      11.75,    9699.27
        10,  3333000,      11.41,    9011.81,   3327000,      12.92,    9028.57
        15,  3703000,      10.73,    8111.67,   3754000,      13.71,    8004.90
        20,  3875000,      12.05,    7753.28,   3772000,      11.76,    7964.40
        30,  3969000,      17.16,    7575.46,   3860000,      14.62,    7787.18
        40,  3984000,      11.49,    7541.92,   3675000,      11.43,    8174.71
        50,  3658000,      11.43,    8210.96,   3967000,      18.62,    7580.44
        60,  4097000,      13.96,    7335.84,   4178000,      14.97,    7195.86
        70,  4248000,      12.69,    7074.06,   4158000,      16.42,    7230.45
        80,  4357000,      15.06,    6899.92,   4291000,      13.03,    7004.19
        90,  4044000,      11.75,    7430.71,   4057000,      11.67,    7406.41
       100,  4209000,      27.45,    7155.32,   4104000,      11.53,    7320.57
       200,  4244000,      11.34,    7079.50,   4016000,      14.29,    7484.85
       300,  4217000,      11.70,    7125.37,   4123000,      10.87,    7286.24
       400,  4247000,      11.55,    7075.26,   4103000,      12.57,    7324.44
       500,  3277000,      31.07,    9185.04,   3208000,      14.93,    9364.29
       600,  3289000,      19.17,    9139.68,   3294000,      14.02,    9120.49
       700,  3677000,      23.82,    8181.50,   3699000,      15.86,    8126.09
       800,  3724000,      22.37,    8076.61,   3989000,      15.61,    7536.52
       900,  3909000,      11.80,    7685.26,   4158000,      14.79,    7230.30
```

But it very much looks like there is little or no gain when Dispatcher throughput setting is changed.
(the number that decides how many messages to process per mailbox run)

with a setting of "1" the framework schedules a new task to the threadpool per message sent.
So this is expected to be slow.
but with a setting of "900", the framework will process 900 messages at once, for each scheduled mailbox run.

Im not sure what to make of these numbers right now.

**Comment by rogeralsing** [comment]
This is from 2011, but... https://bugzilla.xamarin.com/show_bug.cgi?id=1653 "ThreadPool QueueUserWorkItem is slow"

**Comment by alistair** [comment]
does executing with mono --server help?

I believe this does some optimizations,  one of which is about threading and tasks ( sorry really can't remember the details ).

**Comment by rogeralsing** [comment]
If I run the whole thing in the terminal, w/o running form monodevelop, its not that bad TBH.
starting with `mono --server` it peaks at 8 mil messages per second and is fairly stable perf wise.

```
Throughput, Msgs/sec, Start [ms], Total [ms],  Msgs/sec, Start [ms], Total [ms]
         1,  2440000,       9.82,   12303.07,   2454000,       5.52,   12225.83
         5,  4904000,       4.84,    6122.14,   4638000,       8.60,    6477.22
        10,  6458000,       6.30,    4651.35,   5790000,       4.52,    5186.35
        15,  6621000,       4.73,    4536.57,   6462000,       7.69,    4650.07
        20,  6576000,       7.30,    4570.04,   6558000,       4.58,    4578.67
        30,  7095000,       6.98,    4235.72,   7407000,       7.56,    4057.60
        40,  7097000,      13.12,    4240.17,   7057000,      10.75,    4262.37
        50,  7436000,      13.39,    4047.41,   7285000,       7.54,    4126.26
        60,  7470000,       4.92,    4020.97,   7159000,       5.06,    4195.60
        70,  7097000,      12.23,    4239.61,   8152000,       3.91,    3684.59
        80,  7475000,      11.05,    4024.58,   7702000,       6.10,    3901.38
        90,  7292000,       7.34,    4121.63,   6640000,       7.77,    4526.58
       100,  7361000,      20.52,    4096.39,   6808000,       4.82,    4411.33
       200,  7702000,      12.65,    3908.60,   7618000,       4.49,    3943.27
       300,  7649000,       4.98,    3927.76,   7295000,       9.22,    4121.92
       400,  7414000,       4.81,    4051.78,   7812000,       7.99,    3848.21
       500,  7260000,      13.01,    4145.55,   7845000,       8.20,    3832.81
       600,  7676000,       7.86,    3916.44,   7313000,      18.89,    4121.34
       700,  7110000,       4.82,    4224.61,   7228000,       5.89,    4156.56
       800,  8006000,      16.56,    3763.95,   6443000,       4.88,    4661.10
       900,  7416000,       4.77,    4050.63,   6469000,       4.12,    4642.01
```

That's not too shabby for a VM.
.NET + native machine is still 4 times faster, but it's not horrific imo.

**Comment by stefansedich** [comment]
I did a run under mono on windows and did see some different figures than
.net under windows, need to dig into it a bit more with my ubuntu vm and
mono on windows but my holidays have been getting in the way :p!

**Comment by Aaronontheweb** [comment]
I ended up implementing most of these fixes in my latest PR for Mono remoting. Going to close this one.

**Pull request closed without merging**
