### PR TITLE
UnityDependencyResolver and example project

### PR DESCRIPTION
**Pull request by jwconway**
Ive recreated this as i made a mess of the previous one :S

### CODE REVIEW

**Comment by jwconway** [comment]
@jcwrequests this is the PR for the `UnityDependencyResolver` now. I had to close the last PR as i messed up the merge

**Comment by jcwrequests** [comment]
@jwconway I just looked it over on GitHub. It's been a long time since I have used unity. It looks like unity creates a new instance per resolve by default so you don't need to worry about lifetime issues. Is that right?

**Comment by jwconway** [comment]
That's right. Unity uses the `TransientLifetimeManager` by default. Which creates a new instance in every call to `Resolve`

**Comment by jcwrequests** [comment]
@jwconway Everything looks good to me. The lifetime scope is very important so unity is got you covered by default so no worries there.

 Jay is your avatar pic from a movie?

**Comment by jwconway** [comment]
That's great! 

Ha, it's character from a program that I used to enjoy. His name is Terry Tibbs

https://m.youtube.com/watch?v=MjnhHKIKqJA

**Comment by jcwrequests** [comment]
@jwconway :)

**Pull request merged**
