### PR TITLE
Update docs on Autofac wiring to use new extension method

### PR DESCRIPTION
**Pull request by caioproiete**
Update docs on Autofac wiring to use the new extension method, now that https://github.com/akkadotnet/Akka.DI.AutoFac/pull/16 has been merged.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@caioproiete don't we need to do a new release of the Autofac library first in order for this example to work?

**Comment by caioproiete** [comment]
@Aaronontheweb Correct! I should have mentioned that in the PR description.

**Comment by Aaronontheweb** [comment]
@caioproiete this is going up on NuGet any minute: https://github.com/akkadotnet/Akka.DI.AutoFac/releases/tag/v1.3.9

**Comment by caioproiete** [comment]
@Aaronontheweb Awesome! Cheers for shipping it so quick!!

**Pull request merged**
