### PR TITLE
[api-docs] Added TBD placeholders for Akka.csproj

### PR DESCRIPTION
**Pull request by sean-gilliam**
This PR is the initial commit for #2407. It adds placeholders for missing/incomplete xmldoc comments.

[1/23]

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Looks like due to the old commit age (7 days ago) on here, CI system didn't pick it up

Please follow these steps to update it http://stackoverflow.com/a/31540373/377476

**Comment by Danthar** [comment]
oh, it already has conflicts :P @Aaronontheweb would simply pushing a new commit resolve the 'old commit age' issue as well ?

**Comment by sean-gilliam** [comment]
Yea I think it happens whenever you squash commits. It looks like it takes the date of the commit you squash everything down into. And I did a lot of squashing :)

**Comment by Danthar** [comment]
Ah, well that would mean you could add another commit, and squash to that commit. Interesting.
Or use the SO link that Aaron posted ofc :)

**Comment by sean-gilliam** [comment]
Alright fixed the conflict and updated the timestamp. Let the tests commence :)

**Comment by Danthar** [comment]
Never knew that adding comments could cause performance problems :P

**Pull request merged**
