### PR TITLE
Add TeamCity formatting option to MultiNode Test Runner

### PR DESCRIPTION
**Pull request by heynickc**
Work in progress for adding TeamCity formatting to MNTR.  Putting PR up so to be able to configure the command flags in CI to be able to see the results in TeamCity.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@heynickc No TC formatting as far as I can tell....

```
[22:40:33]	[MultiNodeTests] [INFO][6/1/2017 10:40:32 PM][Thread 0013][[akka://TestRunnerLogging/user/TcpLogger#692185559]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/selectors/$a/6#1730900206]
[22:40:33]	[MultiNodeTests] 
[22:40:33]	[MultiNodeTests] [INFO][6/1/2017 10:40:32 PM][Thread 0013][[akka://TestRunnerLogging/user/TcpLogger#692185559]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/selectors/$a/8#1197697570]
[22:40:33]	[MultiNodeTests] 
[22:40:33]	[MultiNodeTests] [INFO][6/1/2017 10:40:32 PM][Thread 0021][[akka://TestRunnerLogging/user/TcpLogger#692185559]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/selectors/$a/7#1240929591]
[22:40:33]	[MultiNodeTests] 
[22:40:41]	[MultiNodeTests] [NODE1:first][10:40 PM]: SPEC PASSED: Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec.RemoteRoundRobinSpecs PASS
[22:40:41]	[MultiNodeTests] [INFO][6/1/2017 10:40:40 PM][Thread 0020][[akka://TestRunnerLogging/user/TcpLogger#692185559]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/selectors/$a/5#1925210578]
[22:40:41]	[MultiNodeTests] 
[22:40:41]	[MultiNodeTests] [NODE1:first][10:40 PM]: SPEC PASSED: Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec passed.
[22:40:41]	[MultiNodeTests] [NODE2:second][10:40 PM]: SPEC PASSED: Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec passed.
[22:40:41]	[MultiNodeTests] [NODE3:third][10:40 PM]: SPEC PASSED: Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec passed.
[22:40:41]	[MultiNodeTests] [NODE4:fourth][10:40 PM]: SPEC PASSED: Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec passed.
[22:40:41]	[MultiNodeTests] [RUNNER][6/1/2017 10:40:40 PM][INFO][Akka.MultiNodeTestRunner.Shared]: Waiting 3 seconds for all messages from all processes to be collected.
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: Spec completed.
[22:40:44]	[MultiNodeTests] [RUNNER][6/1/2017 10:40:43 PM][INFO][Akka.MultiNodeTestRunner.Shared]: Starting test RemoteRandomSpecs
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: Beginning spec Akka.Remote.Tests.MultiNode.Router.RemoteRandomSpec.RemoteRandomSpecs on 4 nodes
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: Results for Akka.Remote.Tests.MultiNode.Router.RemoteRoundRobinSpec.RemoteRoundRobinSpecs
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: Start time: 6/1/2017 10:40:13 PM
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]:  --> Node 1:first : PASS [00:00:27.1130585 elapsed]
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]:  --> Node 2:second : PASS [00:00:19.3160907 elapsed]
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]:  --> Node 3:third : PASS [00:00:19.2981188 elapsed]
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]:  --> Node 4:fourth : PASS [00:00:19.3430501 elapsed]
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: End time: 6/1/2017 10:40:43 PM
[22:40:44]	[MultiNodeTests] [RUNNER][10:40 PM]: FINAL RESULT: PASS after 00:00:30.2514441.
[22:40:44]	[MultiNodeTests] [RUNNER][6/1/2017 10:40:43 PM][INFO][Akka.MultiNodeTestRunner.Shared]: Started node 1 : first on pid 8660
[22:40:44]	[MultiNodeTests] [RUNNER][6/1/2017 10:40:43 PM][INFO][Akka.MultiNodeTestRunner.Shared]: Started node 2 : second on pid 7848
[22:40:44]	[MultiNodeTests] Writing test state to: D:\work\d26c9d7f36545acd\bin\multinode\Akka.Remote.Tests.MultiNode-636319535821399791.json
[22:40:44]	[MultiNodeTests] Writing test state to: D:\work\d26c9d7f36545acd\bin\multinode\Akka.Remote.Tests.MultiNode-636319535821399791.html
[22:40:44]	[MultiNodeTests] [RUNNER][6/1/2017 10:40:43 PM][INFO][Akka.MultiNodeTestRunner.Shared]: Started node 3 : third on pid 8136
```

**Comment by heynickc** [comment]
@Aaronontheweb yes, I hadn't passed the flag into the TeamCity build step yet

**Comment by Danthar** [comment]
@heynickc is this one done ? / ready for review ?

**Comment by heynickc** [comment]
@Danthar Yes, it is ready, and will probably help with #2759.  Thanks.

**Pull request merged**
