### PR TITLE
ActorTaskScheduler QueueTask for LongRunning #1410

### PR DESCRIPTION
**Pull request by Aaronontheweb**
For @Zetanova

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@JeffCyr mind taking a look at this issue while you're at it?

**Comment by JeffCyr** [comment]
@Aaronontheweb Sure,

I think the TaskCreationOptions got mixed up here.

TaskCreationOptions.LongRunning is a hint that means:
> Hey scheduler, I'm going to send you a task that may take quite some time to complete, you may want to execute my task on a dedicated thread instead of the ThreadPool to prevent a starvation of your precious threads.

The changes proposed by @Zetanova breaks the ActorTaskScheduler contract (which is to execute tasks in the actor context) by executing the `LongRunning` task with `TaskScheduler.Default` (and potentially starving the ThreadPool) outside the actor context (so the task may execute concurrently with other tasks or with other Receives, this is bad).

Concerning the AttachedToParent option in @Zetanova's commit, I think the flag is mixed up as well. I tried to explain this one in issue #1346. This flag is poorly documented and this is probably due to the fact that it is generally harmful or useless. The proposed change would allow concurrent execution of tasks in the actor context when this flag is specified, so it is bad.

I implemented the LongRunning flag in the refactoring of ActorTaskScheduler included in PR #1484, can you validate that it address your issue appropriately?

**Comment by rogeralsing** [comment]
Completely agree with @JeffCyr, this PR breaks actor concurrency due to `TaskScheduler.Default`

**Comment by JeffCyr** [comment]
I just realized that my implementation of the LongRunning task is useless in PR #1484. I'm starting a thread just to send a msg in the actor mailbox, the task will still be executed on the actor's IScheduler.

I think there is no fix to this issue, the ActorTaskScheduler cannot satisfy the LongRunning hint by design.

Do you think we should throw an exception and refuse to execute LongRunning tasks on an ActorTaskScheduler? I'm not sure what is the best trade-off here, it could work to just ignore the flag too.

**Comment by rogeralsing** [comment]
I think ignoring the flag would be the most correct thing to do, as that is inline with how other schedulers work as you describe.

The fact that actors shouldn't do long running tasks is something that developers/users of Akka.NET need to learn anyway, as the same apply to the synchronous message pipeline.

**Comment by rogeralsing** [comment]
Closing as this breaks actor concurrency..

**Pull request closed without merging**
