### PR TITLE
getting the example to work when you run it

### PR DESCRIPTION
**Pull request by voltcode**
actual fix proposed by @Silv3rcircl3 on Gitter today - I was merely the one to stumble on this problem

### CODE REVIEW

**Comment by Silv3rcircl3** [comment]
@voltcode I would actually prefer the other example I posted in Gitter. It gives an better overview how you can use `Source.Tick`  in combination with other stages. Also, since this is a console application, we should use `Console.ReadLine()` to block at the end. 

```csharp
        static void Main(string[] args)
        {
            Run();
            Console.ReadLine();
        }

        static void Run()
        {
            var oneSecond = TimeSpan.FromSeconds(1);

            using (var system = ActorSystem.Create("system"))
            using (var materializer = system.Materializer())
            {
                var source = Source.Tick(oneSecond, oneSecond, "hello");
                var flow = Flow.Create<string>()
                    .Select(s => s.ToUpper())
                    .Intersperse(", ");
                var sink = Sink.ForEach<string>(Console.WriteLine);

                var t = source.Via(flow).ToMaterialized(sink, Keep.Both).Run(Materializer);
                var cancelTickSource = t.Item1;
                var foreachTask = t.Item2;

                foreachTask = foreachTask.ContinueWith(_ => Console.WriteLine("Foreach finished"));

                cancelTickSource.CancelAfter(TimeSpan.FromSeconds(5));

                foreachTask.Wait(TimeSpan.FromSeconds(10));

                Console.WriteLine("Task finished");
            }
        }
```

**Comment by Silv3rcircl3** [comment]
@voltcode could you update this PR ?

**Comment by voltcode** [comment]
Yes, sorry for the delay. I'll do it in the coming week

**Comment by alexvaluyskiy** [comment]
@voltcode Please, update your PR

**Comment by Silv3rcircl3** [comment]
@voltcode thanks!

**Pull request merged**
