### PR TITLE
Remove an unnecessary DeadLetter at GracefulStop. #2157

### PR DESCRIPTION
**Pull request by veblush**

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
@veblush Looks good, but, It is a bad idea to change standard Scala specs if we want to verify a new bug. The better idea is - create a new test with name like "GracefulStopSupport_must_not_send_unnecessary_Deadletter_bug_2157"
And squash this PR into one commit, please

**Comment by Aaronontheweb** [comment]
@veblush I agree with @alexvaluyskiy. Could you revert the original spec to as it was and then add a new spec to that file, as @alexvaluyskiy suggested?

**Comment by veblush** [comment]
Oh good point. I didn't know that. I'll take it.

**Comment by veblush** [comment]
Oh i failed to update this PR to have squash one commit. I create new PR and close this one.

**Pull request closed without merging**
