### PR TITLE
Patch to Issues with DI Support #706

### PR DESCRIPTION
**Pull request by jcwrequests**
Patch to Issues with DI Support #706

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
MSBuild failed: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=264&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild

**Comment by nvivo** [comment]
I'm not sure if this is planned or not, but since the DI producer is registered as an extension inside the actor system, shouldn't the ActorOf methods  (both from ActorSystem and children Actors) automatically support it internally somehow?

Having to [extract the DIExt](https://github.com/akkadotnet/akka.net/pull/733/files#diff-5cfcb16334e195be265545548eb09aa1R62) in every actor to create children seems too low level for general use.

**Comment by jcwrequests** [comment]
@nvivo I based my implementation off the jvm side so it should theoretically work the same. Have you tried using the contrib and testing if that would work? Either way send me some examples and I will take a look.

**Comment by nvivo** [comment]
@jcwrequests, I don't know much about the JVM implementation, so I'm sorry if the question is out of place. I was looking at the examples you provided in this PR, and inside an actor you do:

```cs
var producer = Context.System.GetExtension<DIExt>();
Context.ActorOf(producer.Props("TypedWorker"));
```

This actor must know a DI framework is being used and code accordingly, which seems strange as the DI should be "transparent" to the application of code.

Since the extension is registered inside the ActorSystem, shouldn't be able to just call `System/Context.ActorOf<TypedWorker>()` and that would use the DI extension internally if registered?

I'm currently using the contrib from nuget with Autofac, but it seems this part didn't change in this PR.

**Comment by jcwrequests** [comment]
@nvivo I will take a look as soon as I can to see what can be done. There maybe some changes that need to occur to Akka itself. My contrib was using the extensibility extensions with the framework. This maybe something that could be solved with an extension method. Either way I will take a look.

**Comment by jcwrequests** [comment]
@nvivo The problem is with the extension method which is not taking into account the possibility of DI being used. That was not something I coded but I think it is worth looking at seeing if there is a way around the issue. @aaronontheweb @hcanber @rogeralsing what do you guys think?

**Comment by Aaronontheweb** [comment]
> Since the extension is registered inside the ActorSystem, shouldn't be able to just call System/Context.ActorOf<TypedWorker>() and that would use the DI extension internally if registered?

@nvivo that's not how actor system extensions work. They're meant to be called directly.

The actor construction pipeline, a special type of extension does work this way however - we don't have detailed docs for it but we do have a description of its API here: https://github.com/akkadotnet/akka.net/releases/tag/v0.8

It's configurable and can perform special initialization and shutdown logic on actors. It's how stashes get created and destroyed currently. Th'at's something worth investigating cc @jcwrequests

**Comment by nvivo** [comment]
@Aaronontheweb, I'm not questioning anything related to the how the extensions or Akka works. I'm sorry if that was the impression I gave, this was really not my intention.

@jcwrequests, please it was just a question, don't bother trying to change anything. I'm under the impression that for this to work, Akka would need to recognize DI directly, so it's really transparent to the developer. In theory, if DI is supported we should be able to do something like `Context.ActorOf<IServiceInterface>()`, but that's a long shot and I'm just brainstorming here.

I need to take a look at how the JVM works for this, but I'd be glad to help with anything.

**Comment by jcwrequests** [comment]
@nvivo I think you have a valid point that may be solvable and help everyone using the extension. Don't worry I would spend to much time it's an interesting problem.

**Comment by Aaronontheweb** [comment]
>  I'm not questioning anything related to the how the extensions or Akka works. I'm sorry if that was the impression I gave, this was really not my intention.

No worries man - was just trying to educate you on how they work. No need to apologize.

**Comment by jcwrequests** [comment]
@Aaronontheweb @nvivo Just made the changes and added an extension method and adapter in the core to make created child actors with DI simple.

**Comment by rogeralsing** [comment]
@jcwrequests could you fix the current conflicts and prefferably squash to a single commit?

**Comment by jcwrequests** [comment]
@rogeralsing Not sure if squashing at this time will screw anything up. Sorry about the conflicts for some reason I could not get my fork's upstream to merge properly so I was not seeing the rename changes made to ConsistentHashable.

**Comment by jcwrequests** [comment]
@rogeralsing I see there are some new conflicts I will look into it.

**Comment by rogeralsing** [comment]
@akkadotnet/developers should we pull this in?
Should we squash the commits? anyone that is comfortable with git that can assist on that?

**Comment by Aaronontheweb** [comment]
Replacing this PR with #775

**Pull request closed without merging**
