### PR TITLE
Some documentation fixes

### PR DESCRIPTION
**Pull request by nvivo**
Convert examples to C#, removed some references of JVM and Scala.

### CODE REVIEW

**Comment by nvivo** [comment]
While modifying the "Working with Actors", there are many places saying "Don't forget the second argument on Tell(....)!!!", but it seems Akka.NET by default passes the Self inside the actor. I wonder if this should be removed from most examples.

Maybe leave it only if explaining explicitly that something that requires it, like a child actor answering on behalf of the parent.

**Comment by rogeralsing** [comment]
Looks great, thanks!

**Comment by rogeralsing** [comment]
Yes, the sender in a call to `.Tell` is optional, it will be resolved from the current context.
So it can be omitted, and I think your suggestion is good, leave it in if there is an Ask/ReqResp type of communication going on.

**Comment by nvivo** [comment]
@rogeralsing, I'll keep translating and fixing things first, then I'll go back and try to improve the examples.

**Comment by rogeralsing** [comment]
:+1:

**Pull request merged**
