### PR TITLE
Akka.Streams: fixed sln file

### PR DESCRIPTION
**Pull request by Horusiath**
This PR should fix build step for akka-streams branch.

### CODE REVIEW

**Comment by Danthar** [comment]
Is it expected for the tests to fail on this? Since its the akka-streams branch. If so, i'd say merge it. Because it does fix akka-streams not building.

**Comment by Aaronontheweb** [comment]
@Danthar some of these test failures can probably be fixed with a rebase on `dev` - but the others are all failures related to Streams. Those specs should be passing.

**Comment by Silv3rcircl3** [comment]
@aaronontheweb most of the test aren't passing, at least the ones I ported for example mostly all IO specs in the other PR , which is fine for the moment, we will fix them laiter

**Comment by Aaronontheweb** [comment]
ok, I'll take the status check requirement off

**Pull request merged**
