### PR TITLE
Add optional PipeTo completion handlers

### PR DESCRIPTION
**Pull request by emilingerslev**
Added an optional success and failure handler to PipeTo, to simplify use of Tasks. PipeTo falls back to original behavior either handler isn't supplied.

Some examples:

```csharp
Context.ActorSelection("akka.tcp://remote@remote:1234/user/PingActor")
    .ResolveOne(TimeSpan.FromSeconds(1))
    .PipeTo(Self,
        success: x => new PleasePing(x),
        failure: e => new TryAgainLater(e.ToString()));
        
actorRef.Ask<Pong>(new Ping())
    .PipeTo(Self,
        failure: e => new TryAgainLater(e.ToString()));
```

### CODE REVIEW

**Comment by Horusiath** [comment]
:+1:

**Comment by rogeralsing** [comment]
This is great!!

**Comment by emilingerslev** [comment]
Glad you like it! It works perfect in what I've working on.

I'm not sure though how much is allowed in the `Task.ContinueWith` handling? Can you say something like its best practice to only do conversions to new message types or would something like this be alright?:

```csharp
Context.ActorSelection("akka.tcp://remote@remote:1234/user/PingActor")
    .ResolveOne(TimeSpan.FromSeconds(1))
    .PipeTo(Self,
        success: x => x.Ask<Pong>(new Ping()),
        failure: e => new TryAgainLater(e.ToString()));
```

I think the syntax becomes more dirty and harder to read, but it would be great with some guidelines.
I would gladly help updating the docs too.

**Comment by emilingerslev** [comment]
BTW, do you know why the build has gone rogue like?

**Comment by Aaronontheweb** [comment]
Reverted this- please add unit tests and resubmit

**Comment by emilingerslev** [comment]
Alright, I'll look into creating a few tests for this

**Comment by Aaronontheweb** [comment]
Thanks!

**Comment by emilingerslev** [comment]
Resubmitted it as #1383

**Pull request merged**
