### PR TITLE
[WIP] DotNettyTransport

### PR DESCRIPTION
**Pull request by Aaronontheweb**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Haven't removed Helios yet - wanted to collect some data from the build server.

Note: this is going into a separate version branch independent of `dev` because the `DotNettyTransport` is going to need to be part of a minor version release due to breaking changes with the existing `HeliosTcpTransport`. I might be able to eliminate those with a little finagling inside Helios but I can't confirm yet.

**Comment by annymsMthd** [comment]
I'll check this out when I get to work

**Comment by Aaronontheweb** [comment]
Looks like I introduced a bug inside `GracefulStop`, and the stress test revealed some initialization issues with the transport. Failure to block reads probably.

**Comment by Aaronontheweb** [comment]
Hey @maxim-s, @alexpantyukhin told me that you want to take on reviewing this one. Message me if you need any help with the DotNetty part of it.

**Comment by Aaronontheweb** [comment]
@bobanco is someone else who could help review this - I know he knows DotNetty well.

**Comment by bobanco** [comment]
@Aaronontheweb i will take a look trough this weekend, am pretty busy these days.

**Comment by maxim-s** [comment]
looks good

**Comment by JeffCyr** [comment]
The Throughput test in this code is not working with the DotNetty transport
https://github.com/JeffCyr/Akka.Remote.Transport.Streams/blob/dev/src/StreamTransportSample/Program.cs

The latency test is working so something is probably breaking when there is concurrent writes on a connection.

**Comment by Danthar** [comment]
Whats the status of this ?

**Pull request closed without merging**
