### PR TITLE
NuGet packaging for MNTR (Windows/.NET 4.5.2)

### PR DESCRIPTION
**Pull request by heynickc**
Initial work to get MNTR Test Runner .NET 4.5.2/win7-64x packaged using `dotnet pack`.  Requires the use of a custom .nuspec files so metadata is hard-coded into it right now.  This is just to get a working package ready for release, although later we should work on substituting metadata into the .nuspec.  

Using dotnet-pack simply on the .csproj file only outputs the .exe into the lib/net452 folder, without dependent dlls.  This is why I had to use a .nuspec file to include all dependencies in the .nupkg.

Will use the same build step to output the `netcoreapp1.1` version of the runner.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Arkatufus @heynickc houston we have a problem 

```
[22:38:45]	[MultiNodeTests] 
[22:38:45]	[MultiNodeTests] 
[22:38:45]	[MultiNodeTests] 
[22:38:45]	[MultiNodeTests] 
[22:38:45]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: Unhandled Exception: 
[22:38:45]	[MultiNodeTests] 
[22:38:45]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: 
[22:38:46]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:46]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:46]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:46]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:46]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:46]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:50]	[MultiNodeTests] 
[22:38:51]	[MultiNodeTests] Unhandled Exception: 
[22:38:51]	[MultiNodeTests] 
[22:38:51]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:51]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:51]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:51]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:51]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:51]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:51]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:51]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:51]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:51]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:51]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:51]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:51]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:54]	[MultiNodeTests] 
[22:38:54]	[MultiNodeTests] Unhandled Exception: 
[22:38:54]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:54]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:54]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:54]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:54]	[MultiNodeTests] Unhandled Exception: 
[22:38:54]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:54]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:54]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:54]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:54]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:54]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:54]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:54]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:54]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:57]	[MultiNodeTests] 
[22:38:57]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:57]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:57]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:57]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:57]	[MultiNodeTests] 
[22:38:57]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:57]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:57]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:57]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:38:57]	[MultiNodeTests] 
[22:38:57]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:38:57]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:38:57]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:38:57]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:38:57]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:00]	[MultiNodeTests] 
[22:39:00]	[MultiNodeTests] 
[22:39:00]	[MultiNodeTests] 
[22:39:00]	[MultiNodeTests] Unhandled Exception: 
[22:39:00]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:00]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:00]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:00]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:00]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:00]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:00]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:00]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:00]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:00]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:00]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:00]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:01]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:01]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:01]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:01]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:01]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:01]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:01]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:01]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:01]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:01]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:01]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:01]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:04]	[MultiNodeTests] 
[22:39:04]	[MultiNodeTests] 
[22:39:04]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:04]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:04]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:04]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:04]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:04]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:04]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:04]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:04]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:04]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:04]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:04]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:07]	[MultiNodeTests] 
[22:39:07]	[MultiNodeTests] 
[22:39:07]	[MultiNodeTests] Unhandled Exception: 
[22:39:07]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:07]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:07]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:07]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:07]	[MultiNodeTests] 
[22:39:07]	[MultiNodeTests] Unhandled Exception: Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:07]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:07]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:07]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:07]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:07]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:07]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:07]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:07]	[MultiNodeTests] System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:07]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:07]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:07]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:07]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:10]	[MultiNodeTests] 
[22:39:10]	[MultiNodeTests] Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'multinode.test-assembly'  Key being added: 'multinode.test-assembly'
[22:39:10]	[MultiNodeTests]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
[22:39:10]	[MultiNodeTests]    at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0()
[22:39:10]	[MultiNodeTests]    at System.Lazy`1.CreateValue()
[22:39:10]	[MultiNodeTests]    at System.Lazy`1.LazyInitValue()
[22:39:10]	[MultiNodeTests]    at Akka.NodeTestRunner.Program.Main(String[] args)
[22:39:10]	[MultiNodeTests] 
[22:39:10]	[MultiNodeTests] 
```

From the build log

**Comment by Arkatufus** [comment]
working on it

**Comment by heynickc** [comment]
This PR now includes publishing the .NET Core version as well

**Comment by heynickc** [comment]
Changed to WIP temporarily as we're going to replace some output-folder locations to use the output of dotnet-publish for the standalone .NET Core runner

**Comment by heynickc** [comment]
This will be ready for merge after CI passes

**Comment by heynickc** [comment]
Also removing `multi` feature added by @Arkatufus here due to the inability to guarantee x-plat compatibility due to issues with serialization between netcoreapp1.1 and net45

**Pull request merged**
