### PR TITLE
NoSender is changed to null (Fixes for NoSender serialization bugs)

### PR DESCRIPTION
**Pull request by ssoshchepkov**
Fixes for `NoSender` actor reference serialization bugs described in #1036.
`NoSender` actor reference is changed to `null` as discussed in #1037.

### CODE REVIEW

**Comment by rogeralsing** [comment]
There seems to be some side effect to this.
Possibly just an error in some spec

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 202
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`2 assert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 166
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Predicate`1 isMessage, Nullable`1 timeout, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 57
   at Akka.Testkit.Tests.NoImplicitSenderSpec.When_Not_ImplicitSender_then_testActor_is_not_sender() in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit.Tests\NoImplicitSenderSpec.cs:line 22
```

**Comment by ssoshchepkov** [comment]
Yes, in this spec actor sends `NoSender` as a message:
```    
public class NoImplicitSenderSpec : AkkaSpec, INoImplicitSender
    {
        [Fact]
        public void When_Not_ImplicitSender_then_testActor_is_not_sender()
        {
            var echoActor = Sys.ActorOf(c => c.ReceiveAny((m, ctx) => TestActor.Tell(ctx.Sender)));
            echoActor.Tell("message");
            ExpectMsg<IActorRef>(actorRef => Equals(actorRef, ActorRefs.NoSender));
        }

    }
```
`TestActor.Tell(ctx.Sender)` sends `null` and then `message.GetType()` for this message causes `NullReferenceException`:
```
_assertions.Fail(failMessage2, typeof(T), message.GetType(), message, hint ?? "", sender);
```

**Comment by rogeralsing** [comment]
Could you mark the failing test with skip attribute?
Just so we dont merge failing tests that confuse others before the test itself is cleaned up or removed

**Comment by rogeralsing** [comment]
Thanks!

**Pull request merged**
