### PR TITLE
Test runner improvements

### PR DESCRIPTION
**Pull request by annymsMthd**
Opening pull request to test on CI. This may not be ready for merge and should be reviewed.

### CODE REVIEW

**Comment by rogeralsing** [comment]
Any ideas on how to fix these?

```
  Build failure reason MSB3073: D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): The command ""D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe" install "D:\BuildAgent\work\49b164d63843fb4\src\contrib\dependencyInjection\Akka.DI.CastleWindsor\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "D:\BuildAgent\work\49b164d63843fb4\src\ "" exited with code 1.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '0.1.32.1' of package 'slf4net'.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '3.2.2.0' of package 'Ninject'.
  Build failure reason MSB3073: D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): The command ""D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe" install "D:\BuildAgent\work\49b164d63843fb4\src\contrib\loggers\Akka.Logger.slf4net\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "D:\BuildAgent\work\49b164d63843fb4\src\ "" exited with code 1.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '3.5.2' of package 'Autofac'.
  Build failure reason MSB3073: D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): The command ""D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe" install "D:\BuildAgent\work\49b164d63843fb4\src\contrib\dependencyInjection\Akka.DI.AutoFac\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "D:\BuildAgent\work\49b164d63843fb4\src\ "" exited with code 1.
  Build failure reason Building D:\BuildAgent\work\49b164d63843fb4\src\Akka.sln failed with exitcode 1.
  Build failure reason MSB3073: D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): The command ""D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe" install "D:\BuildAgent\work\49b164d63843fb4\src\contrib\dependencyInjection\Akka.DI.Ninject\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "D:\BuildAgent\work\49b164d63843fb4\src\ "" exited with code 1.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '2.4.1.521' of package 'Google.ProtocolBuffers'.
  Build failure reason MSB3073: D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): The command ""D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.exe" install "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "D:\BuildAgent\work\49b164d63843fb4\src\ "" exited with code 1.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '3.3.0' of package 'Castle.Core'.
  Build failure reason : D:\BuildAgent\work\49b164d63843fb4\src\.nuget\NuGet.targets(100,9): Unable to find version '3.3.0' of package 'Castle.Windsor'.
```

**Comment by Aaronontheweb** [comment]
Sacrifice a chicken and turn a rainstick upside down - looks like NuGet crapped out when the DI packages were trying to load their dependencies.

**Comment by Aaronontheweb** [comment]
So nevermind - looks like the build engine is borked at the moment. XUnit isn't even starting to run.

**Comment by Aaronontheweb** [comment]
From the build log

```
[Step 1/1] Test Settings: Default Test Settings
[18:32:44][Step 1/1] Using XUnit runner: D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe
[18:32:45][Step 1/1] Task: xUnit D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Cluster.Tests\bin\Release\Akka.Cluster.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.FSharp.Tests\bin\Release\Akka.FSharp.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.MultiNodeTestRunner\bin\Release\Akka.Cluster.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.MultiNodeTestRunner.Shared.Tests\bin\Release\Akka.MultiNodeTestRunner.Shared.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.NodeTestRunner\bin\Release\Akka.Cluster.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.TestKit.Tests\bin\Release\Akka.Persistence.TestKit.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.Tests\bin\Release\Akka.Persistence.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.TestKit.Tests\bin\Release\Akka.Remote.TestKit.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests\bin\Release\Akka.Remote.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit.Tests\bin\Release\Akka.TestKit.Tests.dll, D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\bin\Release\Akka.Tests.dll
[18:32:45][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Cluster.Tests\bin\Release\Akka.Cluster.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.FSharp.Tests\bin\Release\Akka.FSharp.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.MultiNodeTestRunner\bin\Release\Akka.Cluster.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.MultiNodeTestRunner.Shared.Tests\bin\Release\Akka.MultiNodeTestRunner.Shared.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.NodeTestRunner\bin\Release\Akka.Cluster.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.TestKit.Tests\bin\Release\Akka.Persistence.TestKit.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.Tests\bin\Release\Akka.Persistence.Tests.dll" "/teamcity" 
[18:32:46][Step 1/1] error: file not found: /teamcity
[18:32:46][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.TestKit.Tests\bin\Release\Akka.Remote.TestKit.Tests.dll" "/teamcity" 
[18:32:47][Step 1/1] error: file not found: /teamcity
[18:32:47][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests\bin\Release\Akka.Remote.Tests.dll" "/teamcity" 
[18:32:47][Step 1/1] error: file not found: /teamcity
[18:32:47][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit.Tests\bin\Release\Akka.TestKit.Tests.dll" "/teamcity" 
[18:32:47][Step 1/1] error: file not found: /teamcity
[18:32:47][Step 1/1] D:\BuildAgent\work\49b164d63843fb4\src\packages\FAKE\xunit.runner.console\tools\xunit.console.exe "D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\bin\Release\Akka.Tests.dll" "/teamcity" 
```

Looks like the "/teamcity" flag getting passed in is being treated like a file >_<

**Comment by annymsMthd** [comment]
yup. I'm investigating and it looks like that might be coming from fake

**Comment by annymsMthd** [comment]
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/XUnitHelper.fs line 79

**Comment by annymsMthd** [comment]
Almost there. The build works and runs the tests. It looks like the RoutingSpec race is still there. Should I squash these commits now or continue to tackle the races?

**Comment by annymsMthd** [comment]
Closing for squashed and rebased PR. #870

**Pull request closed without merging**
