### PR TITLE
Testkit support for MSpec

### PR DESCRIPTION
**Pull request by Silv3rcircl3**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Silv3rcircl3 do the unit tests for MSpec need to be run using the MSpec test runner?

**Comment by Aaronontheweb** [comment]
I assume that's the case :p - right now the build script is trying to run them using XUnit. You'll need to modify the FAKE file; you can see some examples of where we did this to support other test runners:

https://github.com/akkadotnet/akka.net/blob/dev/build.fsx#L214

**Comment by Silv3rcircl3** [comment]
Yeah I totally forgot to run the build script on my local machine before I submitted the PR. 
I hope it works now :pray:

**Comment by Silv3rcircl3** [comment]
The MSpectests are passing but the MultiNodeTestRunner throws an exception... 

Do I need to include the Testkit.MSpec int the CopyOutput target?

**Comment by Aaronontheweb** [comment]
@Silv3rcircl3 yessir - you should also make sure to add a .nuspec file to the project (so FAKE can detect that we need to publish a package for it)

**Comment by Aaronontheweb** [comment]
looks like we have a merge conflict here since v1.0.4 - could you update?

**Comment by Silv3rcircl3** [comment]
Oh my god, that doesn't went well. 
I think I did it wrong, I have rebased the akka repositroy in visual studio... 
Should I delete the PR and create a new one ? :)

**Comment by GraemeBradbury** [comment]
Since mspec has been [end-of-lifed](http://www.planetgeek.ch/2015/04/28/bye-bye-machine-specifications/) is it worth using it?

**Comment by Silv3rcircl3** [comment]
These are sad news :( 
I have created a [Gist](https://gist.github.com/Silv3rcircl3/fee49a8ddb88e56ecbbf) with the files that are included in this PR so that anybody can use them if needed. 

Feel free to close the PR.

**Pull request closed without merging**
