### PR TITLE
Detailed error message on sending Tcp.Close to TcpManager

### LINKED ISSUE #3768: System.ArgumentException when trying to close TCP connection
**Environment**
* Akka Version 1.3.12
* .NET Framework 4.7.1
* Win7
* Visual Studio 2017

**Steps to reproduce**
1. Check out a simple demo: https://github.com/MichaelMayrhofer/Akka.TcpDemo
The repo contains two projects:
1.1 **TcpServer:** Waits for an incoming TCP connection and sends each second a date-time string to the connected client.
-> Implemented without akka.net.
1.2 **TcpClient:** Connects to a TCP server, receives data and closes the connection.
-> Implemented with akka.net.
2. Build & run the two programs.
3. Press [enter] in the TcpClient.exe console window to connect to the TCP server.
4. The TcpClient should receive data.
5. Press [enter] in the TcpClient.exe console window to close the connection.

=> there will be an error output in the TcpClient.exe console window:
> [ERROR][29.04.2019 05:17:24][Thread 0004][akka://Akka-TcpDemo/system/IO-TCP] The  supplied message type is invalid. Only Connect and Bind messages are supported.
>
> Parametername: message
> Cause: System.ArgumentException: The supplied message type is invalid. Only Connect and Bind messages are supported.
> Parametername: message
>    bei Akka.IO.TcpManager.Receive(Object message)
>    bei Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    bei Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    bei Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Implementation details:**
The TcpClient uses `Context.System.Tcp().Tell(new Tcp.Connect(...))` and `Sender.Tell(new Tcp.Register(...))` to open the TCP connection. With `Context.System.Tcp().Tell(Tcp.Close.Instance)` the connection will be closed.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #3768

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@IgorFedchenko looks like a merge conflict here

**Comment by IgorFedchenko** [comment]
@Aaronontheweb Indeed, resolved now.

**Comment by Aaronontheweb** [comment]
Looks like a compilation failure now

**Comment by IgorFedchenko** [comment]
Sorry for that

**Pull request merged**
