### PR TITLE
made Akka.Persistence.SqlServer LinkedList ThreadSafe

### PR DESCRIPTION
**Pull request by Aaronontheweb**
work done by @zetanova

### CODE REVIEW

**Comment by Horusiath** [comment]
Actually in this context, list of pending operations isn't even necessary, as the only thing we use pending operations list for is to cancel all async operations, that work in the background when actor is stopped. This can be done easy using single shared `CancellationTokenSource` as it's in [JournalDbEngine](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs#L61) right now.

**Comment by rogeralsing** [comment]
@Horusiath so you are saying that this PR fixes a non issue?

**Comment by Horusiath** [comment]
I've submitted PR #1507 , where I've (hopefully) solved this problem in the simpler manner.

**Comment by Aaronontheweb** [comment]
@Horusiath can this be closed then?

**Comment by Horusiath** [comment]
Fixed in another PR (#1507)

**Pull request closed without merging**
