### PR TITLE
First autodetected bugs

### PR DESCRIPTION
**Pull request by rogeralsing**
# Do not merge

This PR demonstrates the initial work on the code analyzer.
It correctly detected the use of Self/Sender/Context inside `ContinueWith`

Currently, the analyzer only comments on these issues, I think that is probably safest so that we can reason about the change and fix it as we like.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
This is super cool @rogeralsing! Should we be recommending that developers close over `Self` and `Parent`? I thought that since those properties were immutable it didn't matter - is there something I'm missing?

**Comment by rogeralsing** [comment]
`Parent` is only available on `Context`, so to access it you have to close over `Context`

`Self` has this impl;

```csharp
protected IActorRef Self { get { return HasBeenCleared ? _clearedSelf : Context.Self; } }
```

Which means that as long as the actor is a normal actor, it goes through the thread static `Context`, so even if Self never changes, Context does (because of the thread static magic we have for scala implicit values)

So yes, both needs to be closed over.

**Comment by rogeralsing** [comment]
I created another analyzer that checks the number of references to each class.
There are like 70+ classes that has 0 references via code atm.
that does not however mean that they are not used, they could be used via reflection, but we should at least verify their usage.
either remove them, or add tests that show how they should be used..

**Comment by rogeralsing** [comment]
(Some might be tests that the analyzer doesnt yet see as tests.)

**Comment by rogeralsing** [comment]
cc @akkadotnet/developers please take a peek at all the "not used" classes. we need better coverage than this

**Comment by Danthar** [comment]
This is pretty damn cool stuff. Ill see if I can spend some time this weekend to verify some of the unused code.

**Comment by rogeralsing** [comment]
I've updated the analyzer to ignore test classes, as those generally report 0 references as they are managed via reflection in the testrunners.
sending a clean PR with a more accurate list of files

**Pull request closed without merging**
