### PR TITLE
Fix issue #2440

### PR DESCRIPTION
**Pull request by SeanFarrow**
Fixes issue #2440, but does not migrate away form using MSBuild style package restore, I'll do this as a separate issue.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@SeanFarrow  on Mono:

```
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:14]	Cannot open assembly '/checkout/src/packages/FAKE/tools/FAKE.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/.nuget/NuGet.exe': No such file or directory.
[15:39:17]	Cannot open assembly '/checkout/src/packages/FAKE/tools/FAKE.exe': No such file or directory.
```

**Comment by Aaronontheweb** [comment]
@SeanFarrow Mono compilation step is still failing, same issue as before.

**Comment by SeanFarrow** [comment]
@aaronontheweb,Where is this specifically failing?
I can’t replicate this locally!

**Comment by Danthar** [comment]
@SeanFarrow The mono build uses the build.sh file to run the build. It seems the errors originate from that file. As far as i can see, it should download nuget.exe if its not there. But apparently there is a bug in that script.

**Comment by SeanFarrow** [comment]
Ok, thanks, do you have any idea what the bug is?

**Comment by Danthar** [comment]
It seems that the check that verifies if the nuget.exe is there does not work. Either that, or downloading the nuget.exe fails (or puts it in the wrong directory or something)

**Comment by Aaronontheweb** [comment]
@SeanFarrow the process is still trying to access the `/src/.nuget/NuGet.exe'

**Comment by SeanFarrow** [comment]
Which project specifically?
There could be a bug in the build.sh script—I don’t have a mono setup to test unfortunately!

**Comment by Danthar** [comment]
@SeanFarrow me either, but you could check the code for obvious problems, and then abuse our CI integation to let you know if that fixed it ;). Long feedback cycle though. 

I can take a look this afternoon and see if i can spot any pathing problems. Ill let you know what i find.

**Comment by Danthar** [comment]
Ah yes. The problem is in the build.sh file. nuget is downloaded as nuget.exe. While further down the process its being called as NuGet.exe (note the difference in capitals). Because its run on a unix machine it fails.

The reason current builds do work. Is because the NuGet.exe was already part of the artifacts. So even though the if condition that checks if the exe is there returns false, and it downloads a new version of nuget. There would effectively be 2 versions available side by side. A nuget.exe and a NuGet.exe. (again note the difference in capitals). 
Because you removed the NuGet.exe that was in git, this fails now.

If you want i can do a PR to fix this. Or you can make it part of this PR. Whatever you want.

**Comment by SeanFarrow** [comment]
Hi,

I’ll fix this tomorrow, thanks!

**Comment by Danthar** [comment]
ow man. You stirred a hornet nest here @SeanFarrow .
Next problem: "./build.sh: line 13: wget: command not found"

**Comment by SeanFarrow** [comment]
Hi,
Any chance of you fixing?
Cheers
Sean.

**Comment by Aaronontheweb** [comment]
The issue with wget is my fault. We switched Docker containers and wget is not included by default on the new container so we'll have to install it.

**Pull request merged**
