### PR TITLE
ThisActorSystemQuarantinedEvent event added

### PR DESCRIPTION
**Pull request by zbynek001**

### CODE REVIEW

**Comment by Silv3rcircl3** [comment]
@zbynek001 do you need this for something? 

This changes were also made in #1745

**Comment by zbynek001** [comment]
Sorry, didn't see it. I'll close this one then.
I'm planning to use this as one of the events to check inside split-brain resolver

**Comment by Silv3rcircl3** [comment]
Alright, no problem, I will make sure that we get the other PR in and you can use it from the nightly builds.

**Comment by Silv3rcircl3** [comment]
@zbynek001 #1745 was merged, so you're good to go ;)

**Comment by zbynek001** [comment]
Great, thanks!

**Pull request closed without merging**
