### PR TITLE
Add spec for handling delegates in DI

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Looks like one of these specs failed

**Comment by Arkatufus** [comment]
It was a racy spec

**Comment by Aaronontheweb** [comment]
@Arkatufus yes, but it looks like a new one we just introduced - we should try to harden that before it gets merged into the suite.

**Comment by Aaronontheweb** [comment]
This is the spec that failed - it's only the tests that you are adding in this PR that are racy in this instance; incrementalist won't run any of the tests from outside this test suite since the only library that is affected is Akka.DependencyInjection:

**Akka.DependencyInjection.Tests.ActorServiceProviderPropsWithScopesSpecs.ActorsWithNonDiDependenciesShouldStart**

```
Expected deps1.Dependencies.Where(x => (x is AkkaDiFixture.ISingletonDependency)).All(x => x.Disposed) to be true, but found False.`
```

**Comment by Arkatufus** [comment]
I didn't write that test.
I'll look into it.

**Comment by Aaronontheweb** [comment]
> I didn't write that test.
> I'll look into it.

Whoops - my bad

**Pull request merged**
