### PR TITLE
Fixes for mono FAKE builds

### PR DESCRIPTION
**Pull request by stefansedich**
Fixes for #1100

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@stefansedich could you squash these commits?

**Comment by Aaronontheweb** [comment]
Pull in latest from dev - #1102 might have fixed this.

**Comment by stefansedich** [comment]
Ah awesome! Wil give that a shot today sometime.

**Comment by Aaronontheweb** [comment]
@stefansedich mind including a short update about where you're at with the Mono stuff? All of the fun stuff from our Skype chat ;)

**Comment by stefansedich** [comment]
Sure sorry @Aaronontheweb forgot to write an update :)

So thus far this has been mostly a task of one step forwards 500 back, after various small fixes to actually get the build running on Mono (fix some output paths, ignore MSTest tests under mono) we have now run into an issue with xunit2 on mono: 

https://github.com/xunit/xunit/issues/158

According to this thread the master branch (4.3.x) actually works with xunit2 (this is something I am currently validating as being true for akka.net).

I will update as soon as I get the latest mono compiling and have a chance to run the build.

**Comment by stefansedich** [comment]
Ok running the latest nightly mono build the xunit tests at least start, but at the first cluster test it goes boom and seems to hang.

Will investigate this further!

**Comment by stefansedich** [comment]
@Aaronontheweb should I kill this PR for now and shelve my changes? I am not sure I see a fix in the immediate term, I prefer to not just change the tests to mask the issue we are seeing in Mono :(.

**Comment by Aaronontheweb** [comment]
@stefansedich yes, that's probably for the best - but keep #1110 up to date.

**Comment by stefansedich** [comment]
Ok no worries, closing this off!

**Pull request closed without merging**
