### PR TITLE
read Environment.ProcessorCount once into a static

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/akkadotnet/akka.net/issues/2713

### CODE REVIEW

**Comment by 0x53A** [comment]
ref https://github.com/fsharp/FAKE/issues/1571 for the build error ...

**Comment by Danthar** [comment]
Not sure why test are failing. I restarted the tests, 
The change is harmless from a functional perspective.

**Comment by Aaronontheweb** [comment]
# Before

# Akka.Remote.Tests.Performance.Transports.HeliosRemoteMessagingThroughputSpec+OneWay
__Measures the throughput of Akka.Remote over a particular transport using one-way messaging__
_5/30/2017 10:58:53 PM_
### System Info
```ini
NBench=NBench, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Iterations, TestMode=Measurement
NumberOfIterations=3, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          137.00 |          136.67 |          136.00 |            0.58 |
|TotalCollections [Gen1] |     collections |            4.00 |            2.33 |            1.00 |            1.53 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       50,000.00 |       50,000.00 |       50,000.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           25.58 |           25.13 |           24.87 |            0.40 |
|TotalCollections [Gen1] |     collections |            0.73 |            0.43 |            0.19 |            0.27 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |        9,336.66 |        9,192.27 |        9,075.48 |          132.76 |

### Raw Data
#### TotalCollections [Gen0]
|           Run # |     collections | collections / s |ns / collections |
|---------------- |---------------- |---------------- |---------------- |
|               1 |          137.00 |           24.87 |   40,214,253.28 |
|               2 |          137.00 |           25.58 |   39,089,308.76 |
|               3 |          136.00 |           24.93 |   40,115,722.79 |

#### TotalCollections [Gen1]
|           Run # |     collections | collections / s |ns / collections |
|---------------- |---------------- |---------------- |---------------- |
|               1 |            4.00 |            0.73 |1,377,338,175.00 |
|               2 |            1.00 |            0.19 |5,355,235,300.00 |
|               3 |            2.00 |            0.37 |2,727,869,150.00 |

#### TotalCollections [Gen2]
|           Run # |     collections | collections / s |ns / collections |
|---------------- |---------------- |---------------- |---------------- |
|               1 |            0.00 |            0.00 |5,509,352,700.00 |
|               2 |            0.00 |            0.00 |5,355,235,300.00 |
|               3 |            0.00 |            0.00 |5,455,738,300.00 |

#### [Counter] RemoteMessageReceived
|           Run # |      operations |  operations / s | ns / operations |
|---------------- |---------------- |---------------- |---------------- |
|               1 |       50,000.00 |        9,075.48 |      110,187.05 |
|               2 |       50,000.00 |        9,336.66 |      107,104.71 |
|               3 |       50,000.00 |        9,164.66 |      109,114.77 |

**Comment by Aaronontheweb** [comment]
# After

# Akka.Remote.Tests.Performance.Transports.HeliosRemoteMessagingThroughputSpec+OneWay
__Measures the throughput of Akka.Remote over a particular transport using one-way messaging__
_5/31/2017 8:51:58 AM_
### System Info
```ini
NBench=NBench, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
WorkerThreads=32767, IOThreads=2
```

### NBench Settings
```ini
RunMode=Iterations, TestMode=Measurement
NumberOfIterations=3, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
          Metric |           Units |             Max |         Average |             Min |          StdDev |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalCollections [Gen0] |     collections |          213.00 |          204.00 |          197.00 |            8.19 |
TotalCollections [Gen1] |     collections |           28.00 |           23.67 |           20.00 |            4.04 |
TotalCollections [Gen2] |     collections |            1.00 |            0.33 |            0.00 |            0.58 |
[Counter] RemoteMessageReceived |      operations |       50,000.00 |       50,000.00 |       50,000.00 |            0.00 |

### Per-second Totals
          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
TotalCollections [Gen0] |     collections |           63.13 |           62.38 |           61.12 |            1.10 |
TotalCollections [Gen1] |     collections |            8.97 |            7.27 |            6.05 |            1.52 |
TotalCollections [Gen2] |     collections |            0.32 |            0.11 |            0.00 |            0.19 |
[Counter] RemoteMessageReceived |      operations |       16,022.57 |       15,303.90 |       14,761.50 |          648.75 |

### Raw Data
#### TotalCollections [Gen0]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |          213.00 |           62.88 |   15,902,298.59 |
               2 |          197.00 |           63.13 |   15,840,596.45 |
               3 |          202.00 |           61.12 |   16,362,440.59 |

#### TotalCollections [Gen1]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |           23.00 |            6.79 |  147,269,113.04 |
               2 |           28.00 |            8.97 |  111,449,910.71 |
               3 |           20.00 |            6.05 |  165,260,650.00 |

#### TotalCollections [Gen2]
           Run # |     collections | collections / s |ns / collections |
---------------- |---------------- |---------------- |---------------- |
               1 |            0.00 |            0.00 |3,387,189,600.00 |
               2 |            1.00 |            0.32 |3,120,597,500.00 |
               3 |            0.00 |            0.00 |3,305,213,000.00 |

#### [Counter] RemoteMessageReceived
           Run # |      operations |  operations / s | ns / operations |
---------------- |---------------- |---------------- |---------------- |
               1 |       50,000.00 |       14,761.50 |       67,743.79 |
               2 |       50,000.00 |       16,022.57 |       62,411.95 |
               3 |       50,000.00 |       15,127.62 |       66,104.26 |

**Comment by Aaronontheweb** [comment]
Specs look good from the POV of Akka.Remote, but the current dispatcher throughput specs that measure the dispatcher implementations themselves don't perform enough work for a measurement to be reliable. About to submit a PR that bumps it up considerably.

**Comment by Aaronontheweb** [comment]
@Danthar some sort of issue with the Mono compiler... No idea why that's having an issue, given that it appears to be having trouble with FAKE. 

cc @heynickc did we change the Mono docker container at all today?

**Comment by Aaronontheweb** [comment]
@0x53A looks like the build agent was properly cleaning itself out on checkout for Mono builds, hence why we had this issue. Just updated those settings and am re-running it now.

**Comment by Aaronontheweb** [comment]
No idea where there's a persistent Mono compilation failure here, given that we're doing clean checkouts now...

**Comment by 0x53A** [comment]
It looks like it fails when it Writes the cache, not when Reading it.

If you are doing a clean build anyway, I would just disable the cache.

**Comment by Aaronontheweb** [comment]
@0x53A killing off the current TC build agents and relaunching them since the same issue re-appeared

**Comment by 0x53A** [comment]
My guess that it's related to the cache was wrong, it can't even compile build.fsx:
http://petabridge-ci.cloudapp.net/viewLog.html?buildId=27587&buildTypeId=AkkaNet_LinuxMonoBuild&tab=buildLog#_state=684,695,703,30,35,32,354,395&focus=618

image

This looks similar to https://github.com/fsharp/fsharp/issues/685, which was fixed in https://github.com/fsharp/fsharp/pull/687.

**Comment by Aaronontheweb** [comment]
@0x53A you were targeting the `master` branch, which explains a bunch of these issues - I've changed it to point to the `v1.3` branch instead :p 

Could you revert your changes to the build scripts?

**Comment by Aaronontheweb** [comment]
@0x53A actually, I'd probably just rebase the entire thing on `v1.3` and remove those two commits

**Comment by 0x53A** [comment]
@Aaronontheweb done - let's see if the CI likes me

**Comment by 0x53A** [comment]
@Aaronontheweb build looks broken:

image


image

**Comment by Aaronontheweb** [comment]
@0x53A we're having issues with other parts of our test suite unrelated to your changes (timeouts;) no worries, we'll b dealing with that shortly.

**Pull request merged**
