### PR TITLE
ported #12449. And added the project Akka.Remote.Tests.Multinode to t…

### PR DESCRIPTION
**Pull request by GeertVL**
…he InternalsVisibleTo of the Akka.Remote project.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@GeertVL sorry for the delay on this! I'll review this today and see if I can help figure out why it's not passing.

**Comment by rogeralsing** [comment]
Stale PR, what do we do with it?

**Comment by Aaronontheweb** [comment]
Leave it alone - the test code is still good and this makes it easy to find it

**Comment by Aaronontheweb** [comment]
Already ported

**Pull request closed without merging**
