### PR TITLE
Deprecate PersistentFSM+State.Using (#3955)

### PR DESCRIPTION
**Pull request by aloker**
Also replaces all internal calls with calls to Copy, so Using can safely be removed in the future.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@aloker ah, need to approve the API: https://getakka.net/community/public-api-changes.html

**Comment by aloker** [comment]
Oh, didn't know about that. Let me check.

**Comment by Aaronontheweb** [comment]
It's ok, we keep it in there so people don't make breaking API changes by accident.

**Comment by aloker** [comment]
So I basically diff the related .received.txt and and the .approved.txt file to check that only the intended changes are in there (here: the added attribute) and then copy .received.txt over to .approved.txt, right?

**Comment by Aaronontheweb** [comment]
@aloker all you should need to do is just commit the new `approved.txt` after running it through a diff / merge tool. Should launch automatically when the test fails. Otherwise, you could copy it over manually and rename it.

**Comment by aloker** [comment]
I didn't notice P4Merge pop up in the background. Nice :-)

**Pull request merged**
