### PR TITLE
Akka.Persistence plugin

### PR DESCRIPTION
**Pull request by Horusiath**
This is a port of the canonical Akka.Persistence plugin for Akka JVM:

- User-friendly documentation is available under `documentation/wiki/Persistence.md`. 
- Technical description of the actor's recovery cycle can be found inside README.md file in main Akka.Persistence project. 
- Example project (`Examples/Persistence/PersistentExample`) shows basic API usage.
- Additional tech description may be found in XML comments inside project itself.

While all common cases are working, there are still some known issues. Some of the implemented test may still be failing - those are marked as skipped - for various reasons, including bugs found in other parts of core Akka project (known places are tagged with `FIXME` comment inside project code base).

Additionally, `Akka.Persistence.TestKit` xUnit-based project also has been ported to provide basic test cases to verify third-party plugins of backend storages for Journals and Snapshot Stores. All test cases are have been implemented successfully, so this project can be freely used for plugin verification.

This push request doesn't introduce any nuspec files inside the projects, so actual NuGet packaging must be done in separate commit.

cc #316

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Horusiath I think this is a tremendous accomplishment, Bartosz. Very well done.

Do you think this is ready to distribute via a `-pre` NuGet package yet for super-early adopters? Or are there some critical cases and features missing still?

**Comment by Horusiath** [comment]
@Aaronontheweb I love that kind of questions ;) As a man, who spent 99% of his time with this lib on debugging, fixing bugs and seeing things broken I think I'm the most skeptic person in the world to distribute this package right now :D

I think that journals and snapshot stores are pretty stable right now. We may even start to integrate them with 3rd party storage. Considering other parts of the library:

- `PersistentActor` and it's derivatives are almost done. Tests have shown some problems with custom persistent actors using stashing, but I don't know yet if this issue occurs also in real actor systems.
- `PersistentView` also works quite well. There are some minor problem referring an update message parametrization and actor crashes during recovery.
- `GuaranteedDeliveryActors` is the part, I'm most concerned with. While everything seems to work as designed, there are still some failing scenarios of recovering unconfirmed messages received from actor's state snapshot.

Summarizing: I think we may distribute it with `-pre` flag, but I'd recommend to take this lib, compile it, play with and try to break some things... by more than one person to be sure.

**Comment by mmisztal1980** [comment]
I can't seem to locate documentation/wiki/Persistence.md - is this an authorization issue?

**Comment by Aaronontheweb** [comment]
@mmisztal1980 https://github.com/akkadotnet/akka.net/blob/dev/documentation/wiki/Persistence.md - does that work for you?

**Comment by mmisztal1980** [comment]
yes! Cheers Aaron.

**Comment by Aaronontheweb** [comment]
No problem Maciek - we're going to do a re-organization of the documentation to make this stuff easier to find in the future :)

**Pull request merged**
