### PR TITLE
[misc] Fixed incorrect copyright headers

### PR DESCRIPTION
**Pull request by sean-gilliam**
This PR fixes numerous copy paste errors in the copyright headers of
some of the source files.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
should probably change the date to be 2016 for all of those anyway

**Comment by sean-gilliam** [comment]
That's a good point. Do you want me to change them for the files affected in this PR and make a separate PR updating the dates for the rest of the files in the tree? Or just append this PR to update the dates on the rest of the files in the tree?

**Comment by Aaronontheweb** [comment]
@sean-gilliam append this PR imho

**Comment by sean-gilliam** [comment]
kk

**Comment by sean-gilliam** [comment]
I modified the PR to address @Aaronontheweb concerns. 

NOTE: The diff is HUMENGEOUS since it touches nearly every file. But most of it is just date changes.

**Comment by Aaronontheweb** [comment]
YOLO

**Comment by sean-gilliam** [comment]
hehe :)

**Pull request merged**
