### PR TITLE
upgraded to XUnit 2.3.1 and VsTest SDK 15.7.2

### PR DESCRIPTION
**Pull request by Aaronontheweb**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
LOL... apparently this broke 100% of the ApiApproval specs. Must be because it affected something in the API.Approvals test assembly itself. I'll double check and see what's up.

**Comment by Danthar** [comment]
This update is also needed to support netstandard 2.0 apparently.

**Comment by Aaronontheweb** [comment]
Got that fixed - had to adjust the output copying of the stored API approval file

**Comment by Aaronontheweb** [comment]
@Danthar I'm probably going to need to merge this into the v1.4 branch as well then :p

**Pull request merged**
