### PR TITLE
ActorSelection refactor

### PR DESCRIPTION
**Pull request by sean-gilliam**
This PR refactors ActorSelection to take advantage of newer C# features.

Breaking apart #2854 for easier review.

### CODE REVIEW

**Comment by sean-gilliam** [comment]
### System Info
```ini
NBench=NBench, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
ProcessorCount=8
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=False
Tracing=False
```

# Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_stress_test
### Totals
|                                    Metric |        |          Units |             Max |         Average |             Min |          StdDev |
|------------------------------------------ |------- |--------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |     operations |       12,415.00 |       12,415.00 |       12,415.00 |            0.00 |
|[Counter] ActorSelectionOperationCompleted |  After |     operations |       12,538.00 |       12,538.00 |       12,538.00 |            0.00 |
|                                           |   Diff |     operations |         +123.00 |         +123.00 |         +123.00 |            0.00 |
### Per-second Totals
|                                    Metric |        |     Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |-------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |    operations |       14,138.31 |       13,774.53 |       13,324.96 |          224.24 |
|[Counter] ActorSelectionOperationCompleted |  After |    operations |       14,545.21 |       14,320.96 |       13,196.68 |          376.59 |
|                                           |   Diff |    operations |         +406.90 |         +546.43 |         -128.28 |         +152.35 |

# Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_throughput
### Totals
|                                    Metric |        |          Units |             Max |         Average |             Min |          StdDev |
|------------------------------------------ |------- |--------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |     operations |       31,797.00 |       31,797.00 |       31,797.00 |            0.00 |
|[Counter] ActorSelectionOperationCompleted |  After |     operations |       33,039.00 |       33,039.00 |       33,039.00 |            0.00 |
|                                           |   Diff |     operations |       +1,242.00 |       +1,242.00 |       +1,242.00 |            0.00 |
### Per-second Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |       33,171.11 |       32,424.18 |       31,427.47 |          566.79 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |       34,985.49 |       34,836.52 |       34,544.10 |          114.55 |
|                                           |   Diff |      operations |       +1,814.38 |       +2,412.34 |       +3,116.63 |         -452.24 |

# Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_new_actor_throughput
### Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |       16,351.00 |       16,351.00 |       16,351.00 |            0.00 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |       16,462.00 |       16,462.00 |       16,462.00 |            0.00 |
|                                           |   Diff |      operations |         +111.00 |         +111.00 |         +111.00 |            0.00 |
### Per-second Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |       19,670.83 |       19,399.27 |       18,259.01 |          406.64 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |       20,737.72 |       20,577.14 |       20,452.29 |           87.08 |
|                                           |   Diff |      operations |       +1,066.89 |       +1,177.87 |       +2,193.28 |         -319.56 |

# Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_pre_existing_actor_throughput
### Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |
|                                           |   Diff |      operations |            0.00 |            0.00 |            0.00 |            0.00 |
### Per-second Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |      270,071.26 |      257,322.57 |      245,040.03 |        6,697.46 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |      360,464.28 |      349,822.53 |      328,640.73 |       10,156.78 |
|                                           |   Diff |      operations |      +90,393.02 |      +92,499.96 |      +83,600.70 |       +3,459.32 |

# Akka.Tests.Performance.Actor.ActorSelectionSpecs+Reused_ActorSelection_on_pre_existing_actor_throughput
### Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |       10,000.00 |       10,000.00 |       10,000.00 |            0.00 |
|                                           |   Diff |      operations |            0.00 |            0.00 |            0.00 |            0.00 |
### Per-second Totals
|                                    Metric |        |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|------------------------------------------ |------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|                                           | Before |      operations |      438,744.82 |      379,633.62 |      252,280.75 |       63,419.00 |
|[Counter] ActorSelectionOperationCompleted |  After |      operations |      652,367.35 |      622,933.77 |      590,628.65 |       18,828.55 |
|                                           |   Diff |      operations |     +213,622.53 |     +243,300.15 |     +338,347.90 |      -44,590.45 |

**Comment by alexvaluyskiy** [comment]
## Before

 |                                      Method |       Mean |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
 |-------------------------------------------- |-----------:|-------:|-------:|-------:|----------:|
 | ActorSelection_initialization_relative_path |   845.0 ns | 0.0210 |      - |      - |     648 B |
 | ActorSelection_initialization_absolute_path | 4,078.4 ns | 0.0831 |      - |      - |    2680 B |
 |                         ActorSelection_tell | 4,261.4 ns | 0.0926 | 0.0081 |      - |    2151 B |
 |             ActorSelection_tell_with_sender | 4,295.7 ns | 0.0946 | 0.0122 | 0.0015 |    2151 B |
 |             ActorSelection_local_ResolveOne | 7,150.9 ns | 0.2090 | 0.0107 | 0.0015 |    4424 B |

## After

 |                                      Method |       Mean |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
 |-------------------------------------------- |-----------:|-------:|-------:|-------:|----------:|
 | ActorSelection_initialization_relative_path |   852.0 ns | 0.0205 |      - |      - |     648 B |
 | ActorSelection_initialization_absolute_path | 4,225.2 ns | 0.0804 |      - |      - |    2680 B |
 |                         ActorSelection_tell | 3,889.7 ns | 0.0412 | 0.0081 | 0.0005 |    1118 B |
 |             ActorSelection_tell_with_sender | 3,877.0 ns | 0.0381 | 0.0086 | 0.0005 |    1118 B |
 |             ActorSelection_local_ResolveOne | 6,818.2 ns | 0.1521 | 0.0102 | 0.0010 |    3392 B |

**Comment by Danthar** [comment]
So, less memory allocation. But slower in almost all cases

**Comment by alexvaluyskiy** [comment]
@Danthar It has almost the same or higher perf in all tests

**Comment by Danthar** [comment]
@alexvaluyskiy You are right. Im not reading it correctly.

**Comment by Aaronontheweb** [comment]
I have no idea what's going on with these Windows specs for the MNTR blowing up - happened on my PR too.... Might be some sort of issue with two versions of XUnit going on inside the assembly there, but weird that it appears to happen randomly.

```
System.InvalidCastException : Unable to cast transparent proxy to type 'Xunit.DiaSessionWrapperHelper'.
   at Akka.MultiNodeTestRunner.Shared.Tests.MultiNodeTestRunnerDiscovery.DiscoverySpec.DiscoverSpecs() in D:\work\edbce350daf6a08d\src\core\Akka.MultiNodeTestRunner.Shared.Tests\MultiNodeTestRunnerDiscovery\DiscoverySpec.cs:line 49
   at Akka.MultiNodeTestRunner.Shared.Tests.MultiNodeTestRunnerDiscovery.DiscoverySpec.No_abstract_classes() in D:\work\edbce350daf6a08d\src\core\Akka.MultiNodeTestRunner.Shared.Tests\MultiNodeTestRunnerDiscovery\DiscoverySpec.cs:line 20
```

**Comment by Aaronontheweb** [comment]
#2875 contains some fixes that are needed to get these MNTR specs to pass again

**Pull request merged**
