### PR TITLE
DONT MERGE

### PR DESCRIPTION
**Pull request by GraemeBradbury**
Stuff to see what's what with the build hangs.

Please don't merge.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
So I just noticed that the files actually do get written to disk successfully (RDP into the build server to verify) but this call never appears to return. It's like the process for the multinode test runner never exits.

**Comment by GraemeBradbury** [comment]
Did the json/html contain more than 1 message/test?
The entire file gets re-written each message the sink receives.
So I wonder if the something is messing up the output.

**Comment by Aaronontheweb** [comment]
## JSON
[Akka.Cluster.Tests.MultiNode-635834854169362547-JSON.txt](https://github.com/akkadotnet/akka.net/files/38459/Akka.Cluster.Tests.MultiNode-635834854169362547-JSON.txt)

## HTML
[Akka.Cluster.Tests.MultiNode-635834854169362547-HTML.txt](https://github.com/akkadotnet/akka.net/files/38460/Akka.Cluster.Tests.MultiNode-635834854169362547-HTML.txt)

**Comment by Aaronontheweb** [comment]
Nope, only 1 test

**Comment by GraemeBradbury** [comment]
Think this is a race condition in the coordinator.

**Pull request closed without merging**
