### PR TITLE
RemoteDaemon bug, not removing children

### PR DESCRIPTION
**Pull request by rogeralsing**
This fixes the issue that remote deployed actors was not removed from the remote daemon when `.Stop(remoteref)`. which resulted in that it was impossible to re-deploy remote actors with the same name,

Renamed RemoteDaemon to RemoteSystemDaemon (was changed in JVM)
Added Hooks 
Added spin-retry updates of parent2children
Added fake remote terminator argument (using deadletters instead of true termination hooks as those are still missing)
Added AddChildParentNeedsWatch

### CODE REVIEW

**Comment by rogeralsing** [comment]
I've found a big issue in the last change to this PR.

Apparently, when the RemoteSystemDaemon tries to send messages back to the calling system, there is no `Serialization.CurrentTransport` 
This line `parent.Tell(new Watch(parent, this),this);` tries to communicate back to the creating system, _but_ the `ActorRef` for the remote daemon gets serailized w/o transport information, that is, no address, no protocol.
Which causes the calling side to fail when trying to deserialize that message.

This looks critical to me, if the remoting layer "forgets" to set the active transport before sending messages under some conditions.

cc @Aaronontheweb

**Comment by rogeralsing** [comment]
I Updated the PR, fixed the problem with outbound actorrefs in RemoteSystemDaemon. (which was an error in Serialization.SerializeActorRef, not as I first suspected, an error with active transports)

However, there is another bug that surfaces if the `parent.Tell(new Watch(parent, this),this);` line is uncommented.
The remoting layer will try to re-watch the actorref over and over, so that needs fixing, but I'd say that is a separate issue.
I'm leaving the line commented for now, as this is new functionallity that we have not had before, and which relies on the remote watching re-watch problem to be resolved first.

**Comment by rogeralsing** [comment]
The failing test might be racy or something, it works locally, rerun?

**Comment by Aaronontheweb** [comment]
This is great work @rogeralsing - I'll give it a full review tomorrow.

**Comment by rogeralsing** [comment]
Just to avoid any confusion, this is unrelated to #1062

**Pull request merged**
