### PR TITLE
[WIP] Cluster Tools technical debt

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Did not change anything, just cleaned the API. Also I've updated *.DotSettings file, and added default *.ruleset file

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
I have plans to change namespaces
Akka.Cluster.Tools.Singleton => Akka.Cluster.Singleton
Akka.Cluster.Tools.Client => Akka.Cluster.Client
Akka.Cluster.Tools.PublishSubscribe => Akka.Cluster.PubSub or (Akka.Cluster.PublishSubscribe)

and move all public PubSub messages under DistributedPubSubMediator class, like JVM did
@Aaronontheweb @Horusiath what do you think?

**Comment by Horusiath** [comment]
Regarding changing namespaces - great! :) 
Regarding moving messages under mediator - it will be irritating to prefix every message with `DistributedPubSubMediator` (think about other .NET languages here as well).

**Comment by alexvaluyskiy** [comment]
@Horusiath so Akka.Cluster.PubSub or Akka.Cluster.PublishSubscribe? Since we have a class DistributedPubSubMediator, we should use PubSub

> Regarding moving messages under mediator - it will be irritating to prefix every message with DistributedPubSubMediator
But we have all public message under ClusterClient. We should have consistency here.

**Comment by Aaronontheweb** [comment]
I have no idea what happened with the MNTR on this run... Looks like something faulted early on in the test run and broke 100% of the specs that came after it... Process that failed to terminate or something else like it could do it.

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy mind updating this PR with the latest?

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb only when we decide to make Cluster.Tools as a stable

**Pull request closed without merging**
