### PR TITLE
Possible fix for racy sql testkit specs

### PR DESCRIPTION
**Pull request by Danthar**
As i have discovered before. XUnit in combination with the akka TestKit causes some wierd stuff sometimes.
One thing that happens is that state you expect to be reinitialized for each test is sometimes reused between tests.

Reference to where i encountered a similar case: http://stackoverflow.com/questions/40767924/testing-behavior-not-consistent-when-watching-actor-for-termination/40929659#40929659

What this PR does, is move the SqlReadJournal reference to the local scope. Thereby eliminating any chance there is concurrent access to that resource where its not expected.

The EventsByTagSpec might need more refactoring. But worked consistently locally on the SqlLite tests implementation whereas before are very racy.

### CODE REVIEW

**Comment by Danthar** [comment]
This might also help solve issues with: https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/56

**Comment by Horusiath** [comment]
If it works I'm all for it :) My only remark is to keep up with conventions - if `_queries` are local now, there's no need to have underscore prefix.

**Comment by Aaronontheweb** [comment]
@Danthar would you make those style changes that @Horusiath suggested?

**Comment by Danthar** [comment]
Sure thing. First thing tomorrow.

**Pull request merged**
