### PR TITLE
replaced inline delegates with local functions in perf-sensitive parts of Akka.Remote

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Should help reduce allocations

### CODE REVIEW

**Comment by Danthar** [comment]
Nice 👍

**Comment by Danthar** [comment]
Ah its a WIP  then :P let me/us know when your done. And it will be reviewed then.

**Comment by Danthar** [comment]
@Aaronontheweb told me he is done with this PR. Looks good to me.

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb @Danthar Hey guys, where is performance comparison? It is not serious

**Comment by Aaronontheweb** [comment]
any of the Akka.Remote benchmarks @alexvaluyskiy - and I compared the before and after results live onstage to an audience of about 100 people at Techorama. This PR outperformed the most recent PR to the v1.3 branch by about 10%, but I don't believe that value is wholly attributable to these changes.

**Comment by Aaronontheweb** [comment]
# Before 

# Akka.Remote.Tests.Performance.Transports.HeliosRemoteMessagingThroughputSpec+OneWay
__Measures the throughput of Akka.Remote over a particular transport using one-way messaging__
_5/22/2017 8:54:47 PM_
### System Info
```ini
NBench=NBench, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Iterations, TestMode=Measurement
NumberOfIterations=3, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          137.00 |          136.00 |          135.00 |            1.00 |
|TotalCollections [Gen1] |     collections |            3.00 |            2.33 |            2.00 |            0.58 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       50,000.00 |       50,000.00 |       50,000.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           24.68 |           24.60 |           24.56 |            0.07 |
|TotalCollections [Gen1] |     collections |            0.54 |            0.42 |            0.36 |            0.10 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |        9,141.88 |        9,044.89 |        8,964.37 |           89.89 |

**Comment by Aaronontheweb** [comment]
# After 

# Akka.Remote.Tests.Performance.Transports.HeliosRemoteMessagingThroughputSpec+OneWay
__Measures the throughput of Akka.Remote over a particular transport using one-way messaging__
_5/24/2017 9:23:11 AM_
### System Info
```ini
NBench=NBench, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Iterations, TestMode=Measurement
NumberOfIterations=3, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          137.00 |          136.67 |          136.00 |            0.58 |
|TotalCollections [Gen1] |     collections |            2.00 |            2.00 |            2.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       50,000.00 |       50,000.00 |       50,000.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           29.73 |           28.62 |           27.28 |            1.24 |
|TotalCollections [Gen1] |     collections |            0.43 |            0.42 |            0.40 |            0.02 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       10,851.02 |       10,471.33 |        9,956.50 |          462.32 |

**Comment by Aaronontheweb** [comment]
Pulled some more figures off of builds that ran today on the build server too:

# Akka.Remote.Tests.Performance.Transports.HeliosRemoteMessagingThroughputSpec+OneWay
__Measures the throughput of Akka.Remote over a particular transport using one-way messaging__
_5/25/2017 7:22:32 PM_
### System Info
```ini
NBench=NBench, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Iterations, TestMode=Measurement
NumberOfIterations=3, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          139.00 |          136.33 |          135.00 |            2.31 |
|TotalCollections [Gen1] |     collections |            3.00 |            2.67 |            2.00 |            0.58 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       50,000.00 |       50,000.00 |       50,000.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           28.46 |           28.02 |           27.23 |            0.69 |
|TotalCollections [Gen1] |     collections |            0.61 |            0.55 |            0.42 |            0.11 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|[Counter] RemoteMessageReceived |      operations |       10,539.15 |       10,278.43 |       10,086.13 |          234.13 |

**Comment by Aaronontheweb** [comment]
IMHO: these changes probably don't have much impact on the performance, but there's nothing but upside to using them. One of the new changes the C# 7 compiler introduces is the ability to have these local functions inlined or expressed as value types, both of which offer reduced GC pressure over the delegation allocation + closure method we used before. Worst case scenario though is that the compiler writes the code the exact same we did before.

But, most of this code is only used when the remoting system is buffering so I think most of the perf variations you're seeing have more to do with the busy-ness of the underlying hardware our VMs are running on.

**Pull request merged**
