### PR TITLE
fixed build script

### PR DESCRIPTION
**Pull request by Silv3rcircl3**

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
Is it related with failed checks here?
https://github.com/akkadotnet/akka.net/pull/1906

**Comment by Silv3rcircl3** [comment]
@alexvaluyskiy yep

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 is it possible to restart tests in that PR?

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy rebase to latest - that'll restart the PR.

**Pull request merged**
