### PR TITLE
Speedup unit test build

### PR DESCRIPTION
**Pull request by marcpiechura**
First attempt to run all tests in parallel except the racy ones

### CODE REVIEW

**Comment by Danthar** [comment]
@Silv3rcircl3 was this one ready ?

**Comment by Silv3rcircl3** [comment]
@danthar yup

**Comment by Danthar** [comment]
Now we have conflicts here.

**Comment by Silv3rcircl3** [comment]
@Danthar resolved

**Comment by Danthar** [comment]
👍

**Comment by Danthar** [comment]
Is this still a thing? Or has it been superseded by the work from @heynickc  ?

**Comment by heynickc** [comment]
@Danthar My work doesn't supersede the idea of doing this, but I'm not sure if it's safe at the moment to run tests in parallel since we see so much flaky behavior on Linux right now.  This might add an additional level of instability before we can resolve the existing instability in the test suite.

**Comment by alexvaluyskiy** [comment]
@Silv3rcircl3 is it still actual?

**Pull request closed without merging**
