### PR TITLE
#1918 Fixed version comparison of the DistributedPubSub to avoid cont…

### PR DESCRIPTION
**Pull request by corneliutusnea**
Fix for continuous incorrect delta sending between multiple DistributedPubSubMediators.
https://github.com/akkadotnet/akka.net/issues/1918#issuecomment-216122593

### CODE REVIEW

**Comment by Horusiath** [comment]
It's hard to verify that one without proper tests.

**Comment by corneliutusnea** [comment]
Yeah, I know. I'll try to write some but there were no tests around the area.
From my initial testing it seems to be working correctly and updates are passed across correctly.

**Comment by Aaronontheweb** [comment]
cc @alexvaluyskiy is this covered by any of the specs you've been porting?

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb yes, it covered by this spec  DistributedPubSubMediator_must_transfer_delta_correctly
Nevertheless, these changes are implemented in my PR too.

**Comment by Horusiath** [comment]
@alexvaluyskiy @Aaronontheweb so are we ready to merge this?

**Comment by alexvaluyskiy** [comment]
@Horusiath you could merge, but I made similar changes in this big PR https://github.com/akkadotnet/akka.net/pull/2057 and I've enabled all tests there.

**Pull request merged**
