### PR TITLE
use .NET Standard 2.0 and later as only build target

### LINKED ISSUE #3851: Target .NET Standard 2.0 and newer only
Version: 1.4.0 beta and beyond

As part of the v1.4.0 release we are now targeting .NET Standard 2.0, instead of .NET Standard 1.6, and long-term we plan to stick with .NET Standard as the "guts" of Akka.NET.

However, we are also still dual-targeting .NET 4.5.2 - a version of .NET that is getting quite old and is missing some features (i.e. some of the `TaskCompletionSource` flags) that we currently have to hack around.

Going forward, I would like to propose the following roadmap for how we manage the versions of the .NET runtimes that Akka.NET targets:

- v1.4.0 - .NET Standard 2.0 only
- v1.4.* - .NET Standard 2.0 & .NET Core 3.0 - this would be done as a part of "spanifying" parts of the Akka.IO, Akka.Persistence, Akka Serialization, and Akka.Remote systems in order to improve performance. .NET Core 3.0 would enter into the picture as a means of gradually moving our "spanification" efforts down into the serialization and I/O layers, which require access to APIs that are not available in .NET Standard at the moment.
- v1.5.0 and beyond - .NET 5.0? Who knows.

Here's the strategic question we have to wrangle as maintainers: how do we balance getting the best possible experience for Akka.NET users with supporting our enterprise users, many of whom are stuck with .NET Framework for the time being?

Technical purity is usually the losing argument here - Akka.NET needs to create as wide of a tent as possible, but supporting .NET Framework 4.5 in perpetuity isn't sustainable long-term either. I might answer this question by polling the Petabridge mailing list, but I wanted to invite some open discussion on Github first.

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #3851 - dropping .NET Framework 4.5.2 support.

Draft PR because we need to get rid of the old Helios transport package first.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/akka.net/pull/3945 needs to be merged into `dev` first before this can run successfully.

**Comment by Aaronontheweb** [comment]
Welp, here's where this build hit the wall:

```
https://github.com/akkadotnet/akka.net/blob/0a8c0390ee24927e3c381a99bca079ebc7e5b8e9/src/core/Akka/Configuration/Hocon/AkkaConfigurationSection.cs
```

... @Arkatufus - so what should we do with this given that we're moving HOCON as a stand-alone feature into Akka.NET? If we get rid of `AkkaConfigurationSection`?

**Comment by Aaronontheweb** [comment]
I think what we're going to end up doing here, so as to not introduce too many behavior changes at once, is wait and see how the new stand-alone HOCON integration goes and see if that library can offer a good solution.

**Comment by Arkatufus** [comment]
> 
> 
> Welp, here's where this build hit the wall:
> 
> https://github.com/akkadotnet/akka.net/blob/0a8c0390ee24927e3c381a99bca079ebc7e5b8e9/src/core/Akka/Configuration/Hocon/AkkaConfigurationSection.cs
> 
> ... @Arkatufus - so what should we do with this given that we're moving HOCON as a stand-alone feature into Akka.NET? If we get rid of `AkkaConfigurationSection`?

This should fix it: https://github.com/Arkatufus/akka.net/commit/3e08c21a41a732d3dfcb70bf169c45375129fdf7

**Comment by Arkatufus** [comment]
We should mark the old `System.Configuration` implementation as `deprecated` to prepare for standalone HOCON integration.

**Comment by Aaronontheweb** [comment]
> We should mark the old `System.Configuration` implementation as `deprecated` to prepare for standalone HOCON integration.

Have some API ideas for how we can do this...

**Comment by Aaronontheweb** [comment]
@Arkatufus retrying this PR with your fix

**Comment by Aaronontheweb** [comment]
Looks like we're good to go here. Going to merge this in and set the groundwork for stand-alone HOCON.

**Pull request merged**
