### PR TITLE
Moved the documentation to docfx

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
## Changes:
- Moved the documentation to docfx
- API Reference also generating by docfx
- Created a project with examples from the articles.  

## Changed articles:
- Added `Untyped Actor API` article
- Reworked `ReceiveActor API` article
- Added `Finite State Machine` article
- Reworked all concept's documentation
- Added Testing Actor Systems  article
- Updated `Cluster Singleton`, `Cluster Client` and `Distributed Pub/Sub` articles
- Updated `Fault Tolerance` article

Preview: http://akkanetdocfx.azurewebsites.net/

### CODE REVIEW

**Comment by Danthar** [comment]
Holy crap. Impressive work @alexvaluyskiy !

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy TeamCity isn't running this because the commit age is set to 12/20/2016. Please use http://stackoverflow.com/questions/454734/how-can-one-change-the-timestamp-of-an-old-commit-in-git to reset the timestamp

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb there is no code changes here. Is that make sense to reset the date?

**Comment by alexvaluyskiy** [comment]
@Danthar I've fixed the links

**Comment by Danthar** [comment]
What do we need to move forward on this ?

**Comment by alexvaluyskiy** [comment]
@Danthar Probably someone should do a proof-reading of the new docs. 
Then we should setup `docfx` on the build agents. And update our build scripts. After 1.2 we could merge this pull request

**Comment by Danthar** [comment]
I dont mind giving it a good read through. But is all content from the getakka.net website already in this WIP ? (excluding PR's on the getakka site that might have been merged in the meantime)

And once this is merged. We should define a migration strategy for how we are going to replace the existing website. With regards to existing url's, which we will probably brake, and such.
A quick fix could be to redirect any url under **/docs/*** to the search feature ?

Personally im fine with breaking the urls. Its not like we do this every year.

**Comment by alexvaluyskiy** [comment]
@Danthar this PR contains the latest docs from getakka.net repo, except of `Coordinated shutdown`

It is not possible to make this docs with backward compatibility with the old one

**Comment by sean-gilliam** [comment]
Overall it looks nice and clean. I didn't find to much wrong with it.  :+1: 

However, in the API references section, there's a ton of missing documentation that our current site currently displays. See http://api.getakka.net/docs/stable/html/5590F8C9.htm for comparison.

**Comment by alexvaluyskiy** [comment]
@sean-gilliam fixed

**Comment by Danthar** [comment]
I have been reading through the docs for the past few days. Overall it looks good. I know some articles are no longer fully up to date. There have been some PR's merged in the getakka repo lately.
But those are minor things. I am sure there are plenty of other places where our articles can be improved content wise.
However that is an issue that we should tackle outside of this PR.

If there are no further objections. I vote we merge this. @Aaronontheweb  @Horusiath  ?

**Pull request merged**
