### PR TITLE
Removed the nuget package references to Microsoft.Bcl.Immutable

### PR DESCRIPTION
**Pull request by GeertVL**
Removed all the remaining references to Microsoft.Bcl.Immutable as was indicated in #485

### CODE REVIEW

**Comment by GeertVL** [comment]
Ok I screwed it up. Sorry. I am going to fix it.

**Comment by GeertVL** [comment]
Locally I get a perfect build (build all).

**Comment by Aaronontheweb** [comment]
Click on the `X` next to the commit to view the build log.

My guess is that the component you're referencing isn't at the path of the nuget package, but rather at the path of your `Debug` or `Release` folder.

**Comment by GeertVL** [comment]
Finally. Nuget bug or error. It doesn't like two packages with different names and same namespaces.

**Comment by Aaronontheweb** [comment]
awesome, thank you @GeertVL - could you squash these commits per our contribution guidelines?

**Comment by GeertVL** [comment]
What do you mean with squashing?

**Comment by rogeralsing** [comment]
@GeertVL it is still 6 commits in total, squashing should result in a single commit.
(its aesthetics of the  project history, easier to see what commit added what features)

**Comment by GeertVL** [comment]
@Aaronontheweb I resolved the conflicts, squashed the commits and retested everything. I learned a lot by doing this git exercise. Will help me doing future PR's.

**Comment by Aaronontheweb** [comment]
glad to hear it @GeertVL - looks like there's still some conflicts with the .SLN though; would you mind rebasing on `dev` to pull it in?

If you ever need help with any of the Git stuff, please ask - we'd be more than happy to help!

**Comment by GeertVL** [comment]
@Aaronontheweb I am sorry , I was on vacation. Why did you close it?

**Pull request closed without merging**
