### PR TITLE
Change the base class of PrimitiveSerializers to SerializerWithStringManifest

### LINKED ISSUE #4986: Akka.Remote.Serialization.PrimitiveSerializers needs cross platform compatibility
Akka.Remote.Serialization.PrimitiveSerializers breaks when an actor system living inside a .Net core environment sends a remote message to ones that are living inside .Net Framework environment, and vice versa because of the namespace changes introduced between NetFx and NetCore.

Need to change the base class of the serializer to `SerializerWithStringManifest` to make sure that no future namespace changes will break the wire format again.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes  #4986

### CODE REVIEW

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Need to make this backwards wire compatible - we have to accept the manifests that could be produced using reflection and the old type names too, and we'll have to add unit tests to verify that.

**Comment by Arkatufus** [comment]
Alright, will do

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
@Arkatufus need to do API approvals as well here

**Comment by Arkatufus** [comment]
Done

**Comment by Martin-Molinero** [comment]
I'm getting `Serializer not defined for message with serializer id [6] and manifest []. Transient association error (association remains live). Cannot find manifest class [S] for serializer with id [17].` when using new akka remote `1.4.20` (or bigger) with an older version, think might be related to this change, breaks connection compatibility.

**Comment by Aaronontheweb** [comment]
Hi @Martin-Molinero - this looks like a new version --> old version breaking wire format change that we caused, and the reason why is because we standardized the the primitive type manifests because they varied between .NET Core and .NET Framework due to the breaking changes Microsoft introduced at the inception of .NET Core.

We're really sorry about this - we probably should have made this an opt-in feature some months _after_ introducing this serializer so you wouldn't be hit with this issue during a live upgrade. The work around for this now is probably to either just bite the bullet and upgrade everything, or to override this serializer with the one from the v1.4.19 source code and drop it later.

**Comment by Aaronontheweb** [comment]
@Martin-Molinero this should resolve this issue in v1.4.26 https://github.com/akkadotnet/akka.net/pull/5280

**Comment by Martin-Molinero** [comment]
@Aaronontheweb awesome ty! is there an ETA for v1.4.26?

**Comment by Aaronontheweb** [comment]
We can probably ship something simple soon

**Pull request merged**
