### PR TITLE
Configure duration for applying `MemberStatus.WeaklyUp`  to joining nodes

### PR DESCRIPTION
**Pull request by Aaronontheweb**
port of https://github.com/akka/akka/pull/29665

close https://github.com/akkadotnet/akka.net/issues/4849

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Looks like this did help some:

**Before**

```
[INFO][4/18/2021 7:41:06 PM][Thread 0069][akka.trttl.gremlin.tcp://StressSpec@localhost:58399/user/result6] [join 2 to seed nodes, in 9 nodes cluster] completed in [8095] ms
```

**After**

```
[INFO][4/18/2021 7:14:12 PM][Thread 0066][akka.trttl.gremlin.tcp://StressSpec@localhost:57599/user/result6] [join 2 to seed nodes, in 9 nodes cluster] completed in [7318] ms
```

**Comment by Aaronontheweb** [comment]
Looks like some issues with the `WeaklyUp` MNTR specs - I'll take a look at those.

**Comment by Aaronontheweb** [comment]
> Looks like some issues with the `WeaklyUp` MNTR specs - I'll take a look at those.

This was a bug in the `ClusterSettings` code - I was validating that the `allow-weakly-up-members` had to be less than 7 seconds, when the check really should be that it's greater than zero. I've fixed this since.

**Review by Arkatufus — APPROVED** [review]
LGTM

**Pull request merged**
