### PR TITLE
Added a local journal plugin backed by disk

### PR DESCRIPTION
**Pull request by joshgarnett**
LocalJournal is an akka persistence plugin that is backed by disk.  This follows a similar pattern as the LocalSnapshotStore, but supports the journal api methods.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@joshgarnett looks like a bunch of issues on Linux .NET Core

**Comment by Horusiath** [comment]
What is the motivation for it?

**Comment by Danthar** [comment]
Im with @Horusiath on this one. Whats wrong with using the sqlite version ? It does basically the same thing.

**Comment by joshgarnett** [comment]
I had some issues getting the sqlite plugin to work in Akka 1.2.3 on OSX.  That said, I just tried it again in Akka 1.3 and it appears to be working as expected.  I'll do some further testing and will close this out if it appears it isn't needed.

**Comment by joshgarnett** [comment]
Out of the box on Windows, I hit this error:

```
[ERROR][8/29/2017 1:37:44 PM][Thread 0005][akka://Cluster/system/akka.persistence.journal.sqlite] sqlite3
Cause: [akka://Cluster/system/akka.persistence.journal.sqlite#1566673401]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.DllNotFoundException: sqlite3
  at (wrapper managed-to-native) Microsoft.Data.Sqlite.Interop.NativeMethods+Sqlite3_sqlite3:sqlite3_open_v2 (intptr,Microsoft.Data.Sqlite.Interop.Sqlite3Handle&,int,intptr)
  at Microsoft.Data.Sqlite.Interop.NativeMethods+Sqlite3_sqlite3.open_v2 (System.IntPtr filename, Microsoft.Data.Sqlite.Interop.Sqlite3Handle& ppDb, System.Int32 flags, System.IntPtr vfs) [0x00000] in <d14cb13d623440949106bbb0219a5c86>:0 
  at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2 (System.String filename, Microsoft.Data.Sqlite.Interop.Sqlite3Handle& ppDb, System.Int32 flags, System.String vfs) [0x00022] in <d14cb13d623440949106bbb0219a5c86>:0 
  at Microsoft.Data.Sqlite.SqliteConnection.Open () [0x000e4] in <d14cb13d623440949106bbb0219a5c86>:0 
  at Akka.Persistence.Sqlite.ConnectionContext.Remember (System.String connectionString) [0x00050] in <c7fe081d188840c4bc7e845d186193a2>:0 
  at Akka.Persistence.Sqlite.Journal.SqliteJournal.PreStart () [0x00006] in <c7fe081d188840c4bc7e845d186193a2>:0 
  at Akka.Actor.ActorBase.AroundPreStart () [0x00000] in <ddd3922453fd4198bd591ddcb68d801d>:0 
  at Akka.Actor.ActorCell+<>c__DisplayClass168_0.<Create>b__0 () [0x00000] in <ddd3922453fd4198bd591ddcb68d801d>:0 
  at Akka.Actor.ActorCell.UseThreadContext (System.Action action) [0x0000c] in <ddd3922453fd4198bd591ddcb68d801d>:0 
  at Akka.Actor.ActorCell.Create (System.Exception failure) [0x00024] in <ddd3922453fd4198bd591ddcb68d801d>:0 
   --- End of inner exception stack trace ---
  at Akka.Actor.ActorCell.Create (System.Exception failure) [0x000b8] in <ddd3922453fd4198bd591ddcb68d801d>:0 
  at Akka.Actor.ActorCell.SysMsgInvokeAll (Akka.Dispatch.SysMsg.EarliestFirstSystemMessageList messages, System.Int32 currentState) [0x0009b] in <ddd3922453fd4198bd591ddcb68d801d>:0 
```

**Comment by joshgarnett** [comment]
I've gotten our local dev environment to use sqlite properly on osx and windows, so I'm going to close this PR.

**Pull request closed without merging**
