### PR TITLE
Refactor ActorSystemImpl constructor and methods

### PR DESCRIPTION
**Pull request by rodrigovidal**

### CODE REVIEW

**Comment by rogeralsing** [comment]
This seems to have broken something in the build. not sure what it could be though.
But this needs some extra eyes

**Comment by rodrigovidal** [comment]
I'll check it. Thank you.

**Comment by Aaronontheweb** [comment]
Yeah, these tests should not be failing - everything that Remote deployment uses has failed in this PR, including the `DaemonMsgCreateSerializer` (never failed before.)

**Comment by Aaronontheweb** [comment]
Going to close this PR - feel free to resend if you can get the test suite to pass again.

**Pull request closed without merging**
