### PR TITLE
changed version of .NET Core SDK being used on Linux

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Trying to solve the same problem as #3391, but from a different angle.

### CODE REVIEW

**Comment by Danthar** [comment]
@Aaronontheweb Is this still a thing ?

**Comment by Aaronontheweb** [comment]
@Danthar yeah, for the 1.3.* branches at least. Gets us some Linux tests again now that we're no longer doing Mono. You should still move forward with https://github.com/akkadotnet/akka.net/pull/3452 for the v1.4.0 rollout though.

**Comment by Aaronontheweb** [comment]
@Danthar I think I have a fix in-place here to resolve that `ClusterSpec` that failed on Linux... Issue is that a cancelled task wasn't actually throwing a `TaskCancellationException`... Has to be a platform difference issue, I think. We'll see ❓

**Comment by Aaronontheweb** [comment]
Threw in the towel on that spec -had to mute it on Mono for the exact same reason. Something in the underlying code doesn't throw on Linux when the cancellation token is invoked. So, guess this is good to go now.

**Pull request merged**
