### PR TITLE
Fix MNTR failure

### LINKED ISSUE #4060: MNTR Tests failing
There are MNTR tests persistent failures (i.e. in #4022 or #4057 ) that need to be resolved.

Example:
https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=25174&view=ms.vss-test-web.build-test-results-tab&runId=1072398&resultId=100021&paneView=debug

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #4060

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
MNTR failure is reproducing well - and that is perfect.

**Comment by IgorFedchenko** [comment]
[This](https://github.com/akkadotnet/akka.net/blob/63192fba8944a573eaf025dcaea62ca0fc4a51d8/src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs#L663-L670) expectation is failing (inner `ExpectOne`):
```csharp
EventFilter.Info(start: "Connected to", source:logSource).ExpectOne(() =>
 {
    EventFilter.Info(start: "Lost contact", source:logSource).ExpectOne(() =>
     {
         // shutdown server
         TestConductor.Shutdown(_remainingServerRoleNames.First()).Wait();
     });
 });
```

**Comment by IgorFedchenko** [comment]
Current issue is based on `logSource` filtering.

Node is getting `Lost connect ...` message, but the source of the message is `akka.trttl.gremlin.tcp://ClusterClientSpec@localhost:60832/user/client4`, which after `ToStringWithoutAddress()` is transformed into `/user/client4`, and comparing with expected `[akka://ClusterClientSpec/user/client4#1250951351]` address string, which of course does not match.

**Comment by IgorFedchenko** [comment]
Well, actually @Aaronontheweb seem to be already familiar with this issue - there is a nice commented-out line with `TODO` reference for #3867 . Since that one is merged, the fix was as easy as uncomment existing line and verify that it is working (and it is, like a charm).

**Comment by IgorFedchenko** [comment]
Wonder why CI shows that MNTR tests under .NET Core are failing , but the only failed tests it shows are  from .NET Framework Unit Tests (some racy test there).

And Windows MNTR works, so seems like the issue is resolved.

**Comment by IgorFedchenko** [comment]
Let me revert that initial space sign to run CI once more time, just to clear things up.

**Comment by Aaronontheweb** [comment]
Same spec failed on .NET Core for some reason - wonder if the way we're formatting the logs are different there.

**Comment by Aaronontheweb** [comment]
Going to re-run it to see if it's racy

**Pull request merged**
