### PR TITLE
Double wildcard implementation for ActorSelection

### PR DESCRIPTION
**Pull request by Arkatufus**
Double wildcard (**) selection feature for ActorSelection.
example:
`Sys.ActorSelection("/user/a/b2/**")` will select all children under "user/a/b2" recursively.

### CODE REVIEW

**Comment by Arkatufus** [comment]
right-o

**Comment by IgorFedchenko** [comment]
For whatever reason, could not make NBench to produce markdown report... But I can paste results from console output.

<details>
<summary>Before this PR</summary>

```
--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_new_actor_throughput ---------------
Tests the message delivery throughput of NEW ActorSelections to NEW actors
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 31 604,00 operations, Average: 31 604,00 operations, Min: 31 604,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 41 210,49 operations, Average / s: 36 843,66 operations, Min / s: 33 123,27 operations, StdDev / s: 2 764,03 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+Reused_ActorSelection_on_pre_existing_actor_throughput ---------------
Tests the message delivery throughput of REUSABLE ActorSelections to PRE-EXISTING actors
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 10 000,00 operations, Average: 10 000,00 operations, Min: 10 000,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 1 195 857,55 operations, Average / s: 1 057 097,16 operations, Min / s: 806 848,53 operations, StdDev / s: 119 098,18 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_pre_existing_actor_throughput ---------------
Tests the message delivery throughput of NEW ActorSelections to PRE-EXISTING actors. This is really a stress test.
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 10 000,00 operations, Average: 10 000,00 operations, Min: 10 000,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 793 342,27 operations, Average / s: 750 725,87 operations, Min / s: 695 497,35 operations, StdDev / s: 30 379,84 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_throughput ---------------
Tests the throughput of resolving an ActorSelection on a pre-existing actor via ResolveOne
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 69 186,00 operations, Average: 69 186,00 operations, Min: 69 186,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 69 071,30 operations, Average / s: 68 350,42 operations, Min / s: 67 063,86 operations, StdDev / s: 646,94 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_stress_test ---------------
Continuously creates actors and attempts to resolve them immediately. Used to surface race conditions.
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 19 653,00 operations, Average: 19 653,00 operations, Min: 19 653,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 23 480,54 operations, Average / s: 21 733,80 operations, Min / s: 19 168,87 operations, StdDev / s: 1 549,65 operations
```

</details>

<details>
<summary>After this PR</summary>

```
--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_new_actor_throughput ---------------
Tests the message delivery throughput of NEW ActorSelections to NEW actors
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 24 382,00 operations, Average: 24 382,00 operations, Min: 24 382,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 39 570,63 operations, Average / s: 36 495,06 operations, Min / s: 24 043,77 operations, StdDev / s: 4 621,72 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+Reused_ActorSelection_on_pre_existing_actor_throughput ---------------
Tests the message delivery throughput of REUSABLE ActorSelections to PRE-EXISTING actors
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 10 000,00 operations, Average: 10 000,00 operations, Min: 10 000,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 1 232 118,87 operations, Average / s: 1 168 783,35 operations, Min / s: 1 005 206,97 operations, StdDev / s: 59 018,05 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+New_ActorSelection_on_pre_existing_actor_throughput ---------------
Tests the message delivery throughput of NEW ActorSelections to PRE-EXISTING actors. This is really a stress test.
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 10 000,00 operations, Average: 10 000,00 operations, Min: 10 000,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 781 873,06 operations, Average / s: 729 128,97 operations, Min / s: 611 755,49 operations, StdDev / s: 52 683,60 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_throughput ---------------
Tests the throughput of resolving an ActorSelection on a pre-existing actor via ResolveOne
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 67 923,00 operations, Average: 67 923,00 operations, Min: 67 923,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 66 471,47 operations, Average / s: 64 425,78 operations, Min / s: 60 512,38 operations, StdDev / s: 2 209,63 operations

--------------- RESULTS: Akka.Tests.Performance.Actor.ActorSelectionSpecs+ActorSelection_ResolveOne_stress_test ---------------
Continuously creates actors and attempts to resolve them immediately. Used to surface race conditions.
--------------- DATA ---------------
[Counter] ActorSelectionOperationCompleted: Max: 19 308,00 operations, Average: 19 308,00 operations, Min: 19 308,00 operations, StdDev: 0,00 operations
[Counter] ActorSelectionOperationCompleted: Max / s: 25 251,93 operations, Average / s: 22 082,34 operations, Min / s: 19 677,88 operations, StdDev / s: 1 896,00 operations
```

</details>

**Comment by Aaronontheweb** [comment]
Thanks @IgorFedchenko - looks safe to merge. Performance numbers look about the same before and after.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko NBench markdown usually gets written out to the file system rather than the console

**Comment by IgorFedchenko** [comment]
> @IgorFedchenko NBench markdown usually gets written out to the file system rather than the console

Yeah, I was trying to find any files, or specify output directory to look there - but could not get anything generated...

**Review by Aaronontheweb — APPROVED** [review]

**Pull request merged**
