### PR TITLE
Print out contributors since release

### PR DESCRIPTION
**Pull request by skotzko**
Call `bash tools/contributors.sh` to get contribs since last release. Example usage below.

The formatting of the tabs is good in bash, just looks weird when pasted into Github.

```
>> bash tools/contibutors.sh
30 contributors since release v1.0.4

TOTAL	ADDED	REMOVED	AUTHOR
23369	5258	18111	Aaron Stannard
18827	16329	2498	Bartosz Sypytkowski
11994	9496	2498	Steffen Forkmann
6031	4637	1394	maxim.salamatko
1987	1667	320	Graeme Bradbury
1556	1149	407	Sean Gilliam
1118	1118	0	moliver
706	370	336	rogeralsing
616	576	40	Marek Kadek
501	5	496	Alex Koshelev
377	269	108	Jeff Cyr
280	208	72	willieferguson
150	98	52	Christian Palmstierna
85	63	22	Willie Ferguson
77	71	6	Emil Ingerslev
66	61	5	Grover Jackson
60	39	21	Alexander Pantyukhin
56	33	23	Uladzimir Makarau
55	54	1	rdavisau
51	18	33	alex-kondrashov
42	26	16	Silv3rcircl3
36	30	6	evertmulder
33	19	14	Filip Malachowicz
27	27	0	Andrew Skotzko
13	11	2	Suhas Chatekar
7	6	1	tintoy
4	2	2	Jonathan
2	1	1	neekgreen
2	1	1	Christopher Martin
2	1	1	Artem Borzilov
```

You can also pass in a specific release tag name, e.g. "v1.0.2". For example:
```
>> bash tools/contibutors.sh v1.0.2
41 contributors since release v1.0.2

TOTAL	ADDED	REMOVED	AUTHOR
39677	7263	32414	Aaron Stannard
20253	17637	2616	Bartosz Sypytkowski
11994	9496	2498	Steffen Forkmann
9401	9327	74	willieferguson
9317	8984	333	Willie Ferguson
6031	4637	1394	maxim.salamatko
3365	2282	1083	Sean Gilliam
2106	1265	841	rogeralsing
1987	1667	320	Graeme Bradbury
1699	124	1575	Jordan S. Jones
1118	1118	0	moliver
616	576	40	Marek Kadek
564	282	282	unknown
507	456	51	Thomas Tomanek
501	5	496	Alex Koshelev
377	269	108	Jeff Cyr
275	168	107	Gareth Budden
150	98	52	Christian Palmstierna
128	119	9	Nikita Tsukanov
77	71	6	Emil Ingerslev
73	65	8	rdavisau
66	61	5	Grover Jackson
61	57	4	Andrew Skotzko
60	39	21	Alexander Pantyukhin
56	33	23	Uladzimir Makarau
51	18	33	alex-kondrashov
46	19	27	Semyon Oshchepkov
42	26	16	Silv3rcircl3
36	30	6	evertmulder
33	19	14	Filip Malachowicz
13	11	2	Suhas Chatekar
8	4	4	Roger Johansson
7	6	1	tintoy
4	2	2	Jonathan
4	1	3	Stuart Blackler
3	3	0	Geert Van Laethem
2	1	1	neekgreen
2	1	1	ashic
2	1	1	Tomek Stojecki
2	1	1	Christopher Martin
2	1	1	Artem Borzilov
```

### CODE REVIEW

**Comment by rogeralsing** [comment]
This gets somewhat misleading, but I guess it cant be fixed w/o looking up user info from github (?)
```
9401    9327    74  willieferguson
9317    8984    333 Willie Ferguson
```

**Comment by Aaronontheweb** [comment]
might have been committing from two different computers with different git credentials

**Comment by Aaronontheweb** [comment]
this reads data directly from the git repository, which is decoupled from Github UserID

**Comment by skotzko** [comment]
@Aaronontheweb *sigh* build server wonkiness again

**Comment by Aaronontheweb** [comment]
@skotzko that was my fault - was messing around with TeamCity when you re-ran the build

**Comment by Horusiath** [comment]
I think, that actual columns should be: nr-of-commits (sort by this), LOCs added, LOCs removed, user name. I can make that, but also nice-to-have would be displaying this in github [tabular form](https://help.github.com/articles/github-flavored-markdown/#tables).

**Comment by Horusiath** [comment]
This is script version displaying and sorting by number of commits:

```bash
git log $release_tag..HEAD --oneline --numstat --pretty=format:%an --no-merges --abbrev-commit | awk 'author == "" { author = $0; commits[author] += 1; next } /^$/ { author = ""; next} {added[author] += $1; removed[author] +=$2 } END { for(author in added) { printf "%s\t%s\t%s\t%s\n", commits[author], added[author], removed[author], author } }' | sort -n -k1 -r
```

**Comment by skotzko** [comment]
@Horusiath good points. Fixing this now and re-submitting in a separate PR as my fork got a lil messed up.

**Pull request closed without merging**
