### PR TITLE
AsyncTaskScheduler #1410

### PR DESCRIPTION
**Pull request by Zetanova**
Added support for LongRunning Tasks

### CODE REVIEW

**Comment by Zetanova** [comment]
I created now a new branch cherry-pick the commits and push it to my dev, after i made a pull request from dev. Was is correct? And how to create a second feature pull-request ?

**Comment by Aaronontheweb** [comment]
to create a second feature pull-request, you need to do the following 

```
git checkout dev #gets you back to your local copy of our dev branch
git checkout -b new-feature-branch
```

and then cherry-pick your commits and send a PR.

Could you also squash these commits? That involves using `git rebase -i` - contributing.md explains this.

**Comment by Zetanova** [comment]
I rebased it to one commit and pushed oit with
```
git push -f origin branchName
```
But i cant make a PR or sync 
and dont realy know how to debug this

**Comment by Zetanova** [comment]
If i am switching to the branch i get following message
```
Switched to branch 'branchName'
Your branch and 'origin/dev' have diverged,
and have 3 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

**Pull request closed without merging**
